#!/bin/bash
/opt/karoshi/serversetup/distro/ubuntu-18.04/scripts/set_boot_status glusterfs off 1>/dev/null 2>/dev/null
/opt/karoshi/serversetup/distro/ubuntu-18.04/scripts/set_boot_status glusterd off 1>/dev/null 2>/dev/null
/opt/karoshi/serversetup/distro/ubuntu-18.04/scripts/set_boot_status glustereventsd off 1>/dev/null 2>/dev/null

