#!/bin/bash
service mysql start 2>&1
if [ "$?" != 0 ]
then
	sleep 5
fi

Ports="3306"

#Check that the service ports are up
for Port in $Ports
do
	PortCheck=0
	Counter=0
	while [ "$PortCheck" = 0 ]
	do
		#Check if we can see the Port open with netstat and keep looping until the Port is up
		PortCheck=$(netstat -vatupn | grep 'mysql' | grep -c ":$Port ")
		if [ "$PortCheck" = 0 ]
		then
			sleep 1
			#Give up after 60 seconds
			[ $Counter = 60 ] && exit 101
			let Counter=$Counter+1
		fi
	done	
done

#Check that we can connect to mysql
for i in {1..60}
do
	mysqladmin ping 1>/dev/null 2>/dev/null
	[ "$?" = 0 ] && exit
	sleep 1
done

