#!/bin/bash
Display=$(echo "$1" | tr -cd 'a-z')
[ -z "$Display" ] && display=html

service postfix stop > /dev/null 2>&1
service postfix start 2>&1

if [ "$?" != 0 ]
then
	sleep 5
fi

/opt/karoshi/serversetup/distro/ubuntu/scripts/control_services/check_port_status postfix start "$Display"
