#!/bin/bash
#Start mon on boot
chkconfig mon off
[ -f /opt/karoshi/start_on_boot/karoshi_services ] || touch /opt/karoshi/start_on_boot/karoshi_services
[ `grep -c -w mon /opt/karoshi/start_on_boot/karoshi_services` = 0 ] && echo mon,1 >> /opt/karoshi/start_on_boot/karoshi_services
