#!/bin/bash
#Start winbind on boot
chkconfig winbind off
[ -f /opt/karoshi/start_on_boot/karoshi_services ] || touch /opt/karoshi/start_on_boot/karoshi_services
[ `grep -c -w winbind /opt/karoshi/start_on_boot/karoshi_services` = 0 ] && echo winbind,3 >> /opt/karoshi/start_on_boot/karoshi_services
