#!/bin/bash
#archive_internet_logs
#Copyright (C) 2006  Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contact either at mpsharrad@karoshi.org.uk or jharris@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

DATE=`date +%F`

[ ! -d /home/internetdata/rawinternetlogs ] && mkdir -p /home/internetdata/rawinternetlogs
chmod 0640 /home/internetdata/rawinternetlogs
chmod u+X,g+X -R /home/internetdata/rawinternetlogs
chown -R root.itadmin /home/internetdata/rawinternetlogs

#Default to keeping logs for 5 years.
DURATION=1825

#Clear out old logs
find /home/internetdata/rawinternetlogs/* -mtime +$DURATION -exec rm {} \;

#Copy logs to archive folder
cp /var/log/squid3/access.log /home/internetdata/rawinternetlogs/"$DATE"_squid_access.log
cp /var/log/e2guardian/access.log /home/internetdata/rawinternetlogs/"$DATE"_dg_access.log

#Compress log files in archive folder - this avoids tar moaning if the log file is still being written to.

tar --force-local -z -c -f /home/internetdata/rawinternetlogs/"$DATE"_squid_access.log.tar.gz /home/internetdata/rawinternetlogs/"$DATE"_squid_access.log
tar --force-local -z -c -f /home/internetdata/rawinternetlogs/"$DATE"_dg_access.log.tar.gz /home/internetdata/rawinternetlogs/"$DATE"_dg_access.log

#Delete copied files
rm -f /home/internetdata/rawinternetlogs/"$DATE"_squid_access.log
rm -f /home/internetdata/rawinternetlogs/"$DATE"_dg_access.log

############################
#Clear logs
############################
echo > /var/log/squid3/access.log
echo > /var/log/e2guardian/access.log
