#!/bin/bash
#dgupdatefilterlist
#Copyright (C) 2006  Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contact either at mpsharrad@karoshi.org.uk or jharris@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

#Delete the current filtergroups list.
[ -f /etc/e2guardian/lists/filtergroupslist ] && rm -f /etc/e2guardian/lists/filtergroupslist
touch /etc/e2guardian/lists/filtergroupslist

for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
do
	FILTERGROUP=$(basename "$FILTERGROUPS")
	FILTERNUMBER=$(echo "$FILTERGROUP" | tr -cd "0-9")
	if [ "$FILTERGROUP" != f1 ]
	then
		#Check to see if any groups have been assigned to this filtergroup.
		if [ -d /etc/e2guardian/lists/filtergroups/"$FILTERGROUP"/assigned_groups ] 
		then
			#Check if there are any custom times for this filtergroup.
			if [ -d /etc/e2guardian/lists/filtertimes/"$FILTERGROUP" ]
			then
				#Check if we are any of the times set match the current time
				CurrentTime=$(date +%H%M)
				CurrentDayofWeek=$(date +%u)
				for FilterTimes in /etc/e2guardian/lists/filtertimes/"$FILTERGROUP"/*
				do
					FilterTimeData=$(basename "$FilterTimes")
					source /etc/e2guardian/lists/filtertimes/"$FILTERGROUP/$FilterTimeData"
					StartTime="$HOUR1$MINUTES1"
					EndTime="$HOUR2$MINUTES2"
					#Check for standard days of the week or every day of the week
					if [ "$CurrentDayofWeek" -ge 1 ] && [ "$DAYOFWEEK" -le 7 ] || [ "$DAYOFWEEK" = 11 ]
					then
						if [ "$CurrentDayofWeek" = "$DAYOFWEEK" ] || [ "$DAYOFWEEK" = 11 ]
						then
							#Check if we are in the time slot
							if [ "$CurrentTime" -gt "$StartTime" ] && [ "$CurrentTime" -lt "$EndTime" ]
							then
								FILTERNUMBER=$(echo "$FALLBACKFILTER" | tr -cd 0-9)
								echo "check 1-7 and 11 pass filternumer is now $FILTERNUMBER"
							fi
						fi
					fi

					#Check for Monday to Friday
					if [ "$DAYOFWEEK" = 8 ]
					then
						if [ "$CurrentDayofWeek" -ge 1 ] && [ "$CurrentDayofWeek" -le 5 ]
						then
							#Check if we are in the time slot
							if [ "$CurrentTime" -gt "$StartTime" ] && [ "$CurrentTime" -lt "$EndTime" ]
							then
								FILTERNUMBER=$(echo "$FALLBACKFILTER" | tr -cd 0-9)
							fi
						fi
					fi
					#Check Friday to Monday
					if [ "$DAYOFWEEK" = 9 ]
					then
						if [ "$CurrentDayofWeek" -ge 5 ] && [ "$CurrentDayofWeek" -le 7 ]
						then
							#Check if we are in the time slot
							if [ "$CurrentTime" -gt "$StartTime" ] && [ "$CurrentTime" -lt "$EndTime" ]
							then
								FILTERNUMBER=$(echo "$FALLBACKFILTER" | tr -cd 0-9)
							fi	
						fi
					fi
					#Check Saturday and Sunday
					if [ "$DAYOFWEEK" = 10 ]
					then
						if [ "$CurrentDayofWeek" -ge 6 ] && [ "$CurrentDayofWeek" -le 7 ]
						then
							#Check if we are in the time slot
							if [ "$CurrentTime" -gt "$StartTime" ] && [ "$CurrentTime" -lt "$EndTime" ]
							then
								FILTERNUMBER=$(echo "$FALLBACKFILTER" | tr -cd 0-9)
							fi
						fi
					fi
				done
			fi

			for ASSIGNEDGROUPS in /etc/e2guardian/lists/filtergroups/"$FILTERGROUP"/assigned_groups/*
			do
				ASSIGNEDGROUP=$(basename "$ASSIGNEDGROUPS")
				#Modify the assigned group if it is an anomaly.
				[ "$ASSIGNEDGROUP" = itadmin ] && ASSIGNEDGROUP=itadminstaff
				[ "$ASSIGNEDGROUP" = tech ] && ASSIGNEDGROUP=techstaff
				#Get all of the members of the group and update filtergroups file
				getent passwd | grep /"$ASSIGNEDGROUP"/ | cut -d: -f1 | sed "s/$/=filter$FILTERNUMBER/g" >> /etc/e2guardian/lists/filtergroupslist
			done
		fi
	fi
done

#Create stafflist for squid
echo samplestaffuser > /etc/squid/stafflist
getent passwd | grep /home/users/tech | cut -d: -f1 >> /etc/squid/stafflist
getent passwd | grep /home/users/itadmin | cut -d: -f1 >> /etc/squid/stafflist
getent passwd | grep /home/users/staff | cut -d: -f1 >> /etc/squid/stafflist
getent passwd | grep /home/users/officestaff | cut -d: -f1 >> /etc/squid/stafflist

service e2guardian reload 1>/dev/null
exit

