#!/bin/bash
#sysvsupport
#Copyright (C) 2012  Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contact either at mpsharrad@karoshi.org.uk or jharris@karoshi.org.uk
#
#Website: http://www.linuxschools.com

##########################
#SysV - much more reliable for starting, stopping, checking if services are running than upstart.
##########################

#Copy startup scripts back into /etc/init.d

[ -L /etc/init.d/apache2 ] && rm -f /etc/init.d/apache2
[ -L /etc/init.d/clamav-freshclam ] && rm -f /etc/init.d/clamav-freshclam
[ -L /etc/init.d/cups ] && rm -f /etc/init.d/cups
[ -L /etc/init.d/e2guardian ] && rm -f /etc/init.d/e2guardian
[ -L /etc/init.d/mailscanner ] && rm -f /etc/init.d/mailscanner
[ -L /etc/init.d/mon ] && rm -f /etc/init.d/mon
[ -L /etc/init.d/mysql ] && rm -f /etc/init.d/mysql
[ -L /etc/init.d/postgresql ] && rm -f /etc/init.d/postgresql
[ -L /etc/init.d/postfix ] && rm -f /etc/init.d/postfix
[ -L /etc/init.d/portmap ] && rm -f /etc/init.d/portmap
[ -L /etc/init.d/rpcbind ] && rm -f /etc/init.d/rpcbind
[ -L /etc/init.d/rsync ] && rm -f /etc/init.d/rsync
[ -L /etc/init.d/samba ] && rm -f /etc/init.d/samba
[ -L /etc/init.d/shorewall ] && rm -f /etc/init.d/shorewall
[ -L /etc/init.d/slapd ] && rm -f /etc/init.d/slapd
[ -L /etc/init.d/spamassassin ] && rm -f /etc/init.d/spamassassin
[ -L /etc/init.d/squid ] && rm -f /etc/init.d/squid
[ -L /etc/init.d/squid3 ] && rm -f /etc/init.d/squid3
[ -L /etc/init.d/squid-deb-proxy ] && rm -f /etc/init.d/squid-deb-proxy
[ -L /etc/init.d/ssh ] && rm -f /etc/init.d/ssh
[ -L /etc/init.d/tftpd-hpa ] && rm -f /etc/init.d/tftpd-hpa
[ -L /etc/init.d/xinetd ] && rm -f /etc/init.d/xinetd
[ -L /etc/init.d/dovecot ] && rm -f /etc/init.d/dovecot
[ -L /etc/init.d/vsftpd ] && rm -f /etc/init.d/vsftpd
[ -L /etc/init.d/sogo ] && rm -f /etc/init.d/sogo
[ -L /etc/init.d/memcached ] && rm -f /etc/init.d/memcached
[ -L /etc/init.d/isc-dhcp-server ] && rm -f /etc/init.d/isc-dhcp-server
[ -L /etc/init.d/glusterfs-server ] && rm -f /etc/init.d/glusterfs-server
[ -L /etc/init.d/monitorix ] && rm -f /etc/init.d/monitorix
[ -L /etc/init.d/freeradius ] && rm -f /etc/init.d/freeradius
[ -L /etc/init.d/dnsmasq ] && rm -f /etc/init.d/dnsmasq
[ -L /etc/init.d/winbind ] && rm -f /etc/init.d/winbind
[ -L /etc/init.d/openvpn ] && rm -f /etc/init.d/openvpn
[ -L /etc/init.d/openvpn ] && rm -f /etc/init.d/nfs-kernel-server
[ -L /etc/init.d/nginx ] && rm -f /etc/init.d/nginx
[ -L /etc/init.d/icecast2 ] && rm -f /etc/init.d/icecast2
[ -L /etc/init.d/avahi-daemon ] && rm -f /etc/init.d/avahi-daemon

cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/apache2 /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/apache2_karoshi /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/clamav-freshclam /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/cups /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/e2guardian /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/icecast2 /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/mailscanner /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/mon /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/mysql /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/postfix /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/postgresql /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/rsync /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/samba4 /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/shorewall /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/slapd /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/spamassassin /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/squid /etc/init.d/
[ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/squid3 ] && cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/squid3 /etc/init.d
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/squiddebproxy /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/ssh /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/tftpd-hpa /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/xinetd /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/dovecot /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/vsftpd /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/portmap /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/rpcbind /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/sogo /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/memcached /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/isc-dhcp-server /etc/init.d/
if [ ! -f /etc/init.d/glusterfs ]
then
	cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/glusterfs /etc/init.d/
fi
if [ ! -f /etc/init.d/minidlna ]
then
	cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/minidlna /etc/init.d/
fi
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/monitorix /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/freeradius /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/dnsmasq /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/openchange-ocsmanager /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/openvpn /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/nfs-kernel-server /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/nginx /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/zfs-mount-all /etc/init.d/
cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/mount-gluster-volumes /etc/init.d/
[ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/avahi-daemon ] && cp -f /opt/karoshi/serversetup/distro/ubuntu/scripts/initdscripts/avahi-daemon /etc/init.d/

#Check if we have zfs
if [[ $(ls -1 /etc/rc2.d/ | grep -c "zfs-mount-all") -gt 0 ]]
then
	#Make sure we are waiting for ZFS

	#Set minidlna to wait for zfs-mount-all
	if [[ $(grep -c zfs-mount-all /etc/init.d/minidlna) = 0 ]]
	then
		sed -i "s%reserveports samba4%reserveports samba4 zfs-mount-all%g" /etc/init.d/minidlna
	fi
	#Set gluster to wait for zfs-mount-all
	if [[ $(grep -c zfs-mount-all /etc/init.d/glusterfs) = 0 ]]
	then
		sed -i "s%reserveports samba4%reserveports samba4 zfs-mount-all%g" /etc/init.d/glusterfs
	fi
fi

#Get rid of any upstart and systemd configurations

for service in cups bind9 clamav-daemon mysql postgresql smbd nmbd squid ssh tftpd-hpa xinetd dovecot vsftpd nfs-server rpcbind portmap memcached isc-dhcp-server glusterfs monitorix freeradius samba dnsmasq windbind openvpn nfs-kernel-server statd nginx
do
	#Upstart
	#Make sure no scripts have been added to /etc/init for upstart.
	[[ $(ls /etc/init/"$service"* 2>/dev/null | wc -l) -gt 0 ]] && rm -f /etc/init/"$service"*

	#Systemd
	if [[ $(ls /lib/systemd/system/"$service"* 2>/dev/null | wc -l) -gt 0 ]]
	then
		#Disable the systemd service
		systemctl disable "$service".service

		#Get rid of any systemd configurations	
		rm -f /lib/systemd/system/"$service"*
	fi
done
exit

