#!/bin/bash
source /opt/karoshi/serversetup/variables/xdialog
source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/language/$LANGCHOICE/no_network
############################
#Show no network card error message
############################
Xdialog --title "$TITLE" \
--wrap --icon $ICON --rc-file $RCFILE --msgbox "$NO_NETWORK_CARD" 16 50
case $ in
0)
	exit 101;;
255)
	exit 101;;
esac
exit 101
