#!/bin/bash
#sslcertificate
#Copyright (C) 2006  The karoshi Team
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contact either at mpsharrad@karoshi.org.uk or jharris@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata
source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/xdialog
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/language/$LANGCHOICE/setupcertificate
#####################
#Check that ssl data source exists and ask to modify
#####################
/opt/karoshi/serversetup/scripts/sslcertificatedata
SSLSTOP=`cat $HOME/.tempdata/sslstop`
if [ $SSLSTOP = stop ]
then
exit
fi
#####################
#Show certificate change choice
#####################
DIALOG=${DIALOG=Xdialog}
tempfile=`tempfile 2>/dev/null` || tempfile=$HOME/.tempdata/sslchoice
trap "rm -f $tempfile" 0 1 2 5 15

$DIALOG --wrap --icon $ICON --rc-file $RCFILE --backtitle "$TITLE" \
        --title "$TITLE" --clear \
        --checklist "$CHECKLISTMSG" 40 61 5 \
        "Apache" "$APACHEMSG" ON \
	"Pop3s" "$POP3MSG" OFF 2> $HOME/.tempdata/sslchoice

retval=$?

SSLCHOICE=(`sed 's/[/]/ /g' $HOME/.tempdata/sslchoice | tr 'A-Z' 'a-z'`)

case $retval in
  0)
    CHOICE=go;;
  1)
    CHOICE=stop;;
  255)
    CHOICE=stop;;
esac

if [ $CHOICE = stop ]
then
rm -f $HOME/.tempdata/sslstop
Xdialog --title "$TITLE" \
--wrap --icon $ICON --rc-file $RCFILE --msgbox "$TITLE $CANCELLEDMSG" 16 50
case $ in
0)
	exit;;
255)
	exit;;
esac
exit
fi


function apache {
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/apachesslcert
}

function pop3s {
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/pop3sslcert
}

ARRAYCOUNT=`echo ${#SSLCHOICE[@]}`
COUNTER=0
         while [ $COUNTER -lt $ARRAYCOUNT ]; do
         SSLFUNCTION=`echo ${SSLCHOICE[$COUNTER]}`
	 $SSLFUNCTION
         let COUNTER=COUNTER+1
         done

############################
#Display completed message
############################
rm -f $HOME/.tempdata/sslstop
Xdialog --title "$TITLE" \
--wrap --icon $ICON --rc-file $RCFILE --infobox "$TITLE $COMPLETEDMSG" 16 50 2000
case $ in
0)
	exit;;
255)
	exit;;
esac
exit

