#!/bin/bash
#sslcertificatedata
#Copyright (C) 2006  The karoshi Team
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contact either at mpsharrad@karoshi.org.uk or jharris@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata
source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/xdialog
source /opt/karoshi/serversetup/variables/years
source /opt/karoshi/serversetup/language/$LANGCHOICE/sslcertificatedata
echo go > $HOME/.tempdata/sslstop 

#####################
#Set default values for the ssl certificate
#####################

CHOICE=go
COUNTRYCODE2=GB
STATE=County
LOCALITY=City
ORGANISATIONNAME=Karoshi
UNITNAME=ICT_Dept
COMMONNAME=$HOSTNAME
CONTACTEMAIL=email

echo $COUNTRYCODE2 > /opt/karoshi/serversetup/variables/ssldata
echo $STATE >> /opt/karoshi/serversetup/variables/ssldata
echo $LOCALITY >> /opt/karoshi/serversetup/variables/ssldata
echo $ORGANISATIONNAME >> /opt/karoshi/serversetup/variables/ssldata
echo $UNITNAME >> /opt/karoshi/serversetup/variables/ssldata
echo $COMMONNAME >> /opt/karoshi/serversetup/variables/ssldata
echo $CONTACTEMAIL >> /opt/karoshi/serversetup/variables/ssldata

exit
