#!/bin/bash
Display=$(echo "$1" | tr -cd 'a-z')
[ -z "$Display" ] && Display=html

systemctl stop bind9 2>&1

[ "$?" != 0 ] && sleep 5

/opt/karoshi/serversetup/distro/ubuntu-18.04/scripts/control_services/check_port_status bind stop "$Display"
