#!/bin/bash
Display=$(echo "$1" | tr -cd 'a-z')
[ -z "$Display" ] && Display=html

systemctl stop dnsmasq 2>&1

[ "$?" != 0 ] && sleep 5

/opt/karoshi/serversetup/distro/ubuntu/scripts/control_services/check_port_status dnsmasq stop "$Display"
