#!/bin/bash
Display=$(echo "$1" | tr -cd 'a-z')
[ -z "$Display" ] && display=html

systemctl start dnsmasq 2>&1

[ "$?" != 0 ] && sleep 5

/opt/karoshi/serversetup/distro/ubuntu/scripts/control_services/check_port_status dnsmasq start "$Display"
