#!/bin/bash
Display=$(echo "$1" | tr -cd 'a-z')
[ -z "$Display" ] && Display=html

systemctl start postfix 2>&1

if [ "$?" = 0 ]
then
	/opt/karoshi/serversetup/distro/ubuntu-18.04/scripts/control_services/check_port_status postfix start "$Display"
else
	sleep 5
fi

