#!/bin/bash
Display=$(echo "$1" | tr -cd 'a-z')
[ -z "$Display" ] && Display=html

systemctl stop freeradius 2>&1

if [ "$?" = 0 ]
then
	/opt/karoshi/serversetup/distro/ubuntu/scripts/control_services/check_port_status radius stop "$Display"
else
	sleep 5
fi

