#!/bin/bash
Display=$(echo "$1" | tr -cd 'a-z')
[ -z "$Display" ] && Display=html

systemctl stop samba4 2>&1
if [ "$?" != 0 ]
then
	sleep 5
fi

/opt/karoshi/serversetup/distro/ubuntu-18.04/scripts/control_services/check_port_status samba stop "$Display"

#Check to see if this is a pdc or adc
if [[ $(grep -w -c sysvol /etc/samba/smb.conf) -gt 0 ]]
then
	#Check that all samba4 processes have stopped
	for PROCESS in $(ps aux | grep "/usr/sbin/samba" | grep -v "grep" | sed "s/ * / /g" | cut -d" " -f2 | tr -cd "0-9\ \n")
	do
		echo Stopping "$PROCESS"
		#kill -9 "$PROCESS"
	done
fi

