#!/bin/bash
#Copyright (C) 2011 Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk


#Check for federated servers
[ ! -d /opt/karoshi/server_network/federated_ldap_servers/ ] && exit
[ `ls -1 /opt/karoshi/server_network/federated_ldap_servers/ | wc -l` = 0 ] && exit

if [  ! -d /opt/karoshi/server_network/password_sync/ ]
then
mkdir -p /opt/karoshi/server_network/password_sync/
chmod 0700 /opt/karoshi/server_network/password_sync/
fi

#Check each federated server for any passwords that need syncing.
function check_for_passwords_to_change {
for FEDERATEDLDAPSERVERS in /opt/karoshi/server_network/federated_ldap_servers/*
do
FEDERATEDLDAPSERVER=`basename $FEDERATEDLDAPSERVERS`
echo Checking "for" passwords to change on $FEDERATEDLDAPSERVER
#Copy /opt/karoshi/server_network/password_sync ldiff files back to the main server
scp root@$FEDERATEDLDAPSERVER:"/opt/karoshi/server_network/password_sync/*" /opt/karoshi/server_network/password_sync/ 2>/dev/null
done
} 


function update_passwords {
if [ `ls -1 /opt/karoshi/server_network/password_sync/ | wc -l` -gt 0 ]
then
for LDIF_FILES in /opt/karoshi/server_network/password_sync/*
do
LDIF_FILE=`basename $LDIF_FILES`
echo Syncing password - $LDIF_FILE

#Sync password on the main server
echo Syncing password on $HOSTNAME
LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
ldapmodify -x -D "cn=admin,dc=karoshi,dc=local" -w $LDAPPASS -f /opt/karoshi/server_network/password_sync/$LDIF_FILE

#Sync passwords on all other federated servers

for FEDERATEDLDAPSERVERS in /opt/karoshi/server_network/federated_ldap_servers/*
do
FEDERATEDLDAPSERVER=`basename $FEDERATEDLDAPSERVERS`
scp /opt/karoshi/server_network/password_sync/$LDIF_FILE root@$FEDERATEDLDAPSERVER:"/opt/karoshi/server_network/password_sync/"
ssh -x -o PasswordAuthentication=no $FEDERATEDLDAPSERVER '
echo Syncing password on $HOSTNAME
LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
ldapmodify -x -D "cn=admin,dc=karoshi,dc=local" -w $LDAPPASS -f /opt/karoshi/server_network/password_sync/'$LDIF_FILE'
rm -f /opt/karoshi/server_network/password_sync/'$LDIF_FILE'
'
done
rm -f /opt/karoshi/server_network/password_sync/$LDIF_FILE
done
fi
}

check_for_passwords_to_change
update_passwords
