#!/bin/bash
#Copyright (C) 2010  Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
########################
#Get variables
########################
LOG_DATE=`date +%F`
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: configureldap - incorrect number of arguments."<br>"
exit 101
fi
read -t 3 DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-/'`

REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
PDCSERVER=`echo "$DATA" | cut -s -d: -f4`
PDCIP=`echo "$DATA" | cut -s -d: -f5`

if [ $REMOTE_USER'null' = null ]
then
echo `date`: configureldap - Blank remote user."<br>"
exit 101
fi

if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: configureldap - Blank remote tcpip address."<br>"
exit 101
fi

if [ $PDCSERVER'null' = null ]
then
echo `date`: configureldap - Blank PDC."<br>"
exit 101
fi

#PDCIP=`net lookup $PDCSERVER`

if [ $PDCIP'null' = null ]
then
echo `date`: configureldap - Blank TCPIP."<br>"
exit 101
fi

#Check to see that we can ping the PDC
ping -c 2 $PDCIP 1>/dev/null
if [ `echo $?` != 0 ]
then
echo `date` : configureldap - $PINGFAIL'.'"<br>"
exit 101
fi

[ -d /opt/karoshi/.tempdata ] || mkdir /opt/karoshi/.tempdata

LANGCHOICE=englishuk
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/modules/fileserver/configureldap ] || LANGCHOICE=englishuk
source /opt/karoshi/serversetup/language/$LANGCHOICE/modules/ldap/setupldap

source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/variables/tcpip
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/software

########################
#Add PDC ip to /etc/hosts
########################
echo $PDCIP'	''	'$PDCSERVER $PDCSERVER.internal >> /etc/hosts
#######################
#Setup ldap
######################
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/nsswitch.conf /etc/
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/pam.d/* /etc/pam.d/
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/configfiles/etc_ldap.conf /etc/ldap.conf
[ -d /etc/openldap ] && cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/configfiles/etc_openldap_ldap.conf /etc/openldap/ldap.conf
[ -d /etc/ldap ] && cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/configfiles/etc_openldap_ldap.conf /etc/ldap/ldap.conf
#Modify ldap.conf with correct ip for the pdc
sed -i "s/127.0.0.1/$PDCIP/g" /etc/ldap.conf
exit

