#!/bin/bash
#import users
#Copyright (C) 2008 Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

SERVERNAME=`echo $1`
[ $SERVERNAME'null' = null ] && exit

[ -d /opt/karoshi/.tempdata/ ] || mkdir /opt/karoshi/.tempdata/
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/software
source /opt/karoshi/serversetup/language/$LANGCHOICE/modules/ldap/setupldap

##############################
#Export the ldap database from the PDC to the slave ldap server
##############################

#Create list of users to set uids the same as the pdc
getent passwd | cut -d: -f1,3,6 > /opt/karoshi/.tempdata/userlist.$$
#Copy user list to the slave ldap server
echo $COPYLDAPMSG
echo
scp /opt/karoshi/.tempdata/userlist.$$ root@$SERVERNAME:"/opt/karoshi/.tempdata/"
rm -f /opt/karoshi/.tempdata/userlist.$$

LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
ENCRYPTEDPASS=`slappasswd -s $LDAPPASS`
[ -f /opt/karoshi/.tempdata/master.$$.ldif ] && rm -f /opt/karoshi/.tempdata/master.$$.ldif
touch /opt/karoshi/.tempdata/master.$$.ldif
chmod 0600 /opt/karoshi/.tempdata/master.$$.ldif
chown root.root /opt/karoshi/.tempdata/master.$$.ldif
#service ldap stop
#Create ldif file of all users

slapcat -s "ou=People,dc=karoshi,dc=local" -l /opt/karoshi/.tempdata/master.$$.ldif
scp /opt/karoshi/.tempdata/master.$$.ldif root@$SERVERNAME:"/opt/karoshi/.tempdata/"
rm -f /opt/karoshi/.tempdata/master.$$.ldif
echo '<br><br>'
##########################
#Import ldap users to the slave ldap server
##########################
ssh -x -o PasswordAuthentication=no $SERVERNAME '
#Make a backup of the current ldap database on the slave ldap server
echo '$SERVERNAME - $BACKUPMSG'"<br><br>"
sleep 3
[ -f /opt/karoshi/.tempdata/ldapbackup.$$.ldif ] && rm -f /opt/karoshi/.tempdata/ldapbackup.$$.ldif
touch /opt/karoshi/.tempdata/ldapbackup.$$.ldif
chmod 0600 /opt/karoshi/.tempdata/ldapbackup.$$.ldif
slapcat -l /opt/karoshi/.tempdata/ldapbackup.$$.ldif
#Delete current users from ldap database
echo '$SERVERNAME - $DELETEUSERSMSG'"<br><br>"
ldapdelete -x -w '$LDAPPASS' -D "cn=admin,dc=karoshi,dc=local" -r "ou=People,dc=karoshi,dc=local"
/opt/karoshi/serversetup/distro/'$DISTROCHOICE'/scripts/control_services/ldap_stop
#Import the data from the pdc
echo '$IMPORTUSERSMSG'"<br><br>"
sleep 3
slapadd -v -c -l /opt/karoshi/.tempdata/master.'$$'.ldif
#Set slave ldap pass to be the same as the pdc
echo '$LDAPPASS' > /etc/ldap.secret
PASSWORDLINENO=`grep -n ^rootpw '$LDAPPATH'/slapd.conf | cut -d: -f1`
sed -i $PASSWORDLINENO"c"\rootpw"		"'$ENCRYPTEDPASS' '$LDAPPATH'/slapd.conf
/opt/karoshi/serversetup/distro/'$DISTROCHOICE'/scripts/control_services/ldap_start
#########################
#Set users to same UID as the pdc and make sure that home folder and email file has correct permissions
#########################
echo '$SETUSERPERMS'"<br><br>"
echo
sleep 3
/opt/karoshi/"useful scripts"/createmailfolders
NO_OF_USERS=`cat /opt/karoshi/.tempdata/userlist.'$$' | wc -l`
COUNTER=1
while [ $COUNTER -le $NO_OF_USERS ]
do
USERDATA=`sed -n $COUNTER,$COUNTER"p" /opt/karoshi/.tempdata/userlist.'$$'`
LOGINNAME=`echo $USERDATA | cut -d: -f1`
LOGINUID=`echo $USERDATA | cut -d: -f2`
LOGINHOME=`echo $USERDATA | cut -d: -f3`
if [ $LOGINUID -ge 500 ]
then
if [ `echo $LOGINHOME | grep -c ^/home/` -gt 0 ] && [ $LOGINHOME != /home/ ] && [ `echo $LOGINNAME | grep -c ^exam` = 0 ]
then
echo Username: $LOGINNAME"<br>"
echo UserID: $LOGINUID"<br>"
echo Home Directory: $LOGINHOME"<br>"
#Ensure that UID is the same
#smbldap-usermod -u $LOGINUID $LOGINNAME
#Set permissions on users home folder
if [ -d $LOGINHOME ]
then
echo '$OWNERMSG'"<br>"
chown -R $LOGINNAME $LOGINHOME"<br>"
else
#Create home folder
echo '$CREATEFOLDERMSG'"<br>"
[ ! -d $LOGINHOME/Mail ] && mkdir -p $LOGINHOME/Mail
[ ! -f $LOGINHOME/Mail/INBOX.Drafts ] && cp /opt/karoshi/.tempdata/INBOX.Drafts $LOGINHOME/Mail/
[ ! -f $LOGINHOME/Mail/INBOX.Sent ] && cp /opt/karoshi/.tempdata/INBOX.Sent $LOGINHOME/Mail/
[ ! -f $LOGINHOME/Mail/INBOX.Trash ] && cp /opt/karoshi/.tempdata/INBOX.Trash $LOGINHOME/Mail/
[ ! -f $LOGINHOME/.mailboxlist ] && cp /opt/karoshi/.tempdata/.mailboxlist $LOGINHOME/
chmod 0700 -R $LOGINHOME
chown -R $LOGINNAME $LOGINHOME
fi
#Set permissions on the users mail folder
if [ -f /var/spool/mail/$LOGINNAME ]
then
echo '$MAILMSG'"<br><br>"
chown $LOGINNAME /var/spool/mail/$LOGINNAME
fi
fi
fi
let COUNTER=$COUNTER+1
done
#Remove temp files
rm -f /opt/karoshi/.tempdata/userlist.'$$'
rm -f /opt/karoshi/.tempdata/master.'$$'.ldif
'
exit
