#!/bin/bash
#setupldap
#Copyright (C) 2008 Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
#########################
#Add log entry
#########################
echo '##############'setupldap'##############' >> /opt/karoshi/serversetup/install_log
date >> /opt/karoshi/serversetup/install_log
touch /opt/karoshi/serversetup/setuplog
if [ `grep -c "$TITLE" /opt/karoshi/serversetup/setuplog` = 0 ]
then
echo setupldap:$TITLE:/opt/karoshi/serversetup/pdc/scripts/setupldap >> /opt/karoshi/serversetup/setuplog
chmod 0600 /opt/karoshi/serversetup/setuplog
fi

[ ! -d /opt/karoshi/.tempdata/ ] && mkdir /opt/karoshi/.tempdata/

[ -e /opt/karoshi/serversetup/variables/language ] || /opt/karoshi/serversetup/changelanguage
[ -e /opt/karoshi/serversetup/variables/distro ] || /opt/karoshi/serversetup/changedistro

source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/variables/years
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/software
source /opt/karoshi/serversetup/language/$LANGCHOICE/modules/ldap/setupldap
source /opt/karoshi/server_network/domain_information/domain_name

#Section flags
ADDDEFAULTGROUPS=yes
DO_GROUPMAPS=no
IMPORTUSERS=yes
IMPORTMACHINES=yes

#Get domain password
if test -f /opt/karoshi/serversetup/variables/initial_password.gpg
then
grep -w root /etc/shadow | cut -d: -f2 | gpg --no-tty --passphrase-fd 0 /opt/karoshi/serversetup/variables/initial_password.gpg
LDAPPASS=`cat /opt/karoshi/serversetup/variables/initial_password`
rm -f /opt/karoshi/serversetup/variables/initial_password
fi

#Get ldap password from ldap.secret
[ -f /etc/ldap.secret ] && LDAPPASS=`sed -n 1,1p /etc/ldap.secret`

#Make sure service runs at boot
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/ldap

#Make sure samba.schema is there
if [ -d /etc/ldap/schema ]
then
if [ ! -f /etc/ldap/schema/samba.schema ]
then
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/ldap/samba.schema /etc/ldap/schema/
chmod 0644 /etc/ldap/schema/samba.schema
fi
fi

#Start ldap if not running
[ `ps -e | grep -c ldap` = 0 ] && /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ldap_start

[ $LDAPPASS'null' = null ] && LDAPPASS=$RANDOM


ENCRYPTEDPASS=`slappasswd -s $LDAPPASS`

#Encryted password cannot contain / because of sed below
COUNTER=1
while [ `echo $ENCRYPTEDPASS | grep -c /` -gt 0 ]
do
ENCRYPTEDPASS=`slappasswd -s $LDAPPASS`
let COUNTER=$COUNTER+1
[ $COUNTER = 100 ] && break
done


##############################
#Configure LDAP
##############################
function configure_ldap {
echo '<li>'$CONFIGURELDAPMSG'</li><br>'
#Copy in slapd.conf
echo Copying in slapd.conf,slapd_karoshi.access.conf and ldap.conf'<br><br>'

cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/slapd.conf $LDAPPATH
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/etc_openldap_ldap.conf $LDAPPATH/ldap.conf
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/slapd_karoshi.access.conf $LDAPPATH

#Edit slapd.conf with new password


#This doesnt work with a / in the password
sed -i 's/CHANGETHIS/'$ENCRYPTEDPASS'/g' $LDAPPATH/slapd.conf
#Apply changes
echo '<li>'$RESTARTLDAPMSG'</li><br>'

/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ldap_stop 1>/dev/null 2>/dev/null

if [ -d $LDAPPATH/slapd.d ]
then
[ -d $LDAPPATH/slapd.$$ ] && rm -f -R $LDAPPATH/slapd.$$
mv $LDAPPATH/slapd.d $LDAPPATH/slapd.$$
mkdir $LDAPPATH/slapd.d
slaptest -f $LDAPPATH/slapd.conf -F $LDAPPATH/slapd.d
chown -R $LDAPUSER.$LDAPUSER $LDAPPATH/slapd.d
rm -f /var/lib/ldap/*
#rm -f -R $LDAPPATH/slapd.d
fi
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ldap_start 1>/dev/null 2>/dev/null

#Copy in new smb.conf
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/configfiles/smb_ldap.conf /etc/samba/smb.conf
source /opt/karoshi/.tempdata/domain_name
sed -i 's/CHANGETHISDOMAINNAME/'$SAMBADOMAIN'/g' /etc/samba/smb.conf
#restart samba

/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/samba_stop 1>/dev/null 2>/dev/null
sleep 1
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/samba_start
echo '<li>Setting samba root ldap password</li><br>'
smbpasswd -w $LDAPPASS
#Copy in smbldaptools.conf

cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/smbldap.conf /etc/smbldap-tools/

#Edit smbldaptools.conf
SIDID=`net getlocalsid | cut -d' ' -f6`
SIDLINENO=`grep -n ^SID= /etc/smbldap-tools/smbldap.conf | cut -d: -f1`
sed -i $SIDLINENO'c'\SID=\""$SIDID"\" /etc/smbldap-tools/smbldap.conf
#Copy in smbldap_bind.conf
echo '<li>Copying in smbldap_bind.conf</li><br>'

cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/smbldap_bind.conf /etc/smbldap-tools/
#Edit smbldap_bind.conf
echo '<li>Editing smbldap_bind.conf</li><br>'

PASSLINENO=`grep -n ^masterPw= /etc/smbldap-tools/smbldap_bind.conf | cut -d: -f1`
sed -i $PASSLINENO'c'\masterPw=\""$LDAPPASS"\" /etc/smbldap-tools/smbldap_bind.conf
#Set permissions
chmod 0644 /etc/smbldap-tools/smbldap.conf
chmod 0600 /etc/smbldap-tools/smbldap_bind.conf

#Populate ldap with existing users and groups - ldap root password set to random password
#Change this to be the domain password

LDAPROOTPASS=$LDAPPASS
echo '<li>'$POPULATEMSG'</li><br>'

echo -e ""$LDAPROOTPASS"\n"$LDAPROOTPASS"" | smbldap-populate -u 500 -g 500 1>/dev/null

#Change ldap userid start number

echo dn: sambaDomainName=$SAMBADOMAINlcase,dc=karoshi,dc=local > /opt/karoshi/.tempdata/uidstartnumber.$$
echo changetype: modify >> /opt/karoshi/.tempdata/uidstartnumber.$$
echo replace: uidNumber >> /opt/karoshi/.tempdata/uidstartnumber.$$
echo uidNumber: 5001 >> /opt/karoshi/.tempdata/uidstartnumber.$$
echo - >> /opt/karoshi/.tempdata/uidstartnumber.$$
echo replace: gidNumber >> /opt/karoshi/.tempdata/uidstartnumber.$$
echo gidNumber: 5001 >> /opt/karoshi/.tempdata/uidstartnumber.$$
echo - >> /opt/karoshi/.tempdata/uidstartnumber.$$

ldapmodify -x -D "cn=admin,dc=karoshi,dc=local" -w $LDAPROOTPASS -f /opt/karoshi/.tempdata/uidstartnumber.$$
rm -f /opt/karoshi/.tempdata/uidstartnumber.$$
}

function add_default_groups {
#Import ldif files
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ldap_stop
echo "<br>"
sed "s/S-1-5-21-1563395597-2327927142-1296001331/$SIDID/g" /opt/karoshi/serversetup/all/configfiles/ldap/groups.ldif > /opt/karoshi/.tempdata/groups.ldif
slapadd -c -l /opt/karoshi/.tempdata/groups.ldif
rm -f /opt/karoshi/.tempdata/groups.ldif
}

function do_groupmaps {
###############################
#Do groupmaps
###############################
if [ $DO_GROUPMAPS = yes ]
then
net groupmap cleanup
net groupmap add rid=512 ntgroup="Domain Admins" unixgroup=tech
net groupmap modify ntgroup="Domain Admins" unixgroup=tech type=domain
net groupmap add ntgroup="guests" unixgroup=guests
net groupmap add ntgroup="exams" unixgroup=exams
net groupmap add ntgroup="staff" unixgroup=staff
net groupmap add ntgroup="itadmin" unixgroup=itadmin
net groupmap add ntgroup="officestaff" unixgroup=officestaff
net groupmap add ntgroup="nonteachingstaff" unixgroup=nonteachingstaff
net groupmap add ntgroup="studentstaff" unixgroup=studentstaff
net groupmap add ntgroup="smt" unixgroup=smt
net groupmap add ntgroup="bursar" unixgroup=bursar
net groupmap add ntgroup="pupiloffice" unixgroup=pupiloffice

COUNTER=$STARTYEAR
         while [  $COUNTER -le $ENDYEAR ]; do
             net groupmap add ntgroup="yr$COUNTER" unixgroup=yr$COUNTER
             let COUNTER=COUNTER+1
         done
fi
}


function create_users {
#Import ldif files

sed "s/S-1-5-21-1563395597-2327927142-1296001331/$SIDID/g" /opt/karoshi/serversetup/all/configfiles/ldap/personnel.ldif > /opt/karoshi/.tempdata/personnel.ldif
sed "s/S-1-5-21-1563395597-2327927142-1296001331/$SIDID/g" /opt/karoshi/serversetup/all/configfiles/ldap/students.ldif > /opt/karoshi/.tempdata/students.ldif
sed "s/S-1-5-21-1563395597-2327927142-1296001331/$SIDID/g" /opt/karoshi/serversetup/all/configfiles/ldap/other.ldif > /opt/karoshi/.tempdata/other.ldif
slapadd -c -l /opt/karoshi/.tempdata/personnel.ldif
slapadd -c -l /opt/karoshi/.tempdata/students.ldif
slapadd -c -l /opt/karoshi/.tempdata/other.ldif

[ -f /opt/karoshi/.tempdata/master.ldif ] && slapadd -c -l /opt/karoshi/.tempdata/master.ldif
#Make sure that permissions are correct in the ldap folder
chown $LDAPUSER.$LDAPUSER -R /var/lib/ldap
#Start ldap
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ldap_start
echo "<br><br>"
sleep 1
#Set user permissions and create folders
#Create list of users
getent passwd | cut -d: -f1,3,6 > /opt/karoshi/.tempdata/userlist.$$

echo $SETUSERPERMS"<br><br>"
sleep 1
/opt/karoshi/"useful scripts"/createmailfolders
NO_OF_USERS=`cat /opt/karoshi/.tempdata/userlist.$$ | wc -l`
COUNTER=1
while [ $COUNTER -le $NO_OF_USERS ]
do
USERDATA=`sed -n $COUNTER,$COUNTER"p" /opt/karoshi/.tempdata/userlist.$$`
LOGINNAME=`echo $USERDATA | cut -d: -f1`
LOGINUID=`echo $USERDATA | cut -d: -f2`
LOGINHOME=`echo $USERDATA | cut -d: -f3`
if [ $LOGINUID -ge 500 ]
then
if [ `echo $LOGINHOME | grep -c ^/home/` -gt 0 ] && [ $LOGINHOME != /home/ ] && [ `echo $LOGINNAME | grep -c ^exam` = 0 ]
then
echo Username: $LOGINNAME"<br>"
echo UserID: $LOGINUID"<br>"
echo Home Directory: $LOGINHOME"<br>"
#Ensure that UID is the same
#smbldap-usermod -u $LOGINUID $LOGINNAME
#Set permissions on users home folder
if [ -d $LOGINHOME ]
then
echo $OWNERMSG"<br>"
chown -R $LOGINNAME $LOGINHOME
echo "<br>"
else
#Create home folder
echo $CREATEFOLDERMSG"<br>"
[ ! -d $LOGINHOME/Mail ] && mkdir -p $LOGINHOME/Mail
[ ! -f $LOGINHOME/Mail/INBOX.Drafts ] && cp /opt/karoshi/.tempdata/INBOX.Drafts $LOGINHOME/Mail/
[ ! -f $LOGINHOME/Mail/INBOX.Sent ] && cp /opt/karoshi/.tempdata/INBOX.Sent $LOGINHOME/Mail/
[ ! -f $LOGINHOME/Mail/INBOX.Trash ] && cp /opt/karoshi/.tempdata/INBOX.Trash $LOGINHOME/Mail/
[ ! -f $LOGINHOME/.mailboxlist ] && cp /opt/karoshi/.tempdata/.mailboxlist $LOGINHOME/
chmod 0700 -R $LOGINHOME
chown -R $LOGINNAME $LOGINHOME
fi
#Set permissions on the users mail folder
if [ -f /var/spool/mail/$LOGINNAME ]
then
echo $MAILMSG"<br>"
chown $LOGINNAME /var/spool/mail/$LOGINNAME
fi
echo '<br>'
fi
fi
let COUNTER=$COUNTER+1
done

rm -f /opt/karoshi/.tempdata/master.ldif
rm -f /opt/karoshi/.tempdata/userlist.$$

}

function this_server_ldap {
############################
#Configure this server to use LDAP for authentication
############################
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/nsswitch.conf /etc/
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/pam.d/* /etc/pam.d/
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/configfiles/etc_ldap.conf /etc/ldap.conf

touch /etc/ldap.secret
chmod 0600 /etc/ldap.secret
echo $LDAPPASS > /etc/ldap.secret
}

########################
#Run functions
########################
function run_functions {
configure_ldap
add_default_groups
#do_groupmaps
this_server_ldap
create_users
#Set lockout
pdbedit -P "bad lockout attempt" -C 10 1>/dev/null 2>> /opt/karoshi/serversetup/install_log
pdbedit -P "lockout duration" -C 3 1>/dev/null 2>> /opt/karoshi/serversetup/install_log
}
run_functions

#Delete tempfiles
rm -f /etc/password_import
rm -f /etc/samba/smbpassword_import
rm -f /opt/karoshi/.tempdata/ldapstatus
#Set karoshi user password for ldap
echo -e "$LDAPPASS""\n""$LDAPPASS" | smbldap-passwd karoshi 1>/dev/null
#Delete ldif files
rm -f -R /opt/karoshi/.tempdata/ldap
echo ldapenabled > /opt/karoshi/serversetup/variables/ldapstatus

###########################
#Open shorewall ports
###########################
RESTART_SHOREWALL=no
MODCHECK=`grep -c -w \#ldap_server_rule /etc/shorewall/rules`
if [ $MODCHECK = 0 ]
then
RESTART_SHOREWALL=yes
echo ''$SHOREWALLMSG' - 389 tcp/udp<br><br>'
LINENUM=`grep -n 'LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE' /etc/shorewall/rules | cut -d: -f1`
sed -i $LINENUM'c'\ACCEPT'	'net'	'fw'	'tcp'	'389'	'-'#'ldap_server_rule /etc/shorewall/rules
echo ACCEPT'	'net'	'fw'	'udp'	'389'	'-'#' >> /etc/shorewall/rules
echo '#'LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE >> /etc/shorewall/rules
fi


##########################################
#Make sure that samba is running
##########################################
if [ `ps -e | grep -c -w smbd` = 0 ] || [ `ps -e | grep -c -w nmbd` = 0 ]
then
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/samba_start 2>> /opt/karoshi/serversetup/install_log
fi
exit
