#!/bin/bash
#clientmanagement
#Copyright (C) 2006  Paul Sharrad
#Copyright (C) 2006  The karoshi Team
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata
[ -e /opt/karoshi/serversetup/variables/language ] || /opt/karoshi/serversetup/changelanguage
[ -e /opt/karoshi/serversetup/variables/distro ] || /opt/karoshi/serversetup/changedistro

source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/language/$LANGCHOICE/all/clientmanagement
Xdialog --wrap --title "$TITLE" --clear \
        --icon $ICON --rc-file $RCFILE --yesno "$CONFRIMUPDATEMIRROR" 16 50

case $? in
  0)
   UPDATECHOICE=y;;
  1)
   UPDATECHOICE=n;;
  255)
   UPDATECHOICE=n;;
esac
if [ $UPDATECHOICE = y ]
then
#konsole --nomenubar --notabbar --vt_sz 120x15 --schema=BlackOnWhite.schema -e /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/updatemirrror
xterm -geometry 120x15 -bg white -fg black -e /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/updatemirrror
fi