#!/bin/bash
#rejoin_domain
#Copyright (C) 2006  Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#aloughlan@karoshi.org.uk
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata

[ -e /opt/karoshi/serversetup/variables/language ] || /opt/karoshi/serversetup/changelanguage
[ -e /opt/karoshi/serversetup/variables/distro ] || /opt/karoshi/serversetup/changedistro

source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/xdialog
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/language/$LANGCHOICE/all/rejoin_domain

######################
#Get root samba password function
######################
function getrootsambapassword {

ROOTPASSWORD=`Xdialog --title "$TITLE" --clear \
       $WIZARD --wrap --icon $ICON --rc-file $RCFILE --password --inputbox "$ERRORMESSAGE $SAMBAPASSWORD" 16 50 2>&1`

retval=$?

case $retval in
  0)
    ;;
  1)
    exit 101;;
  3)
    exit;;
  255)
    exit 101;;
esac
}
########################
#Join samba domain function
########################
function joinsambadomain {
net rpc join -S xen -U root%$ROOTPASSWORD 2>>/opt/karoshi/serversetup/install_log
JOINDOMAINSTATUS=`echo $?`
}
########################
#Join samba domain and check for errors
########################

getrootsambapassword
joinsambadomain
while [ $JOINDOMAINSTATUS != 0 ]
do
ERRORMESSAGE="$ERRORMSG1 \n\n"
getrootsambapassword
joinsambadomain
done

Xdialog --icon $ICON --rc-file $RCFILE --title "$TITLE" \
--msgbox "$TITLE\n\n$COMPLETEDMSG" 16 50
case $ in
0)
	exit;;
255)
	exit;;
esac
exit
