#!/bin/bash
#Used for showing servername and tcpip address in XFCE4 panel via xfce4-genmon-plugin

#Get servername
if [ -f /etc/hostname-fqdn ]
then
	SERVERNAME=$(hostname-fqdn)
	#Reset genmon for karoshi_user
	#Change update time on genmon
	if [ $(grep -c 30000 /opt/karoshi/karoshi_user/.config/xfce4/panel/genmon-3.rc) -gt 0 ]
	then
		sed -i 's/UpdatePeriod=30000/UpdatePeriod=36000000/g' /opt/karoshi/karoshi_user/.config/xfce4/panel/genmon-3.rc
		#Restart panel
		xfce4-panel -r & 
	fi
else
	SERVERNAME="$HOSTNAME"
	[ "$SERVERNAME" = ubuntu ] && SERVERNAME="Karoshi Server"
fi

TCPIP=$(grep "$SERVERNAME." /etc/hosts | cut -f1)
if [ -z "$TCPIP" ]
then
	TCPIP=$(grep address /etc/network/interfaces | tr -cd 0-9.)
fi


if [ -z "$TCPIP" ]
then
	
	echo "$SERVERNAME"
else
	echo "$SERVERNAME" - "$TCPIP"
fi
exit
