#!/bin/bash
#Start bind on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
	#Start on boot
	/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status bind9 on 1>/dev/null 2>/dev/null
else
	chkconfig -f bind9 on 1>/dev/null 2>/dev/null
fi

