#!/bin/bash
#Start dansguardian on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status dansguardian on 1>/dev/null 2>/dev/null
else
chkconfig -f dansguardian on 1>/dev/null 2>/dev/null
fi

