#!/bin/bash
#Start clamav-daemon on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
	/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status clamav-freshclam on 1>/dev/null 2>/dev/null
else
	chkconfig -f clamav-freshclam on 1>/dev/null 2>/dev/null
fi

