#!/bin/bash
#Start proftp on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status proftpd on 1>/dev/null 2>/dev/null
else
chkconfig -f proftpd on 1>/dev/null 2>/dev/null
fi
