#!/bin/bash
#Start mon on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status freeradius on 1>/dev/null 2>/dev/null
else
chkconfig -f freeradius on 1>/dev/null 2>/dev/null
fi

