#!/bin/bash
#Start squid-deb-proxy on boot

if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status squid-deb-proxy on 1>/dev/null 2>/dev/null
else
chkconfig -f squid-deb-proxy on 1>/dev/null 2>/dev/null
fi

