#!/bin/bash
#apache2config
[ -d /etc/ssl/apache ] || mkdir /etc/ssl/apache
cd /etc/ssl/apache
rm -f server.crt
rm -f server.key
if [ -f /opt/karoshi/serversetup/variables/ssldata ]
then
#file is present
COUNTRY=`sed -n 1,1p /opt/karoshi/serversetup/variables/ssldata`
STATE=`sed -n 2,2p /opt/karoshi/serversetup/variables/ssldata`
CITY=`sed -n 3,3p /opt/karoshi/serversetup/variables/ssldata`
NAME=`sed -n 4,4p /opt/karoshi/serversetup/variables/ssldata`
LOCALNAME=`sed -n 5,5p /opt/karoshi/serversetup/variables/ssldata`
SERVERNAME=`sed -n 6,6p /opt/karoshi/serversetup/variables/ssldata`
EMAILADDRESS=`sed -n 7,7p /opt/karoshi/serversetup/variables/ssldata`   

echo -e "$COUNTRY\n$STATE\n$CITY\n$NAME\n$LOCALNAME\n$SERVERNAME\n$EMAILADDRESS\n"

echo -e ""$COUNTRY"\n"$STATE"\n"$CITY"\n"$NAME"\n"$LOCALNAME"\n"$SERVERNAME"\n"$EMAILADDRESS"\n" | openssl req -new -x509 -days 730 -nodes -out server.crt -keyout server.key

chmod 0600 /etc/ssl/apache/server.crt
chmod 0600 /etc/ssl/apache/server.key
fi
/etc/init.d/httpd reload
