#!/bin/bash
#softwareinstall
echo installing quota >> /opt/karoshi/serversetup/install_log

echo apt-get install -y quota 2'>>'/opt/karoshi/serversetup/install_log > $HOME/.tempdata/installsoftware

chmod 0700 $HOME/.tempdata/installsoftware

xterm -geometry 100x20 -bg white -fg black -e $HOME/.tempdata/installsoftware
rm -f $HOME/.tempdata/installsoftware
