#!/bin/bash
#update
[ -d /var/www/html/mirrors/ ] || mkdir /var/www/html/mirrors/
chmod 0755 /var/www/html/mirrors/
#make sure tha apache is running
APACHESTATUS=`ps -e | grep -c -w httpd`
if [ $APACHESTATUS = 0 ]
then
service httpd start
fi
chkconfig httpd on
#Sync mirror
rsync -avr distro.ibiblio.org::distros/texstar/ /var/www/html/mirrors/
