#!/bin/bash
#changepassword
if ! test -f /var/www/cgi-bin/changepassword.cgi
then
cd /opt/karoshi/serversetup/colossus/changepassword
./configure --enable-cgidir=/var/www/cgi-bin --enable-smbpasswd=/etc/samba/smbpasswd --disable-squidpasswd --enable-logo=logos/logo.png
make
make install
fi
