# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1367937817);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "edsintegration%40mozilla.com:0.5,messagingmenu%40mozilla.com:1.3.1,globalmenu%40ubuntu.com:3.6.4,%7Ba62ef8ec-5fdc-40c2-873c-223b8a6925cc%7D:0.18,calendar-timezones%40mozilla.org:1.2011n,%7Be2fda1a4-762b-4020-b5ad-a41df1933103%7D:1.9,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.3");
user_pref("extensions.installCache", "[{\"name\":\"app-system-local\",\"addons\":{\"{e2fda1a4-762b-4020-b5ad-a41df1933103}\":{\"descriptor\":\"/usr/lib/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/{e2fda1a4-762b-4020-b5ad-a41df1933103}\",\"mtime\":1361955749000}}},{\"name\":\"app-system-share\",\"addons\":{\"{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\":{\"descriptor\":\"/usr/share/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/{a62ef8ec-5fdc-40c2-873c-223b8a6925cc}\",\"mtime\":1361955749000},\"calendar-timezones@mozilla.org\":{\"descriptor\":\"/usr/share/mozilla/extensions/{3550f703-e582-4d05-9a08-453d09bdfdc6}/calendar-timezones@mozilla.org\",\"mtime\":1361955749000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1361955467000},\"edsintegration@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/edsintegration@mozilla.com.xpi\",\"mtime\":1361443608000},\"messagingmenu@mozilla.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/messagingmenu@mozilla.com.xpi\",\"mtime\":1361443607000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/thunderbird/extensions/globalmenu@ubuntu.com\",\"mtime\":1361955468000}}}]");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.update.enabled", false);
user_pref("ldap_2.servers.eds.description", "EDS Address Book Bootstrapper");
user_pref("ldap_2.servers.eds.dirType", 3);
user_pref("ldap_2.servers.eds.filename", "eds.mab");
user_pref("ldap_2.servers.eds.position", 1);
user_pref("ldap_2.servers.eds.uri", "moz-abedsdirectory://");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.account.lastKey", 2);
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.localfoldersserver", "server1");
user_pref("mail.append_preconfig_smtpservers.version", 2);
user_pref("mail.attachment.store.version", 1);
user_pref("mail.folder.views.version", 1);
user_pref("mail.openMessageBehavior.version", 1);
user_pref("mail.preferences.advanced.selectedTabIndex", 0);
user_pref("mail.rights.version", 1);
user_pref("mail.spam.version", 1);
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.ui-rdf.version", 5);
user_pref("mail.shell.checkDefaultClient", false);
user_pref("mailnews.database.global.datastore.id", "d1bc50be-8a06-486d-8790-5ec7bb2b62e");
user_pref("mailnews.quotingPrefs.version", 1);
user_pref("mailnews.start_page.enabled", false);
user_pref("mailnews.tags.version", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("toolkit.telemetry.prompted", true);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.36", "");
