#!/bin/bash
#setupkaroshidesktop
#Copyright (C) 2004  Paul Sharrad
#
#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata
[ -e /opt/karoshi/serversetup/variables/language ] || /opt/karoshi/serversetup/changelanguage

source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/language/$LANGCHOICE/pdc/setupkaroshidesktop
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/pdc/software
source /opt/karoshi/server_network/domain_information/domain_name

#########################
#Add log entry
#########################
touch /opt/karoshi/serversetup/setuplog
if [ `grep -c "$TITLE" /opt/karoshi/serversetup/setuplog` = 0 ]
then
echo setupkaroshidesktop:$TITLE:/opt/karoshi/serversetup/pdc/scripts/setupkaroshidesktop >> /opt/karoshi/serversetup/setuplog
chmod 0600 /opt/karoshi/serversetup/setuplog
fi
echo `date`: '##############'setupkaroshidesktop'##############' >> /opt/karoshi/serversetup/install_log
###########################
#Detect desktop type
###########################

#Using kde
DESKTOP_TYPE=kde

if [ `ps -e | grep -c gnome-session` -gt 0 ]
then
#Using Gnome
DESKTOP_TYPE=gnome
fi

if [ `ps -e | grep -c xfce4` -gt 0 ]
then
#Using Thunar
DESKTOP_TYPE=xfce4
fi

######################
#make sure that kdesu uses su
######################
if [ $DESKTOP_TYPE = kde ]
then
KDESUCHECK=`grep -c super-user-command'='su /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals`
if [ $KDESUCHECK = 0 ]
then
echo '['super-user-command']' >> /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals
echo super-user-command'='su >> /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals
fi
fi

###########################
#Stop the karoshi user from logging in by default
###########################
echo `date`: "Stopping auto login for the karoshi user" >> /opt/karoshi/serversetup/install_log
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/default_login
[ -d /opt/karoshi/karoshimanagement ] || mkdir /opt/karoshi/karoshimanagement

#####################
#Copy in serversetup
#####################
echo /opt/karoshi/serversetup/pdc/scripts/setuppdc > /opt/karoshi/karoshimanagement/karoshisetup
chmod 0700 /opt/karoshi/karoshimanagement/karoshisetup

if [ $DESKTOP_TYPE = kde ]
then
echo konqueror --profile filemanagement /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

if [ $DESKTOP_TYPE = gnome ]
then
echo nautilus /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

if [ $DESKTOP_TYPE = xfce4 ]
then
echo thunar /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

##########################
#Stop karoshi setup from running on logon
##########################
echo `date`: "Stopping karoshi setup from running at logon" >> /opt/karoshi/serversetup/install_log
[ -f /opt/karoshi/karoshi_user/.config/autostart/karoshi_setup.desktop ] && rm -f /opt/karoshi/karoshi_user/.config/autostart/karoshi_setup.desktop
#Schedule disk_usage
echo 0 1 "*" "*" 6 /opt/karoshi/serversetup/all/\"useful scripts\"/disk_usage > /opt/karoshi/cronjobs/jobs/disk_usage_report.cron
/opt/karoshi/serversetup/all/"useful scripts"/refreshcronjobs

##########################
#Copy in icons
##########################
echo `date`: "Copying in icons" >> /opt/karoshi/serversetup/install_log
cp -f /opt/karoshi/serversetup/all/links/adminfilemanager.desktop /opt/karoshi/karoshi_user/Desktop/
cp -f /opt/karoshi/serversetup/all/links/webmanagement.desktop /opt/karoshi/karoshi_user/Desktop/
chmod 0700 /opt/karoshi/karoshi_user/Desktop/adminfilemanager.desktop

#######################
#Stop password aging
#######################
chage -M 99999 root
chage -M 99999 karoshi
##########################
#Set Karoshi User Permissions
##########################
echo `date`: "Setting karoshi user permissions" >> /opt/karoshi/serversetup/install_log
chown -c -R karoshi /opt/karoshi/karoshi_user

chmod 0700 /opt/karoshi/karoshimanagement/admin_file_manager

mkdir /opt/karoshi/"useful scripts" 2>/dev/null
chmod 0700 /opt/karoshi/"useful scripts"
cp -f -R /opt/karoshi/serversetup/all/"useful scripts"/* /opt/karoshi/"useful scripts"/
cp -f /opt/karoshi/serversetup/pdc/"useful scripts"/* /opt/karoshi/"useful scripts"
cp -f /opt/karoshi/serversetup/pdc/"useful scripts"/.alphabet /opt/karoshi/"useful scripts"/
chmod -R 0700 /opt/karoshi/"useful scripts"

sed -i 's/CHANGETHISDOMAINNAME/'$SAMBADOMAINlcase'/g' /opt/karoshi/"useful scripts"/ldap_add_machine

#Import SSL root certificate into firefox
echo `date`: "Importing ssl root certificate into firefox" >> /opt/karoshi/serversetup/install_log
FIREFOXPROFILE=`ls /opt/karoshi/karoshi_user/.mozilla/firefox | grep .default`
#su karoshi -c 'certutil -A -n "Karoshi Web Management" -addstore root -t "CTu,CTu,CTu" -i /var/lib/samba/netlogon/domain_information/cacert.pem -d /opt/karoshi/karoshi_user/.mozilla/firefox/'$FIREFOXPROFILE''

certutil -A -n "Karoshi Web Management" -addstore root -t "CTu,CTu,CTu" -i /var/lib/samba/netlogon/domain_information/cacert.pem -d /opt/karoshi/karoshi_user/.mozilla/firefox/$FIREFOXPROFILE

#Modify web management to point at the domain path instead of 127.0.0.1
echo `date`: "MOdifying the web management desktop icon to point at the domain path" >> /opt/karoshi/serversetup/install_log
sed -i "s/127.0.0.1/manage.$REALM/g" /opt/karoshi/karoshi_user/Desktop/webmanagement.desktop

#Modify defaullt home page to point at the web management
echo `date`: "Modifying firefox default home page to point at the web management" >> /opt/karoshi/serversetup/install_log
sed -i "s/http:\/\/www.linuxschools.com/https:\/\/manage.$REALM:50001/g" /opt/karoshi/karoshi_user/.mozilla/firefox/usihywjy.default/prefs.js

###########################
#Display completed message
############################
yad --title "$TITLE" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --width 400 --height 100 --timeout=10 --text="$FINALMSG\n\n$FINALMSG2" --no-buttons 2>/dev/null
exit
