#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
source /opt/karoshi/serversetup/variables/choice
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/variables/language

INSTALL_TYPE=`sed -n 1,1p /opt/karoshi/server_network/install_type`

TEXTDOMAIN=karoshi-server
locale 1>/dev/null

#baseinstallpdc
BASEINSTALLPATH=/opt/karoshi/serversetup/pdc/scripts
BASEINSTALLPATH2=/opt/karoshi/serversetup/web_controls
BASEINSTALLPATH3=/opt/karoshi/serversetup/all/scripts
KAROSHILOG=/opt/karoshi/serversetup/install_log

#Set timezone in php.ini
[ -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/set_php_timezone ] && /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/set_php_timezone

function checkstatus {
EXITSTATUS=`echo $?`
if [ $EXITSTATUS = 101 ]
then
	yad --title $"Main Server Setup" $VERSION --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --width 400 --text=''$"The standard setup has not completed correctly."'' --timeout=3 --timeout-indicator=bottom --no-buttons 2>/dev/null
	exit
fi
if [ $EXITSTATUS = 103 ]
then
	exit 103
fi
}

function do_setup {
	if [ "$INSTALL_TYPE" = adcrestore ] || [ "$INSTALL_TYPE" = archiverestore ]
	then
		echo "1"
		echo '# '$"Restoring essential data"''
		$BASEINSTALLPATH/restore_data 1>>$KAROSHILOG 2>>$KAROSHILOG
		[ ! -f /opt/karoshi/server_network/install_type_pre_restore ] && mv /opt/karoshi/server_network/install_type /opt/karoshi/server_network/install_type_pre_restore
		echo "$INSTALL_TYPE" > /opt/karoshi/server_network/install_type
		echo "2"
	else
		echo "1"
	fi
	echo '# '$"Checking Network"''
	$BASEINSTALLPATH3/checknetwork pdc 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "12"
	echo '# '$"Setup"' '$"Shorewall"''
	$BASEINSTALLPATH/setupshorewall 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "24"
	echo '# '$"Setup"' '$"NTP"''
	$BASEINSTALLPATH/setupntp 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "36"
	echo '# '$"Setup"' '$"Samba"''
	$BASEINSTALLPATH/setupsamba 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "48"
	echo '# '$"Setup"' '$"Bind"''
	$BASEINSTALLPATH/convert_dns_to_bind 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "60"
	echo '# '$"Setup"' '$"Root CA for SSL"''
	$BASEINSTALLPATH/setup_root-ca 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "72"
	echo '# '$"Setup"' '$"Web Management"''
	$BASEINSTALLPATH2/setup_web_controls interactive 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "84"
	echo '# '$"Setup"' '$"Monitorix"''
	/opt/karoshi/serversetup/modules/monitoring/monitorix/setupmonitorix 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "96"
	echo '# '$"Setup"' '$"Monitorix Web Management"''
	/opt/karoshi/serversetup/web_controls/scripts/monitorixwebmanagement 1>>$KAROSHILOG 2>>$KAROSHILOG
	checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
	echo "100"
	echo '# '$"Setup"' '$"Karoshi Desktop"''
	$BASEINSTALLPATH/setupkaroshidesktop 1>>$KAROSHILOG 2>>$KAROSHILOG
	#Kill status bar
	killall yad
}

do_setup | yad --title $"Main Server Setup" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png"  --geometry=400x100+0+10 --no-buttons --text $"Main Server Setup""\n\n\n$STATUS" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --progress 2>/dev/null

#Setup uptime data for the server
/opt/karoshi/serversetup/all/scripts/setup_uptime

#Setup minidlna if this is a home server.
if [ $INSTALL_TYPE = home ]
then
	/opt/karoshi/serversetup/modules/minidlna/setupminidlna
fi
#Add in thunderbird support
/opt/karoshi/serversetup/pdc/windowsclient/thunderbird/configure_thunderbird_windows

#Create initial disk usage report
/opt/karoshi/serversetup/all/"useful scripts"/disk_usage

#Do businesses want google safesearch?
#if [ "$INSTALL_TYPE" = education ] || [ "$INSTALL_TYPE" = joindomain_education ] || [ "$INSTALL_TYPE" = home ]
#then
/opt/karoshi/serversetup/pdc/"useful scripts"/googlesafesearch add
#fi
exit



