#!/bin/bash

#Copyright (C) 2012 Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http:/www.karoshi.org.uk

LOG_DATE=`date +%F`

#Delete warning file
/opt/karoshi/serversetup/web_controls/scripts/web_management_warn delete reboot


function add_warning {
echo `date`: check_reboot - $SERVER: reboot required after an upgrade. >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
/opt/karoshi/serversetup/web_controls/scripts/web_management_warn add reboot_$SERVER /cgi-bin/admin/shutdown_fm.cgi "$ERRORALERT" 3
}

#Check servers for reboot
for SERVERS in /opt/karoshi/server_network/servers/*
do
SERVER=`basename $SERVERS`
if [ $SERVER = $HOSTNAME ]
then
[ -f /var/run/reboot-required ] && add_warning
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
[ -f /var/run/reboot-required ] && exit 105
'
[ `echo $?` = 105 ] && add_warning
fi
done

#Check federated servers for reboot


#Show list of federated servers
if [ -d /opt/karoshi/server_network/federated_ldap_servers/ ]
then
if [ `ls -1 /opt/karoshi/server_network/federated_ldap_servers/ | wc -l` -gt 0 ]
then
for FEDERATED_SERVERS in /opt/karoshi/server_network/federated_ldap_servers/*
do
FEDERATED_SERVER=`basename $FEDERATED_SERVERS`
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
[ -f /var/run/reboot-required ] && exit 105
'
[ `echo $?` = 105 ] && add_warning
done
fi
fi

#Check federated slave servers
if [ -d /opt/karoshi/server_network/federated_ldap_servers/ ]
then
if [ `ls -1 /opt/karoshi/server_network/federated_ldap_servers/ | wc -l` -gt 0 ]
then
for FEDERATED_MASTERS in /opt/karoshi/server_network/federated_ldap_servers/*
do
FEDERATED_MASTER=`basename $FEDERATED_MASTERS`
for SERVERS in /opt/karoshi/server_network/federated_ldap_servers/$FEDERATED_MASTER/servers/*
do
SERVER=`basename $SERVERS`
echo server is $SERVER master is $FEDERATED_MASTER
if [ $SERVER = $FEDERATED_MASTER ]
then
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVER '
[ -f /var/run/reboot-required ] && exit 105
'
[ `echo $?` = 105 ] && add_warning
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $FEDERATED_MASTER '
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 '$SERVER' '\''
[ -f /var/run/reboot-required ] && exit 105
'\''
[ `echo $?` = 105 ] && exit 105
'
[ `echo $?` = 105 ] && add_warning
fi
done
done
fi
fi

exit

