#!/bin/bash
#Configure /opt/karoshi/serversetup for git.

[ ! -d /opt/karoshi/.git ] && mkdir -p /opt/karoshi/.git

echo '[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	fetch = +refs/heads/*:refs/remotes/origin/*
	url = https://github.com/the-linux-schools-project/karoshi-server.git
[branch "master"]
	remote = origin
	merge = refs/heads/master
[alias]
	sync = gitsync
[branch "cups-testing"]
	remote = origin
	merge = refs/heads/cups-testing
' > /opt/karoshi/.git/config

choice=n
echo -e "\nYou will need to enter in a name and E-Mail address for pushing to github."
while [ $choice = n ]
do
	echo -e "\nEnter your name\n"
	read name
	echo -e "\nEnter your email address\n"
	read email
	echo -e "\nName: $name\nE-Mail: $email\n\nAdd these details correct?(y/n)\n"
	read choice

	if [ $choice = y ]
	then
		echo '[user]
	name = Change Me
	email = changeme@changethis.com
[push]
	default = simple
' > /root/.gitconfig

	git config --global user.name "$name"
    	git config --global user.email $email
	fi
done

cp -f /opt/karoshi/serversetup/all/scripts/gitsync /usr/sbin/

cd /opt/karoshi
git init
