#!/bin/bash
#setupsamba
#Copyright (C) 2004  Paul Sharrad
#Copyright (C) 2005  The karoshi Team
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

[ -e /opt/karoshi/serversetup/variables/language ] || /opt/karoshi/serversetup/changelanguage
[ -e /opt/karoshi/serversetup/variables/distro ] || /opt/karoshi/serversetup/changedistro

source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/xdialog
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/variables/years
source /opt/karoshi/serversetup/variables/tcpip
source /opt/karoshi/serversetup/language/$LANGCHOICE/orac/setupsamba
source /opt/karoshi/serversetup/language/$LANGCHOICE/softwareinstall
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/orac/software
SAMBADOMAINCAPS=`echo $SAMBADOMAIN | tr 'a-z' 'A-Z'`

#######################
#Setup ldap
######################
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/xen/configfiles/nsswitch.conf /etc/
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/xen/configfiles/system-auth /etc/pam.d/
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/configfiles/etc_ldap.conf /etc/ldap.conf
#Modify ldap.conf with correct ip for xen
sed -i "s/127.0.0.1/$XEN/g" /etc/ldap.conf
echo ldapenabled > /opt/karoshi/serversetup/variables/ldapstatus

service ypbind stop
echo LDAP covenversion completed
