#!/bin/bash
source /opt/karoshi/server_network/domain_information/domain_name

#Get timezone
TIMEZONE=`cat /etc/timezone`

#Delete any current thunderbird settings
[ -d /var/lib/samba/netlogon/windows_settings/thunderbird ] && rm -f -R /var/lib/samba/netlogon/windows_settings/thunderbird
mkdir -p /var/lib/samba/netlogon/windows_settings/thunderbird
#Copy thunderbird profile to netlogon
cp -f -R /opt/karoshi/serversetup/pdc/windowsclient/thunderbird/profile /var/lib/samba/netlogon/windows_settings/thunderbird/
#Copy thunderbird.kix to netlogon
cp -f /opt/karoshi/serversetup/pdc/windowsclient/thunderbird/thunderbird.kix /var/lib/samba/netlogon/windows_settings/thunderbird/

#Add thunderbird.kix to logonform.kix
if [ `grep -c thunderbird.kix /var/lib/samba/netlogon/logonform.kix` = 0 ]
then
	echo 'Call "$lserver\netlogon\windows_settings/thunderbird/thunderbird.kix"' >> /var/lib/samba/netlogon/logonform.kix
fi

#Delete an existing cert8.db
[ -f /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/cert8.db ] && rm -f /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/cert8.db

#Create cert8.db
certutil -A -n "Karoshi CA" -addstore root -t "CTu,CTu,CTu" -i /var/lib/samba/netlogon/domain_information/cacert.pem -d /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/
chmod 0644 /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/cert8.db
rm -f /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/secmod.db
rm -f /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/key3.db

####################
#Setup sogo plugins with the correct information
####################

#Copy integrator to tmp folder
[ -d /tmp/sogo_integrator ] && rm -f -R /tmp/sogo_integrator
[ -f "/tmp/sogo-integrator@inverse.ca.xpi" ] && rm -f "/tmp/sogo-integrator@inverse.ca.xpi"
mkdir -p /tmp/sogo_integrator
cp -f /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/extensions/sogo-integrator@inverse.ca.xpi /tmp/sogo_integrator

#inflate integrator
cd /tmp/sogo_integrator
unzip "sogo-integrator@inverse.ca.xpi"

#Delete out the xpi 
rm -f "/tmp/sogo_integrator/sogo-integrator@inverse.ca.xpi"

#Set correct path in extensions.rd
sed -i 's/sogo-demo.inverse.ca/mail.'$REALM'\/SOGo/g' /tmp/sogo_integrator/chrome/content/extensions.rdf

#Create sogo-integrator site.js

echo 'pref("app.update.auto", false);
pref("app.update.enabled", false);
pref("autoupdate.enabled", false);
pref("extensions.update.auto", false);
pref("extensions.update.enabled", false);
pref("mail.imap.mime_parts_on_demand_threshold", 300000);
pref("mail.inline_attachments", true);
pref("mail.mdn.report.not_in_to_cc", 0);
pref("mail.strictly_mime.parm_folding", 0);
pref("calendar.alarms.showmissed", false);
pref("calendar.caldav.sched.enabled", true);
pref("calendar.timezone.local", "/mozilla.org/20070129_1/'$TIMEZONE'");
pref("sogo-integrator.autocomplete.server.urlid", "directory");
' > /tmp/sogo_integrator/defaults/preferences/site.js

#Re-create the xpi
zip -r "/tmp/sogo-integrator@inverse.ca.xpi" *

#Copy the file back
cp -f "/tmp/sogo-integrator@inverse.ca.xpi" /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/extensions/

exit


#Copy connector to tmp folder
[ -d /tmp/sogo_connector ] && rm -f -R /tmp/sogo_connector
mkdir -p /tmp/sogo_connector
cp -f /var/lib/samba/netlogon/windows_settings/thunderbird/profile/Thunderbird/Profiles/gyjphq7q.default/extensions/sogo-connector@inverse.ca.xpi /tmp/sogo_connector



#Inflate connector
cd /tmp/sogo_connector
unzip "sogo-connector@inverse.ca.xpi"

