# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1317110767);
user_pref("app.update.lastUpdateTime.background-update-timer", 1206606326);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1317110887);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1206540070);
user_pref("app.update.lastUpdateTime.places-maintenance-timer", 1255698188);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1317111007);
user_pref("browser.EULA.3.accepted", true);
user_pref("browser.cache.disk.capacity", 5000);
user_pref("browser.cache.disk.smart_size.enabled", false);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.download.save_converter_index", 0);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.migration.version", 6);
user_pref("browser.places.createdSmartBookmarks", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.preferences.lastpanel", 1);
user_pref("browser.rights.3.shown", true);
user_pref("browser.search.selectedEngine", "Google");
user_pref("browser.search.update", false);
user_pref("browser.startup.homepage_override.buildID", "20120713224749");
user_pref("browser.startup.homepage_override.mstone", "14.0.1");
user_pref("browser.tabs.loadInBackground", false);
user_pref("browser.urlbar.autocomplete.enabled", false);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.adblockplus.checkedadblockinstalled", true);
user_pref("extensions.adblockplus.checkedtoolbar", true);
user_pref("extensions.adblockplus.frameobjects", false);
user_pref("extensions.adblockplus.showintoolbar", false);
user_pref("extensions.adblockplus.showsubscriptions", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 12);
user_pref("extensions.disabledObsolete", true);
user_pref("extensions.enabledAddons", "globalmenu@ubuntu.com:3.2.5,langpack-en-ZA@firefox.mozilla.org:14.0.1,langpack-en-GB@firefox.mozilla.org:14.0.1,ubufox@ubuntu.com:2.0.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:14.0.1");
user_pref("extensions.enabledItems", "ubufox@ubuntu.com:0.9rc2,langpack-en-GB@firefox-3.6.ubuntu.com:3.6,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.6.10");
user_pref("extensions.installCache", "[{\"name\":\"app-system-share\",\"addons\":{\"ubufox@ubuntu.com\":{\"descriptor\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"mtime\":1341671421000}}},{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/firefox/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1342550500000},\"langpack-en-GB@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"mtime\":1342227406000},\"langpack-en-ZA@firefox.mozilla.org\":{\"descriptor\":\"/usr/lib/firefox/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"mtime\":1342227406000},\"globalmenu@ubuntu.com\":{\"descriptor\":\"/usr/lib/firefox/extensions/globalmenu@ubuntu.com\",\"mtime\":1342550480000}}}]");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.update.enabled", false);
user_pref("extensions.update.notifyUser", false);
user_pref("flagfox.warn.tld", false);
user_pref("flagfox.warn.updates", false);
user_pref("gfx.blacklist.direct2d", 3);
user_pref("gfx.blacklist.layers.direct3d10", 3);
user_pref("gfx.blacklist.layers.direct3d10-1", 3);
user_pref("gfx.blacklist.layers.direct3d9", 3);
user_pref("gfx.blacklist.layers.opengl", 3);
user_pref("gfx.blacklist.webgl.angle", 3);
user_pref("gfx.blacklist.webgl.opengl", 3);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.websocket.enabled", false);
user_pref("places.history.expiration.transient_current_max_pages", 97062);
user_pref("plugin.disable_full_page_plugin_for_types", "application/msword");
user_pref("plugin.soname.list", "libXt.so.6:libXext.so.6");
user_pref("pref.downloads.disable_button.edit_actions", false);
user_pref("privacy.cpd.offlineApps", true);
user_pref("privacy.cpd.siteSettings", true);
user_pref("privacy.item.offlineApps", true);
user_pref("privacy.sanitize.didShutdownSanitize", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("privacy.sanitize.sanitizeOnShutdown", true);
user_pref("privacy.sanitize.timeSpan", 0);
user_pref("privacy.donottrackheader.enabled", true);
user_pref("security.OCSP.URL", "");
user_pref("security.OCSP.signingCA", "Builtin Object Token:IPS CLASE1 root");
user_pref("security.disable_button.openCertManager", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
user_pref("toolkit.startup.last_success", 1358416948);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1361008882);
user_pref("urlclassifier.tableversion.goog-black-url", "1.11201");
user_pref("urlclassifier.tableversion.goog-white-domain", "1.22");
user_pref("urlclassifier.tableversion.goog-white-url", "1.371");
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.103", "");
user_pref("xpinstall.whitelist.add.36", "");
