#!/bin/bash

LOCKFILE=/var/lock/check_Mailscanner.lock
MS_LOCKFILE=/var/lock/subsys/MailScanner.off

if [ -f $MS_LOCKFILE ]; then
  echo "MailScanner manually shut down (no $MS_LOCKFILE file)."
  echo "Not restarting."
  exit
fi

# the lockfile is not meant to be perfect, it's just in case the
# two makewhatis cron scripts get run close to each other to keep
# them from stepping on each other's toes.  The worst that will
# happen is that they will temporarily corrupt the database...
[ -f $LOCKFILE ] && exit 0
trap "rm -f $LOCKFILE" EXIT
touch $LOCKFILE
/usr/sbin/check_mailscanner -q # >/dev/null 2>&1
exit 0
