#!/bin/bash
#ntpinstall
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/orac/software
echo installing $NTP >> /opt/karoshi/serversetup/install_log
echo /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/sendreturn '|' '('urpmi --force $NTP 2'>>'/opt/karoshi/serversetup/install_log ';' killall sendreturn')'  > $HOME/.tempdata/installsoftware

echo apt-get install -y $NTP 2'>>'/opt/karoshi/serversetup/install_log > $HOME/.tempdata/installsoftware

chmod 0700 $HOME/.tempdata/installsoftware

xterm -geometry 100x20 -bg white -fg black -e $HOME/.tempdata/installsoftware
rm -f $HOME/.tempdata/installsoftware

