# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the browser is running,
 * the changes will be overwritten when the browser exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("browser.anchor_color", "#0000FF");
user_pref("browser.bookmarks.file", "g:\\favourites\\bookmarks");
user_pref("browser.display.background_color", "#C0C0C0");
user_pref("browser.display.use_system_colors", true);
user_pref("browser.download.defaultFolder", "G:");
user_pref("browser.download.dir", "G:");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.manager.retention", 1);
user_pref("browser.download.useDownloadDir", false);
user_pref("browser.formfill.enable", false);
user_pref("browser.history_expire_days", 20);
user_pref("browser.preferences.lastpanel", 3);
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.startup.homepage", "http://hal.internal/webwarning");
user_pref("browser.startup.homepage_override.mstone", "rv:1.7");
user_pref("browser.visited_color", "#800080");
user_pref("extensions.disabledObsolete", true);
user_pref("extensions.lastAppVersion", "0.9");
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.lifetimePolicy", 2);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.ftp", "hal.internal");
user_pref("network.proxy.ftp_port", 3128);
user_pref("network.proxy.gopher", "hal.internal");
user_pref("network.proxy.gopher_port", 3128);
user_pref("network.proxy.http", "hal.internal");
user_pref("network.proxy.http_port", 3128);
user_pref("network.proxy.no_proxies_on", "xen.internal , hal.internal , orac.internal , novac.internal , sal.internal , joshua.internal , skynet.internal , mcp.internal , colossus.internal , 192.168.0.2 , deep_thought.internal , xen , xen.internal , queeg500.internal , sentinal.internal , alwaysproblems.internal , aivas.internal , bishop.internal , bomb_number_20.internal , kryten.internal , giskard.internal , tranquillity.internal , ziggy.internal , zorac.internal , zero.internal , vincent.internal ");
user_pref("network.proxy.socks", "hal.internal");
user_pref("network.proxy.socks_port", 3128);
user_pref("network.proxy.ssl", "hal.internal");
user_pref("network.proxy.ssl_port", 3128);
user_pref("network.proxy.type", 0);
user_pref("security.OCSP.URL", "");
user_pref("security.OCSP.signingCA", "Builtin Object Token:Verisign Class 1 Public Primary OCSP Responder");
user_pref("security.warn_entering_secure", false);
user_pref("security.warn_leaving_secure", false);
user_pref("security.warn_submit_insecure", false);
user_pref("security.warn_viewing_mixed", false);
user_pref("signon.rememberSignons", false);
