#!/bin/bash
#Copyright (C) 2007  The karoshi Team
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit

SSHWARNMSG="SSH is not enabled for this server."

########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/banned_users_view2_cgi
then
echo `date`: banned_users_view2 - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/banned_users_view2_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/banned_users_view2.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $banned_users_view2_cgi'check' ]
then
echo `date`: banned_users_view2 - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/banned_users_view2_cgi
then
echo `date`: banned_users_view2 - No tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/banned_users_view2_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/banned_users_view2.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $banned_users_view2_cgi'check' ]
then
echo `date`: banned_users_view2 - Incorrect tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: banned_users_view2 - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
USERARRAY=( `echo $* | cut -s -d: -f4- | sed 's/:/ /g'` )
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: banned_users_view2 - Not called by banned_users_view2.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: banned_users_view2 - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: banned_users_view2 - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: banned_users_view2 - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ $USERARRAY'null' = null ]
then
echo `date`: banned_users_view2 - No users chosen by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

USERCOUNT=`echo ${#USERARRAY[@]}`
COUNTER=0
#Log event
while [ $COUNTER -lt $USERCOUNT ]
do
BANNEDUSER=`echo ${USERARRAY[$COUNTER]}`
echo `date`: banned_users_view2 - allowing $BANNEDUSER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
let COUNTER=$COUNTER+1
done

COUNTER=0
while [ $COUNTER -lt $USERCOUNT ]
do
#Allow user
BANNEDUSER=`echo ${USERARRAY[$COUNTER]}`
[ -f /opt/karoshi/logs/banned_user_account_durations/$BANNEDUSER ] && rm -f /opt/karoshi/logs/banned_user_account_durations/$BANNEDUSER
[ -f /opt/karoshi/logs/banned_user_permanent/$BANNEDUSER ] && rm -f /opt/karoshi/logs/banned_user_permanent/$BANNEDUSER
samba-tool allow $BANNEDUSER 1>/dev/null

#Federated ldap servers
if [ -d /opt/karoshi/server_network/federated_ldap_servers/ ]
then
if [ `ls -1 /opt/karoshi/server_network/federated_ldap_servers/ | wc -l` -gt 0 ]
then
for FEDERATED_LDAP_SERVER in /opt/karoshi/server_network/federated_ldap_servers/*
do
FEDERATED_LDAP_SERVER=`basename $FEDERATED_LDAP_SERVER`
ssh -x $FEDERATED_LDAP_SERVER '
samba-tool allow '$BANNEDUSER' 1>/dev/null
'
done
fi
fi

let COUNTER=$COUNTER+1
done
exit
