#!/bin/bash
#Copyright (C) 2011  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/dnsview_cgi
then
echo `date`: dnsview - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/dnsview_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/dnsview.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $dnsview_cgi'check' ]
then
echo `date`: dnsview - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: dnsview - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-+'`
if [ $DATA'null' = null ]
then
echo `date`: dnsview - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
SERVERNAME=`echo "$DATA" | cut -s -d: -f4`
SERVERTYPE=`echo "$DATA" | cut -s -d: -f5`
ACTION=`echo "$DATA" | cut -s -d: -f6`
NAME=`echo "$DATA" | cut -s -d: -f7`
DNSENTRY=`echo "$DATA" | cut -s -d: -f8`
DNSTYPE=`echo "$DATA" | cut -s -d: -f9`
MOBILE=`echo "$DATA" | cut -s -d: -f10`
########################
#Check data
########################

if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo `date`: dnsview - Not called by dnsview.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ -z "$REMOTE_USER" ]
then
echo `date`: dnsview - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ -z "$REMOTE_ADDR" ]
then
echo `date`: dnsview - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ -z "$SERVERNAME" ]
then
echo `date`: dnsview - Blank servername entry by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ -z "$SERVERTYPE" ]
then
echo `date`: dnsview - Blank servertype entry by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ -z "$ACTION" ]
then
echo `date`: dnsview - Blank action by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

echo `date`: dnsview - viewing /etc/hosts on $SERVERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

############################
#Language
############################
LANGCHOICE=englishuk
STYLESHEET=defaultstyle.css
TIMEOUT=300
NOTIMEOUT=127.0.0.1
[ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/system/dns ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/system/dns
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/all ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/all
MONITORSERVER=no
[ -f /opt/karoshi/server_network/monitoringserver ] && MONITORSERVER=yes
ICON1=/images/submenus/system/edit.png
ICON2=/images/submenus/system/delete.png
ICON3=/images/submenus/monitoring/custom_monitors.png


WIDTH1=100
WIDTH2=100
TABLECLASS=standard
if [ $MOBILE = yes ]
then
WIDTH1=50
WIDTH2=50
TABLECLASS=mobilestandard
EDITMSG=""
DELETEMSG=""
MONITORMSG=""
fi

LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
source /opt/karoshi/server_network/domain_information/domain_name

if [ $ACTION = view ]
then
if [ $SERVERNAME = $HOSTNAME ]
then

#List of entries that we dont want to be able to edit
DONTDISPLAY="_msdcs,_sites,_tcp,_udp,DomainDnsZones,ForestDnsZones"
DNSINFO=`samba-tool dns query 127.0.0.1 $REALM $REALM ALL -U Administrator --password $LDAPPASS`

#Create top of table
echo '<table class="'$TABLECLASS'" style="text-align: left;" border="0" cellpadding="2" cellspacing="2"><tbody>
<tr><td style="vertical-align: top; width: '$WIDTH1'px;"><b>'$DNSNAMEMSG'</b></td><td style="vertical-align: top; width: '$WIDTH2'px;"><b>Type</b></td><td><b>Entry</b></td><td><b>'$EDITMSG'</b></td><td><b>'$DELETEMSG'</b></td>'

[ $MONITORSERVER = yes ] && echo '<td><b>'$MONITORMSG'</b></td>'
echo '</tr>'


#Get dns entry names
for NAME in `echo -e "$DNSINFO" | grep Name= | cut -d= -f2 | cut -d, -f1`
do
if [ `echo $DONTDISPLAY | grep -c $NAME` = 0 ]
then
#Get data for name
DATA=`echo -e "$DNSINFO" | awk '/Name='$NAME'/ { getline;print}'`
DNSTYPE=`echo $DATA | cut -d: -f1`
DNSENTRY=`echo $DATA | cut -d: -f2 | cut -d" " -f2 | sed "s/\.$//g"`
#Add line to table
echo "<tr><td style=\"vertical-align: top;\">$NAME</td><td style=\"vertical-align: top;\">$DNSTYPE</td><td style=\"vertical-align: top;\">$DNSENTRY</td>
<td><form action=\"/cgi-bin/admin/dnsview.cgi\" method=\"post\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERNAME_$SERVERNAME"_"SERVERTYPE_$SERVERTYPE"_"ACTION_edit_NAME_$NAME"_"_DNSENTRY_$DNSENTRY"_"DNSTYPE_$DNSTYPE"_"\" type=\"image\" class=\"images\" src=\"$ICON1\" value=\"\"><span>$EDITMSG<br>$NAME<br>$DNSENTRY</span></a></form></td>
<td><form action=\"/cgi-bin/admin/dnsview.cgi\" method=\"post\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERNAME_$SERVERNAME"_"SERVERTYPE_$SERVERTYPE"_"ACTION_delete_NAME_$NAME"_"_DNSENTRY_$DNSENTRY"_"DNSTYPE_$DNSTYPE"_"\" type=\"image\" class=\"images\" src=\"$ICON2\" value=\"\"><span>$DELETEMSG<br>$NAME<br>$DNSENTRY</span></a></form></td>"

if [ $MONITORSERVER = yes ]
then
echo "<td><form action=\"/cgi-bin/admin/monitors_add_fm.cgi\" method=\"post\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_NAME_$DNSDATA2"_"TCPIP_$DNSENTRY"_"\" type=\"image\" class=\"images\" src=\"$ICON3\" value=\"\"><span>$MONITORMSG<br>$NAME<br>$DNSENTRY</span></a></form></td>"
fi
echo "</tr>"
fi
done

#End table
echo "</tbody></table>"

else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVERNAME '
MONITORSERVER=no
[ -f /opt/karoshi/server_network/monitoringserver ] && MONITORSERVER=yes

LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
source /opt/karoshi/server_network/domain_information/domain_name

DNSINFO=`samba-tool dns query 127.0.0.1 $REALM $REALM ALL -U Administrator --password $LDAPPASS`

#Create top of table
echo "<table class=\"'$TABLECLASS'\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"vertical-align: top; width: '$WIDTH1'px;\"><b>'$DNSNAMEMSG'</b></td><td style=\"vertical-align: top; width: '$WIDTH2'px;\"><b>Type</b></td><td><b>Entry</b></td><td><b>'$EDITMSG'</b></td><td><b>'$DELETEMSG'</b></td>"

[ $MONITORSERVER = yes ] && echo "<td><b>'$MONITORMSG'</b></td>"
echo "</tr>"

#Get dns entry names
for NAME in `echo -e "$DNSINFO" | grep Name= | cut -d= -f2 | cut -d, -f1`
do
if [ `echo $DONTDISPLAY | grep -c $NAME` = 0 ]
then
#Get data for name
DATA=`echo -e "$DNSINFO" | awk "/Name=$NAME/ { getline;print}"`
DNSTYPE=`echo $DATA | cut -d: -f1`
DNSENTRY=`echo $DATA | cut -d: -f2 | cut -d" " -f2 | sed "s/\.$//g"`
#Add line to table
echo "<tr><td style=\"vertical-align: top;\">$NAME</td><td style=\"vertical-align: top;\">$DNSTYPE</td><td style=\"vertical-align: top;\">$DNSENTRY</td>
<td><form action=\"/cgi-bin/admin/dnsview.cgi\" method=\"post\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERNAME_$SERVERNAME"_"SERVERTYPE_$SERVERTYPE"_"ACTION_edit_NAME_$NAME"_"_DNSENTRY_$DNSENTRY"_"DNSTYPE_$DNSTYPE"_"\" type=\"image\" class=\"images\" src=\"'$ICON1'\" value=\"\"><span>'$EDITMSG'<br>$NAME<br>$DNSENTRY</span></a></form></td>
<td><form action=\"/cgi-bin/admin/dnsview.cgi\" method=\"post\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERNAME_$SERVERNAME"_"SERVERTYPE_$SERVERTYPE"_"ACTION_delete_NAME_$NAME"_"_DNSENTRY_$DNSENTRY"_"DNSTYPE_$DNSTYPE"_"\" type=\"image\" class=\"images\" src=\"'$ICON2'\" value=\"\"><span>'$DELETEMSG'<br>$NAME<br>$DNSENTRY</span></a></form></td>"

if [ $MONITORSERVER = yes ]
then
echo "<td><form action=\"/cgi-bin/admin/monitors_add_fm.cgi\" method=\"post\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_NAME_$DNSDATA2"_"TCPIP_$DNSENTRY"_"\" type=\"image\" class=\"images\" src=\"'$ICON3'\" value=\"\"><span>'$MONITORMSG'<br>$NAME<br>$DNSENTRY</span></a></form></td>"
fi
echo "</tr>"
fi
done

#End table
echo "</tbody></table>"
'
fi
fi

#########################
#Delete entry
#########################
if [ $ACTION = delete ]
then
if [ $SERVERNAME = $HOSTNAME ]
then
echo `date`: dnsview - deleting $NAME $DNSENTRY from the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
samba-tool dns delete 127.0.0.1 $REALM $NAME $DNSTYPE $DNSENTRY --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVERNAME '
LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
source /opt/karoshi/server_network/domain_information/domain_name

echo `date`: dnsview \(federated mode\) - deleting '$NAME' '$DNSENTRY' by '$REMOTE_USER' from '$REMOTE_ADDR' >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'

samba-tool dns delete 127.0.0.1 $REALM '$NAME' '$DNSTYPE' '$DNSENTRY' --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
'
fi
fi

#########################
#Edit entry
#########################
if [ $ACTION = edit ]
then
SERVERICON="/images/submenus/system/computer.png"
echo "<form action=\"/cgi-bin/admin/dnsview.cgi\" method=\"post\"><table class=\"$TABLECLASS\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
<tbody>
<tr><td style=\"width: 180px;\">Name</td><td><input tabindex= \"1\" name=\"_NAME_$NAME-\" value=\"$NAME\" style=\"width: 200px;\" size=\"20\" type=\"text\"></td><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>Enter in the name that you want. This can be the name of a server or an alias.</span></a></td></tr>
<tr><td>DNS Entry</td><td><input tabindex= \"2\" name=\"_ACTION_reallyedit"_"DNSENTRY_$DNSENTRY-\" value=\"$DNSENTRY\" size=\"20\" style=\"width: 200px;\" type=\"text\"></td><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>Enter in the dns information that you want. This would be a tcpip number for an A record or it would be an alias entry for a CNAME.</span></a></td></tr>
<tr><td style=\"width: 180px;\">DNS Type</td><td>$DNSTYPE</td><td><input type = \"hidden\" name=\"_DNSTYPE_\" value=\"$DNSTYPE\"></td></tr>
</tbody></table><br>

<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERTYPE_network_SERVERNAME_$SERVERNAME"_"\" type=\"image\" class=\"images\" src=\"$SERVERICON\" value=\"\"><span>$SERVERNAME</span></a><br>$SERVERNAME
</form>
"
fi

#########################
#Add entry
#########################
if [ $ACTION = add ]
then
SERVERICON="/images/submenus/system/computer.png"
echo "<form action=\"/cgi-bin/admin/dnsview.cgi\" method=\"post\"><table class=\"$TABLECLASS\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
<tbody>
<tr><td style=\"width: 180px;\">Name</td><td><input tabindex= \"1\" name=\"_NAME_\"  style=\"width: 200px;\" size=\"20\" type=\"text\"></td><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>$HELPMSG9</span></a></td></tr>
<tr><td>DNS Entry</td><td><input tabindex= \"2\" name=\"_ACTION_reallyadd"_"DNSENTRY_\" value=\"$DNSENTRY\" size=\"20\" style=\"width: 200px;\" type=\"text\"></td><td><a class=\"info\" href=\"javascript:void(0)\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>$HELPMSG10</span></a></td></tr>
<tr><td style=\"width: 180px;\">DNS Type</td><td>$DNSTYPE
<select name=\"_DNSTYPE_\" style=\"width: 200px;\">
<option value=\"CNAME\">CNAME</option>
<option value=\"A\">A Record</option>
</select>
</td></tr></tbody></table><br>

<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_SERVERTYPE_network_SERVERNAME_$SERVERNAME"_"\" type=\"image\" class=\"images\" src=\"$SERVERICON\" value=\"\"><span>$SERVERNAME</span></a><br>$SERVERNAME
</form>
"
fi

if [ $ACTION = reallyadd ]
then
NAME=`echo $NAME | tr -cd 'A-Za-z0-9'`
if [ $SERVERNAME = $HOSTNAME ]
then
echo `date`: dnsview - adding $NAME $DNSENTRY to the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
samba-tool dns add 127.0.0.1 $REALM $NAME $DNSTYPE $DNSENTRY --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVERNAME '
LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
source /opt/karoshi/server_network/domain_information/domain_name
echo `date`: dnsview - adding '$NAME' '$DNSENTRY' to the dns records by '$REMOTE_USER' from '$REMOTE_ADDR' >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
samba-tool dns add 127.0.0.1 $REALM '$NAME' '$DNSTYPE' '$DNSENTRY' --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
'
fi
fi

if [ $ACTION = reallyedit ]
then

CURRENTNAME=`echo $NAME | cut -d"-" -f1`
NEWNAME=`echo $NAME | cut -d"-" -f2`
CURRENTDNSENTRY=`echo $DNSENTRY | cut -d"-" -f1`
NEWDNSENTRY=`echo $DNSENTRY | cut -d"-" -f2`
NEWNAME=`echo $NEWNAME | tr -cd 'A-Za-z0-9'`

if [ $SERVERNAME = $HOSTNAME ]
then

#Delete current entry
echo `date`: dnsview - deleting $CURRENTNAME $CURRENTDNSENTRY from the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
samba-tool dns delete 127.0.0.1 $REALM $CURRENTNAME $DNSTYPE $CURRENTDNSENTRY --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

#Add revised entry to samba4 dns

echo `date`: dnsview - adding $NEWNAME $NEWDNSENTRY to the dns records by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
samba-tool dns add 127.0.0.1 $REALM $NEWNAME $DNSTYPE $NEWDNSENTRY --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $SERVERNAME '

LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
source /opt/karoshi/server_network/domain_information/domain_name

#Delete current entry
echo `date`: dnsview - deleting '$CURRENTNAME' '$CURRENTDNSENTRY' from the dns records by '$REMOTE_USER' from '$REMOTE_ADDR' >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
samba-tool dns delete 127.0.0.1 $REALM '$CURRENTNAME' '$DNSTYPE' '$CURRENTDNSENTRY' --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'

#Add revised entry to samba4 dns

echo `date`: dnsview - adding '$NEWNAME' '$NEWDNSENTRY' to the dns records by '$REMOTE_USER' from '$REMOTE_ADDR' >> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'
samba-tool dns add 127.0.0.1 $REALM '$NEWNAME' '$DNSTYPE' '$NEWDNSENTRY' --username=Administrator --password=$LDAPPASS 1>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE' 2>> /opt/karoshi/logs/karoshi_web_management/'$LOG_DATE'

'
fi
fi
exit

