#!/bin/bash
#setupkaroshidesktop
#Copyright (C) 2004  Paul Sharrad
#Copyright (C) 2005  The karoshi Team

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata
source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/software

TEXTDOMAIN=karoshi-server
locale 1>/dev/null

#########################
#Add log entry
#########################
echo `date`: '##############'setupkaroshidesktop'##############' >> /opt/karoshi/serversetup/install_log
date >> /opt/karoshi/serversetup/install_log
###########################
#Detect desktop type
###########################
#Using kde
DESKTOP_TYPE=kde

if [ `ps -e | grep -c gnome-session` -gt 0 ]
then
#Using Gnome
DESKTOP_TYPE=gnome
fi

if [ `ps -e | grep -c xfce4` -gt 0 ]
then
#Using Thunar
DESKTOP_TYPE=xfce4
fi



######################
#make sure that kdesu uses su
######################
if [ $DESKTOP_TYPE = kde ]
then
KDESUCHECK=`grep -c super-user-command'='su /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals`
if [ $KDESUCHECK = 0 ]
then
echo '['super-user-command']' >> /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals
echo super-user-command'='su >> /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals
fi
fi

##########################
#Copy in icons
##########################
cp -f /opt/karoshi/serversetup/all/links/adminfilemanager.desktop /opt/karoshi/karoshi_user/Desktop/

#########################
#Add in uptime
#########################
echo `date`: "Adding karoshi-uptime" >> /opt/karoshi/serversetup/install_log
source /opt/karoshi/serversetup/variables/distro
#Copy in uptime script
cp -f /opt/karoshi/serversetup/scripts/uptime/karoshi-uptime.sh /usr/sbin/
cp -f /opt/karoshi/serversetup/scripts/uptime/karoshi-uptime /etc/init.d/
#Start update script
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/karoshi-uptime_start
#Set update script to run on boot
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/karoshi-uptime
#Reset the uptime data
karoshi-uptime.sh reset

##########################
#Set Karoshi User Permissions
##########################
echo `date`: "Setting karoshi user permissions" >> /opt/karoshi/serversetup/install_log
chmod u+X -R /opt/karoshi/karoshi_user
chown -c -R karoshi /opt/karoshi/karoshi_user
#######################
#Stop password aging
#######################
chage -M 99999 root
chage -M 99999 karoshi

############################
#Do sudo for karoshi management user
############################
cp -f /opt/karoshi/serversetup/all/configfiles/sudoers3 /etc/sudoers
[ -d /opt/karoshi/karoshimanagement ] || mkdir /opt/karoshi/karoshimanagement

[ -d /opt/karoshi/"useful scripts" ] || mkdir /opt/karoshi/"useful scripts"
echo /opt/karoshi/serversetup/extra_server/scripts/setupextra_server > /opt/karoshi/karoshimanagement/karoshisetup
chmod 0700 /opt/karoshi/karoshimanagement/karoshisetup
cp -f /opt/karoshi/karoshimanagement/karoshisetup /opt/karoshi/"useful scripts"/

if [ $DESKTOP_TYPE = kde ]
then
echo konqueror --profile filemanagement /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

if [ $DESKTOP_TYPE = gnome ]
then
echo nautilus /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

if [ $DESKTOP_TYPE = xfce4 ]
then
echo thunar /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

##########################
#Stop karoshi setup from running on logon
##########################
echo `date`: "Stopping karoshi setup from running on login" >> /opt/karoshi/serversetup/install_log
[ -f /opt/karoshi/karoshi_user/.config/autostart/karoshi_setup.desktop ] && rm -f /opt/karoshi/karoshi_user/.config/autostart/karoshi_setup.desktop

#Schedule disk_usage
echo `date`: "Scheduling disk usage check" >> /opt/karoshi/serversetup/install_log
[ ! -d /opt/karoshi/server_network/cronjobs/`hostname-fqdn`/jobs ] && mkdir -p /opt/karoshi/server_network/cronjobs/`hostname-fqdn`/jobs
echo 0 1 "*" "*" 6 /opt/karoshi/serversetup/all/\"useful scripts\"/disk_usage > /opt/karoshi/server_network/cronjobs/`hostname-fqdn`/jobs/disk_usage_report.cron
/opt/karoshi/serversetup/all/"useful scripts"/refreshcronjobs

###########################
#Delete remastersys folder
###########################
[ -d /home/remastersys ] && rm -f -R /home/remastersys
###########################
#Change default login user
###########################
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/default_login
###########################
#Do desktop change
###########################
cd /
cp -f /opt/karoshi/serversetup/all/"useful scripts"/* /opt/karoshi/"useful scripts"/
cp -f /opt/karoshi/serversetup/all/"useful scripts"/.alphabet /opt/karoshi/"useful scripts"/
cp -f /opt/karoshi/serversetup/extra_server/"useful scripts"/* /opt/karoshi/"useful scripts"/
chmod -R 0700 /opt/karoshi/"useful scripts"
chmod 0700 /opt/karoshi/karoshimanagement/admin_file_manager

###########################
#Set karoshi and root password
###########################
echo `date`: "Setting karoshi and root passwords" >> /opt/karoshi/serversetup/install_log
function getpassword {
DATA=`yad --separator=SEPARATOR --image="/opt/karoshi/serversetup/essentials/smalllogo2.xpm" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --form --title=$"Setup Karoshi Desktop" --width 400 --wrap --text ''"$PASSWORDMSG"'' --field=$"Password":H --field=$"Confirm":H --button=Ok 2>/dev/null | sed 's/|/REPLACEVERTICALLINE/g' | sed 's/SEPARATOR/|/g'`
PASSWORD1=`echo "$DATA" | cut -d"|" -f1 | sed 's/REPLACEVERTICALLINE/|/g'`
PASSWORD2=`echo "$DATA" | cut -d"|" -f2 | sed 's/REPLACEVERTICALLINE/|/g'`

[ -z "$PASSWORD1" ] && PASSWORD1=notset1
[ -z "$PASSWORD2" ] && PASSWORD2=notset2
}

PASSWORDMSG=$"Please enter your choice for the karoshi and system password."
getpassword

while [ "$PASSWORD1" != "$PASSWORD2" ]
do
	PASSWORDMSG=`echo $"The passwords do not match. Please try again."`
	getpassword
done

echo root:"$PASSWORD1" | chpasswd
echo karoshi:"$PASSWORD1" | chpasswd



