#!/bin/bash
#setupkaroshidesktop
#Copyright (C) 2004  Paul Sharrad
#Copyright (C) 2005  The karoshi Team

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata
source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/language/$LANGCHOICE/extra_server/setupkaroshidesktop
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/software

#########################
#Add log entry
#########################

touch /opt/karoshi/serversetup/setuplog
if [ `grep -c "$TITLE" /opt/karoshi/serversetup/setuplog` = 0 ]
then
echo setupkaroshidesktop:$TITLE:/opt/karoshi/serversetup/extra_server/scripts/setupkaroshidesktop >> /opt/karoshi/serversetup/setuplog
chmod 0600 /opt/karoshi/serversetup/setuplog
fi
echo '##############'setupkaroshidesktop'##############' >> /opt/karoshi/serversetup/install_log
date >> /opt/karoshi/serversetup/install_log
###########################
#Detect desktop type
###########################
#Using kde
DESKTOP_TYPE=kde

if [ `ps -e | grep -c gnome-session` -gt 0 ]
then
#Using Gnome
DESKTOP_TYPE=gnome
fi

if [ `ps -e | grep -c xfce4-session` -gt 0 ]
then
#Using Thunar
DESKTOP_TYPE=xfce4
fi



######################
#make sure that kdesu uses su
######################
if [ $DESKTOP_TYPE = kde ]
then
KDESUCHECK=`grep -c super-user-command'='su /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals`
if [ $KDESUCHECK = 0 ]
then
echo '['super-user-command']' >> /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals
echo super-user-command'='su >> /opt/karoshi/karoshi_user/.kde/share/config/kdeglobals
fi
fi

##########################
#Copy in icons
##########################
cp -f /opt/karoshi/serversetup/all/links/adminfilemanager.desktop /opt/karoshi/karoshi_user/Desktop/

#########################
#Add in uptime
#########################
source /opt/karoshi/serversetup/variables/distro
#Copy in uptime script
cp -f /opt/karoshi/serversetup/scripts/uptime/karoshi-uptime.sh /usr/sbin/
cp -f /opt/karoshi/serversetup/scripts/uptime/karoshi-uptime /etc/init.d/
#Start update script
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/karoshi-uptime_start
#Set update script to run on boot
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/karoshi-uptime
#Reset the uptime data
karoshi-uptime.sh reset

##########################
#Set Karoshi User Permissions
##########################
chmod u+X -R /opt/karoshi/karoshi_user
chown -c -R karoshi /opt/karoshi/karoshi_user
#######################
#Stop password aging
#######################
chage -M 99999 root
chage -M 99999 karoshi

############################
#Do sudo for karoshi management user
############################
cp -f /opt/karoshi/serversetup/all/configfiles/sudoers3 /etc/
[ -d /opt/karoshi/karoshimanagement ] || mkdir /opt/karoshi/karoshimanagement

[ -d /opt/karoshi/"useful scripts" ] || mkdir /opt/karoshi/"useful scripts"
echo /opt/karoshi/serversetup/extra_server/scripts/setupextra_server > /opt/karoshi/karoshimanagement/karoshisetup
chmod 0700 /opt/karoshi/karoshimanagement/karoshisetup
cp -f /opt/karoshi/karoshimanagement/karoshisetup /opt/karoshi/"useful scripts"/

if [ $DESKTOP_TYPE = kde ]
then
echo konqueror --profile filemanagement /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

if [ $DESKTOP_TYPE = gnome ]
then
echo nautilus /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

if [ $DESKTOP_TYPE = xfce4 ]
then
echo thunar /home > /opt/karoshi/karoshimanagement/admin_file_manager
fi

##########################
#Stop karoshi setup from running on logon
##########################
[ -f /opt/karoshi/karoshi_user/.config/autostart/karoshi_setup.desktop ] && rm -f /opt/karoshi/karoshi_user/.config/autostart/karoshi_setup.desktop

#Schedule disk_usage
echo 0 1 "*" "*" 6 /opt/karoshi/serversetup/all/\"useful scripts\"/disk_usage > /opt/karoshi/cronjobs/jobs/disk_usage_report.cron
/opt/karoshi/serversetup/all/"useful scripts"/refreshcronjobs

###########################
#Delete remastersys folder
###########################
[ -d /home/remastersys ] && rm -f -R /home/remastersys
###########################
#Change default login user
###########################
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/default_login
###########################
#Do desktop change
###########################
cd /
cp -f /opt/karoshi/serversetup/all/"useful scripts"/* /opt/karoshi/"useful scripts"/
cp -f /opt/karoshi/serversetup/all/"useful scripts"/.alphabet /opt/karoshi/"useful scripts"/
cp -f /opt/karoshi/serversetup/extra_server/"useful scripts"/* /opt/karoshi/"useful scripts"/
chmod -R 0700 /opt/karoshi/"useful scripts"
chmod 0700 /opt/karoshi/karoshimanagement/admin_file_manager

###########################
#Set karoshi and root password
###########################

function getpassword {
DATA=`yad --image="/opt/karoshi/serversetup/essentials/smalllogo2.xpm" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --form --title="$TITLE" --width 400 --wrap --text "$ERRORMSG $PASSWDMSG1" --field="$PASSWDMSG3":H --field="$CONFIRMMSG":H --button=Ok 2>/dev/null`
PASSWORD1=`echo $DATA | cut -d"|" -f1`
PASSWORD2=`echo $DATA | cut -d"|" -f2`

[ $PASSWORD1'null' = null ] && PASSWORD1=notset1
[ $PASSWORD2'null' = null ] && PASSWORD2=notset2
}

getpassword
while [ $PASSWORD1 != $PASSWORD2 ]
do
ERRORMSG=`echo $ERRORMSG1`
getpassword

done
echo root:$PASSWORD1 | chpasswd
echo karoshi:$PASSWORD1 | chpasswd



