#!/bin/bash
#setupntp
#Copyright (C) 2004  Paul Sharrad
#Copyright (C) 2005  The karoshi Team

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk

[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata

[ -e /opt/karoshi/serversetup/variables/language ] || /opt/karoshi/serversetup/changelanguage
[ -e /opt/karoshi/serversetup/variables/distro ] || /opt/karoshi/serversetup/changedistro

source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/software

TEXTDOMAIN=karoshi-server
locale 1>/dev/null

NTPSERVERIP=$NTPSERVER

#########################
#Add log entry
#########################
echo `date`: '##############'setupntp'##############' >> /opt/karoshi/serversetup/install_log
######################
#Final ntp Install check
######################

if ! test -f /etc/init.d/$NTPVER
then
echo /etc/init.d/$NTPVER does not exist >> /opt/karoshi/serversetup/install_log
yad --title ''$"Setup"' '$"NTP"'' --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --width 400 --timeout=4 --image=dialog-question --text='NTP - '$"This package is not installed."'' --no-buttons 2>/dev/null
exit 101
fi

#############################
#Ensure that NTP is running on boot
##############################
echo `date`: "Setting ntp to run on boot" >> /opt/karoshi/serversetup/install_log
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/ntp

#echo Setting up NTP service to get the time from pool.ntp.org
/etc/init.d/$NTPVER stop 1> /dev/null
#echo Creating ntp configuration file
rm -f /etc/ntp.conf
###############################
#create ntp.conf
###############################
echo `date`: "Configuring ntp.conf" >> /opt/karoshi/serversetup/install_log
echo server	127.127.1.0 > /etc/ntp.conf
echo fudge	127.127.1.0 stratum 10	>> /etc/ntp.conf
echo server 0.pool.ntp.org >> /etc/ntp.conf
echo server 1.pool.ntp.org >> /etc/ntp.conf
echo server 2.pool.ntp.org >> /etc/ntp.conf
echo server pool.ntp.org >> /etc/ntp.conf
echo driftfile /etc/ntp/drift >> /etc/ntp.conf
echo broadcastdelay	0.008 >> /etc/ntp.conf
###############################
#Do initial time syncronisation
###############################
echo `date`: "Doing initial time sync" >> /opt/karoshi/serversetup/install_log
ntpdate -t 1 $NTPSERVERIP
echo `date`: "Starting ntp" >> /opt/karoshi/serversetup/install_log
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ntp_start
exit

