#!/bin/bash
#Copyright (C) 2004  Paul Sharrad
#Copyright (C) 2005  The karoshi Team
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
[ -d $HOME/.tempdata ] || mkdir $HOME/.tempdata
source /opt/karoshi/serversetup/variables/language
source /opt/karoshi/serversetup/variables/xdialog
source /opt/karoshi/serversetup/language/$LANGCHOICE/orac/softwarerequirements
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/hal/software
##############################
#Check to see if the software has been installed
##############################
if test -f /etc/init.d/$NTPVER
then
NTPSTATUS=$INSTALLED
clear
else
NTPSTATUS=$NOTINSTALLED
fi
if test -f /etc/init.d/$SMBVER
then
SMBSTATUS=$INSTALLED
clear
else
SMBSTATUS=$NOTINSTALLED
fi

if test -f /etc/init.d/$YPVER
then
YPSTATUS=$INSTALLED
clear
else
YPSTATUS=$NOTINSTALLED
fi

if test -f /etc/init.d/$SHOREWALLVER
then
SHOREWALLSTATUS=$INSTALLED
clear
else
SHOREWALLSTATUS=$NOTINSTALLED
fi


if test -f /etc/init.d/$PORTMAPVER
then
PORTMAPSTATUS=$INSTALLED
clear
else
PORTMAPSTATUS=$NOTINSTALLED
fi


##############################
#Display software required
##############################
Xdialog --title "$TITLE" \
--icon $ICON --rc-file $RCFILE --no-cancel --msgbox  "$TOPMSG: \n\n $NTPMSG1: $NTPSTATUS \n $NTPMSG2 \n\n $YPBINDMSG1: $YPSTATUS \n $YPBINDMSG2 \n\n $SMBMSG1: $SMBSTATUS \n $SMBMSG2 \n\n $SWALLMSG1: $SHOREWALLSTATUS \n $SWALLMSG2" 40 90
case $ in
0)
	;;
255)
	;;
esac
exit