#!/bin/bash
export DEBIAN_FRONTEND=noninteractive
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/variables/language
#baseinstall
BASEINSTALLPATH=/opt/karoshi/serversetup/extra_server/scripts
BASEINSTALLPATH2=/opt/karoshi/serversetup/all/scripts
KAROSHILOG=/opt/karoshi/serversetup/install_log

TEXTDOMAIN=karoshi-server
locale 1>/dev/null

#Set timezone in php.ini
[ -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/set_php_timezone ] && /opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/set_php_timezone

#Delete samba config file
rm -f /etc/samba/smb.conf

function checkstatus {
EXITSTATUS=`echo $?`
if [ $EXITSTATUS = 101 ]
then
yad --title ''$"Extra Server Setup"' '$VERSION'' --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --text=$"The standard setup has not completed correctly." --timeout=3 --timeout-indicator=bottom --no-buttons 2>/dev/null
exit
fi
if [ $EXITSTATUS = 103 ]
then
exit
fi
}

function do_setup {
echo "1"
echo '# '$"Checking Network"''
$BASEINSTALLPATH2/checknetwork extra_server 1>>$KAROSHILOG 2>>$KAROSHILOG
checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
echo "28"
echo '# '$"Setup" $"Shorewall"''
$BASEINSTALLPATH/setupshorewall 1>>$KAROSHILOG 2>>$KAROSHILOG
checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
echo "56"
echo '# '$"Setup" $"NTP"''
$BASEINSTALLPATH/setupntp 1>>$KAROSHILOG 2>>$KAROSHILOG
checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
echo "84"
echo '# '$"Setup" $"Karoshi Desktop"''
$BASEINSTALLPATH/setupkaroshidesktop 1>>$KAROSHILOG 2>>$KAROSHILOG
echo "100"
echo '# '$"Setup" $"SSH"''
$BASEINSTALLPATH/setupssh 1>>$KAROSHILOG 2>>$KAROSHILOG
checkstatus 1>>$KAROSHILOG 2>>$KAROSHILOG
#Kill status bar
killall yad
}


do_setup | yad --title $"Extra Server Setup" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png"  --geometry=400x100+0+0 --no-buttons --text ''$"Extra Server Setup"'\n\n\n'$STATUS'' --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --progress

#Setup uptime data for the server
/opt/karoshi/serversetup/all/scripts/setup_uptime

###########################
#Display completed message
############################
yad --title $"Extra Server Setup" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --width 400 --height 100 --timeout=10  --timeout-indicator=bottom --text=''$"The standard setup is now complete."' '$"Please join this server to the system using the web management on your main server."'' --no-buttons

#Create initial disk usage report
#/opt/karoshi/serversetup/all/"useful scripts"/disk_usage


exit

