#!/bin/bash

#This script has been developed from the information at https://help.ubuntu.com/community/LiveCDCustomizationFromScratch

KAROSHIVER=karoshiV10.0.1
BUILDPATH=/home/karoshi/$KAROSHIVER
ARCH=amd64
RELEASE=trusty

clear

#Install debootstrap
which debootstrap 1>/dev/null
if [ $? != 0 ]
then
	echo -e "Installing debootstrap\n"
	sleep 1
	sudo apt-get install debootstrap
fi

#Create the chroot folder
if [ ! -d $BUILDPATH/chroot ]
then
	echo -e "Creating $BUILDPATH/chroot\n"
	sleep 1	
	mkdir -p $BUILDPATH/chroot
fi

#Chroot into the folder
cd $BUILDPATH
#sudo debootstrap --arch=$ARCH $RELEASE chroot

#Mount dev folder

echo -e "Mounting $BUILDPATH/chroot\n"
sleep 1	
sudo mount --bind /dev chroot/dev

#Copy in system files for network configuration for the chroot

echo -e "Copying /etc/hosts /etc/resolv.conf\n"
sleep 1	
sudo cp /etc/hosts chroot/etc/hosts
sudo cp /etc/resolv.conf chroot/etc/resolv.conf
sudo cp /opt/karoshi/serversetup/distro/ubuntu/all/buildserver/configfiles/sources.list chroot/etc/apt/sources.list

#Copy in serversetup
sudo mkdir -p chroot/opt/karoshi
sudo unzip /tmp/master.zip -d chroot/opt/karoshi/

#Backup /sbin/initctl
sudo cp /sbin/initctl /sbin/initctl.$$

#Copy in script to run in the chroot
sudo cp /opt/karoshi/serversetup/distro/ubuntu/all/buildserver/configure_chroot chroot/tmp/

sudo chmod 0755 chroot/tmp/configure_chroot

sudo chroot chroot /tmp/configure_chroot

sudo umount /dev

#Install software to create the cd image
echo -e "Installing syslinux squashfs-tools and genisoimage\n"
sleep 1	
sudo apt-get install syslinux squashfs-tools genisoimage

#Remove existing image directory
if [ -d image ]
then
	echo -e "Deleting existing image directory\n"
	sleep 1	
	rm -f -R image
fi

#Create image directory
echo -e "Creating image directory\n"
sleep 1	

mkdir -p image/{casper,isolinux,install}

#Copy in the kernel built with the casper scripts
echo -e "Copying in the kernel built with casper scripts\n"
sleep 1	
cp chroot/boot/vmlinuz-3.13.**-**-generic image/casper/vmlinuz
cp chroot/boot/initrd.img-3.13.**-**-generic image/casper/initrd.lz

#Copy in isolinux and memtest binaries
echo -e "Copying in isolinux and memtest binaries\n"
sleep 1	
cp /usr/lib/syslinux/isolinux.bin image/isolinux/
cp /boot/memtest86+.bin image/install/memtest

#Create boot instructions
echo -e "Creating boot instructions\n"
sleep 1	
echo 'splash.rle

************************************************************************

This is a Ubuntu Remix Live CD.

For the default live system, enter "live".  To run memtest86+, enter "memtest"

************************************************************************' > image/isolinux/isolinux.txt

#Create isolinux.cfg
echo -e "Creating isolinux.cfg\n"
sleep 1	
echo 'default vesamenu.c32
prompt 0
timeout 100

menu title __LIVECDLABEL__
menu background splash.png
menu color title 1;37;44 #c0ffffff #00000000 std

label install
  menu label install - Install The Linux Schools Project Server
  kernel /casper/vmlinuz
  append  file=/cdrom/preseed/custom.seed boot=casper automatic-ubiquity initrd=/casper/initrd.lz quiet splash --

label memtest
  menu label memtest - Run memtest
  kernel /install/memtest
  append -

label hd
  menu label hd - boot the first hard disk
  localboot 0x80
  append -
' > image/isolinux/isolinux.cfg

#Create manifest
echo -e "Creating manifest\n"

sudo chroot chroot dpkg-query -W --showformat='${Package} ${Version}\n' | sudo tee image/casper/filesystem.manifest
sudo cp -v image/casper/filesystem.manifest image/casper/filesystem.manifest-desktop
REMOVE='ubiquity ubiquity-frontend-gtk ubiquity-frontend-kde casper lupin-casper live-initramfs user-setup discover1 xresprobe os-prober libdebian-installer4'
for i in $REMOVE 
do
        sudo sed -i "/${i}/d" image/casper/filesystem.manifest-desktop
done

echo -e "Compressing chroot\n"
sleep 1
#Compress the chroot
sudo mksquashfs chroot image/casper/filesystem.squashfs 
#Write the filesystem size - needed by the installer
echo -e "Writing the filesystem size\n"
sleep 1
printf $(sudo du -sx --block-size=1 chroot | cut -f1) > image/casper/filesystem.size

#Create diskdefines
echo '#define DISKNAME  '$KAROSHIVER'
#define TYPE  binary
#define TYPEbinary  1
#define ARCH  amd64
#define ARCHamd64  1
#define DISKNUM  1
#define DISKNUM1  1
#define TOTALNUM  0
#define TOTALNUM0  1
' > image/README.diskdefines

#Recognition as a Ubuntu remix
touch image/ubuntu
mkdir image/.disk
cd image/.disk
touch base_installable
echo "full_cd/single" > cd_type
echo "$KAROSHIVER" > info
echo "http//www.linuxschools.com" > release_notes_url
cd ../..

#Calculate MD5
echo -e "Calculating MD5\n"
sleep 1
sudo -s (cd image && find . -type f -print0 | xargs -0 md5sum | grep -v "\./md5sum.txt" > md5sum.txt)

echo -e "Creating the iso image\n"
sleep 1
#Create iso image for the live CD
cd image
sudo mkisofs -r -V "$KAROSHIVER" -cache-inodes -J -l -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -o ../$KAROSHIVER.iso .
cd ..
exit
