#!/bin/bash
#Copyright (C) 2009  Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#

##########################
#Section Control
##########################
source /opt/karoshi/server_network/menusettings

#Website: http://www.karoshi.org.uk
[ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/menus/menu ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/menus/menu
echo '<img src="/images/small_logo.png" alt="logo" align="top"> <font style="font-weight: bold;" size="+2">Web Management '$SCHOOL_NAME'</font> <small><small>
'$VERSION' : 130816-1132
</small></small>'

#Check for warning messages
if [ -f /opt/karoshi/web_controls/warnings/summary.txt ]
then
echo '<div id="tickerbar">'

echo "<SCRIPT type=\"text/javascript\" LANGUAGE=\"JavaScript\">

/**************************************
* http://vertical-scroller.vbarsan.com/
*    This notice may not be removed 
**************************************/
//scroller's width
var swidth=1000;

//scroller's height
var sheight=15;

//scroller's speed 
var sspeed=2;
var restart=sspeed;
var rspeed=sspeed;

//scroller's pause 
var spause=2000;

var singletext=new Array();"
cat /opt/karoshi/web_controls/warnings/summary.txt
echo "var ii=0;
function goup(){if(sspeed!=rspeed*16){sspeed=sspeed*2;restart=sspeed;}}

function start(){
if(document.getElementById){ns6div=document.getElementById('iens6div');ns6div.style.top=sheight+\"px\";ns6div.innerHTML=singletext[0];sizeup=ns6div.offsetHeight;ns6scroll();}
else 
if(document.layers){ns4layer=document.ns4div.document.ns4div1;ns4layer.top=sheight;ns4layer.document.write(singletext[0]);ns4layer.document.close();sizeup=ns4layer.document.height;ns4scroll();}
else 
if(document.all){iediv=iens6div;iediv.style.pixelTop=sheight+\"px\";iediv.innerHTML=singletext[0];sizeup=iediv.offsetHeight;iescroll();}}
function iescroll(){if(iediv.style.pixelTop>0&&iediv.style.pixelTop<=sspeed){iediv.style.pixelTop=0;setTimeout(\"iescroll()\",spause);}else 
if(iediv.style.pixelTop>=sizeup*-1){iediv.style.pixelTop-=sspeed+\"px\";setTimeout(\"iescroll()\",100);}else{if(ii==singletext.length-1)ii=0;else ii++;iediv.style.pixelTop=sheight+\"px\";iediv.innerHTML=singletext[ii];sizeup=iediv.offsetHeight;iescroll();}}
function ns4scroll(){if(ns4layer.top>0&&ns4layer.top<=sspeed){ns4layer.top=0;setTimeout(\"ns4scroll()\",spause);}else 
if(ns4layer.top>=sizeup*-1){ns4layer.top-=sspeed;setTimeout(\"ns4scroll()\",100);}else{if(ii==singletext.length-1)ii=0;else ii++;ns4layer.top=sheight;ns4layer.document.write(singletext[ii]);ns4layer.document.close();sizeup=ns4layer.document.height;ns4scroll();}}
function ns6scroll(){if(parseInt(ns6div.style.top)>0&&parseInt(ns6div.style.top)<=sspeed){ns6div.style.top=0;setTimeout(\"ns6scroll()\",spause);}else 
if(parseInt(ns6div.style.top)>=sizeup*-1){ns6div.style.top=parseInt(ns6div.style.top)-sspeed+\"px\";setTimeout(\"ns6scroll()\",100);}
else{if(ii==singletext.length-1)ii=0;else ii++;
ns6div.style.top=sheight+\"px\";ns6div.innerHTML=singletext[ii];sizeup=ns6div.offsetHeight;ns6scroll();}}
//-- end Algorithm -->

</script>
<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">
<tr><td>
<SCRIPT type=\"text/javascript\" LANGUAGE=\"JavaScript\">if(document.layers){document.write('<ilayer id=\"ns4div\" width=\"'+swidth+'\" height="'+sheight+'"><layer id=\"ns4div1\" width=\"'+swidth+'\" height=\"'+sheight+'\" onmouseover=\"sspeed=0;\" onmouseout=\"sspeed=rspeed\"><\/layer><\/ilayer>')}
if(document.getElementById||document.all){document.write('<div style=\"position:relative;overflow:hidden;width:'+swidth+'px;height:'+sheight+'px;clip:rect(0 '+swidth+'px '+sheight+'px 0);\" onmouseover=\"sspeed=0\" onmouseout=\"sspeed=rspeed\"><div id=\"iens6div\" style=\"position:relative;width:'+swidth+'px;\"><\/div><\/div>');}</script>
</td></tr></table>"




echo '</div>'

fi
echo '<div id="navbar"><span class="preload1"></span>
<span class="preload2"></span>

<ul id="nav">
	<li class="top"><a href="/cgi-bin/admin/redirect.cgi" class="top_link"><span>Home</span></a></li>
	<li class="top"><a href="/cgi-bin/admin/helpdesk_add_fm.cgi" id="helpdesk" class="top_link"><span class="down">'$HELPDESKSMSG'</span></a>
		<ul class="sub">
			<li><a href="/cgi-bin/admin/helpdesk_add_fm.cgi">'$HELPDESKADDMSG'</a></li>
			<li><a href="/cgi-bin/admin/helpdesk_view_fm.cgi">'$HELPDESKVIEWMSG'</a></li>
			<li><a href="/cgi-bin/admin/helpdesk_view_completed_fm.cgi">'$HELPDESKVIEWMSG2'</a></li>
			<li><a href="/cgi-bin/admin/helpdesk_set_defaults_fm.cgi">'$HELPDESKSETDEFAULTS'</a></li>
		</ul>
	</li>
	<li class="top"><a href="/cgi-bin/admin/change_password_fm.cgi" id="menu" class="top_link"><span class="down">'$USERMSG'</span></a>
		<ul class="sub">'

if [ $ADDUSERCTRL = yes ]
then
echo '			<li><a href="/cgi-bin/admin/add_user_fm.cgi">'$ADDUSERMSG'</a></li>
			<li><a href="/cgi-bin/admin/delete_user_fm.cgi">'$DELETEUSERMSG'</a></li>
'
fi
echo '			<li class="mid"><a href="/cgi-bin/admin/change_password_fm.cgi" class="fly">'$MODUSERSMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/change_password_fm.cgi">'$CHANGEPASSMSG'</a></li>
						<li><a href="/cgi-bin/admin/reset_password_fm.cgi">'$RESETPASSMSG'</a></li>
						<li><a href="/cgi-bin/admin/change_primary_group_fm.cgi">'$CHANGEPRIGRPMSG'</a></li>
						<li><a href="/cgi-bin/admin/group_membership_fm.cgi">'$CHANGESECGRPMSG'</a></li>
						<li class="mid"><a href="/cgi-bin/admin/view_acceptable_use_authorisations_fm.cgi" class="fly">'$ACCEPTABLEUSEMSG'</a>
						      <ul>
						      <li><a href="/cgi-bin/admin/view_acceptable_use_authorisations_fm.cgi">'$VIEWTRIALAUTHMSG'</a></li>
						      <li><a href="/cgi-bin/admin/view_approved_users_fm.cgi">'$VIEWAUTHORISEDMSG'</a></li>
						      <li><a href="/cgi-bin/admin/set_acceptable_use_grace_time_fm.cgi">'$SETGRACETIMEMSG'</a></li>
						      <li><a href="/cgi-bin/admin/acceptable_use_status_fm.cgi">'$ACCEPTABLEUSESTATUSMSG'</a></li>
						      </ul>
						 </li>
						<li><a href="/cgi-bin/admin/ban_user_account.cgi">'$BANUSERMSG'</a></li>
						<li><a href="/cgi-bin/admin/banned_users_view_fm.cgi">'$VIEWBANUSERMSG'</a></li>
						<li class="mid"><a href="/cgi-bin/admin/user_image_upload_fm.cgi" class="fly">'$USERIMAGEMSG'</a>
						<ul>
							<li><a href="/cgi-bin/admin/user_image_upload_fm.cgi">'$USERIMAGEMSG'</a></li>
							<li><a href="/cgi-bin/admin/user_image_bulk_upload_fm.cgi">'$BULKUSERUPLOADMSG'</a></li>
						</ul>
						</li>
					</ul>
			</li>
			<li><a href="/cgi-bin/admin/change_primary_group_fm.cgi" class="fly">'$GROUPSMSG'</a>
					<ul>						
						<li><a href="/cgi-bin/admin/label_groups_fm.cgi">'$LABELGROUPSMSG'</a></li>'
if [ $ADDUSERCTRL = yes ]
then
echo '						<li><a href="/cgi-bin/admin/new_primary_group_fm.cgi">'$NEWPRIGRPMSG'</a></li>'
fi
echo '						<li><a href="/cgi-bin/admin/new_group_fm.cgi">'$NEWGRPMSG'</a></li>
						<li><a href="/cgi-bin/admin/modify_groups_fm.cgi">'$MODIFYGROUPMSG'</a></li>
						<li><a href="/cgi-bin/admin/copy_files_upload_fm.cgi">'$CPFILEMSG'</a></li>
					</ul>
			</li>

			<li class="mid"><a href="/cgi-bin/admin/incident_log_view_fm.cgi" class="fly">'$USERINFOMSG'</a>
					<ul>
			<li><a href="/cgi-bin/admin/incident_log_add.cgi">'$RECINCMSG'</a></li>
			<li><a href="/cgi-bin/admin/incident_log_view_fm.cgi">'$VIEWLOGSMSG'</a></li>
			<li><a href="/cgi-bin/admin/samba_logs_user_fm.cgi">'$USERCONNECTIONLOGSMSG'</a></li>
			<li><a href="/cgi-bin/admin/view_auto_reset_passwords_fm.cgi">'$AUTORESETPASSWORDS'</a></li>
			<li><a href="/cgi-bin/admin/show_user_info_fm.cgi">'$SHOWUSERINFOMSG'</a></li>
			<li><a href="/cgi-bin/admin/show_users_in_a_group_fm.cgi">'$SHOWUSERINFOMSG2'</a></li>
				</ul>
			</li>


			<li class="mid"><a href="/cgi-bin/admin/exam_accounts_enable_disable_fm.cgi" class="fly">'$EXAMSMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/exam_accounts_change_passwords_fm.cgi">'$CHANGEPASSMSG'</a></li>
						<li><a href="/cgi-bin/admin/exam_accounts_reset_passwords_fm.cgi">'$RESETPASSMSG'</a></li>
						<li><a href="/cgi-bin/admin/exam_accounts_view_reset_passwords_fm.cgi">'$VIEWRESETPASSWORDS'</a></li>
						<li><a href="/cgi-bin/admin/exam_accounts_archive_fm.cgi">'$ARCHIVEACCOUNTS'</a></li>
						<li><a href="/cgi-bin/admin/exam_accounts_upload_fm.cgi">'$COPYDATA'</a></li>
						<li><a href="/cgi-bin/admin/exam_accounts_enable_disable_fm.cgi">'$ENABLE_DISABLE'</a></li>
						<li><a href="/cgi-bin/admin/exam_accounts_create_fm.cgi">'$EXTRAACCOUNTS'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/bulk_user_creation_upload_fm.cgi" class="fly">'$BLKUSERCRMSG'</a>
					<ul>'
if [ $ADDUSERCTRL = yes ]
then
echo '						<li><a href="/cgi-bin/admin/bulk_user_creation_upload_fm.cgi">'$BLKUSERCRMSG'</a></li>
						<li><a href="/cgi-bin/admin/bulk_user_creation_view_passwords_fm.cgi">'$VIEWNEWPASSMSG'</a></li>'
fi
echo '						<li><a href="/cgi-bin/admin/bulk_user_creation_import_enrollment_numbers_fm.cgi">'$IMPORTUSERIDMSG'</a></li>
					</ul>
			</li>
		</ul>
	</li>
	<li class="top"><a href="/cgi-bin/admin/change_management_passwords_fm.cgi" id="System" class="top_link"><span class="down">'$SYSTEMMSG'</span></a>
		<ul class="sub">
			<li class="mid"><a href="/cgi-bin/admin/karoshi_servers_view.cgi" class="fly">'$KAROSHSERVERSMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/karoshi_servers_add_fm.cgi">'$ADDSERVERMSG'</a></li>
						<li><a href="/cgi-bin/admin/karoshi_servers_view.cgi">'$ADDSERVERROLEMSG'</a></li>
						<li><a href="/cgi-bin/admin/karoshi_servers_view.cgi">'$SHOWSERVERMSG'</a></li>
						<li><a href="/cgi-bin/admin/services_view_fm.cgi">'$SERVICESMSG'</a></li>
						<li><a href="/cgi-bin/admin/change_management_passwords_fm.cgi">'$SYSPASSMSG'</a></li>
						<li><a href="/cgi-bin/admin/custom_command_fm.cgi">'$CUSTOMMSG'</a></li>
						<li><a href="/cgi-bin/admin/server_info_fm.cgi">'$SERVERINFOMSG'</a>
						<li><a href="/cgi-bin/admin/windows_servers_add_fm.cgi">'$ADDWINDOWSSERVERSMSG'</a></li>
						<li><a href="/cgi-bin/admin/windows_machine_commands_fm.cgi">'$WINDOWSCOMMANDSMSG'</a></li>
						<li><a href="/cgi-bin/admin/shutdown_fm.cgi">'$SHUTDOWNMSG'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/karoshi_servers_view.cgi" class="fly">'$STORAGEMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/home_folders_fm.cgi">'$HOMEFOLDERSMSG'</a></li>
						<li><a href="/cgi-bin/admin/disk_information_fm.cgi">'$DISKINFORMATION'</a></li>
						<li><a href="/cgi-bin/admin/disk_usage_fm.cgi">'$DISKUSAGE'</a></li>
						<li><a href="/cgi-bin/admin/view_disk_usage_logs_fm.cgi">'$DISKUSAGELOGS'</a></li>
						<li class="mid"><a href="/cgi-bin/admin/quotas_enable_fm.cgi" class="fly">'$QUOTAS'</a>
						<ul>
							<li><a href="/cgi-bin/admin/quotas_enable_fm.cgi">'$ENABLEQUOTAS'</a></li>
							<li><a href="/cgi-bin/admin/quotas_view_partitions.cgi">'$VIEWENABLEDPARTITIONS'</a></li>
							<li><a href="/cgi-bin/admin/quotas_view_usage_fm.cgi">'$VIEWQUOTAUSAGE'</a></li>
							<li><a href="/cgi-bin/admin/quotas_view_over_usage_fm.cgi">'$VIEWOVERQUOTAUSAGE'</a></li>
							<li><a href="/cgi-bin/admin/quotas_set_fm.cgi">'$SETQUOTAS'</a></li>
						</ul>
						<li class="mid"><a href="/cgi-bin/admin/zfs_raid_control_fm.cgi" class="fly">'$ZFSRAIDMSG'</a>
						<ul>
							<li><a href="/cgi-bin/admin/zfs_raid_create_fm.cgi">'$CREATERAIDMSG'</a></li>
							<li><a href="/cgi-bin/admin/zfs_raid_control_fm.cgi">'$CONTROLRAIDMSG'</a></li>
						</ul>
						</li>
						<li class="mid"><a href="/cgi-bin/admin/software_raid_control_fm.cgi" class="fly">'$SOFTWARERAIDMSG'</a>
						<ul>
							<li><a href="/cgi-bin/admin/software_raid_create_fm.cgi">'$CREATERAIDMSG'</a></li>
							<li><a href="/cgi-bin/admin/software_raid_control_fm.cgi">'$CONTROLRAIDMSG'</a></li>
						</ul>
						<li><a href="/cgi-bin/admin/samba_add_share_fm.cgi">'$ADDNETWORKSHAREMSG'</a></li>
			</li>'
if [ $FEDERATEDCTL = yes ]
then
echo '						<li><a href="/cgi-bin/admin/federated_file_sync_fm.cgi">'$FEDERATIONSYNCMSG'</a></li>'
fi
echo '					</ul>
			</li>
			<li><a href="/cgi-bin/admin/file_manager.cgi">'$FILEMANAGER'</a></li>
			<li><a href="/cgi-bin/admin/find_student_files_fm.cgi">'$FINDSTUDENTFILES'</a></li>
			<li class="mid"><a href="/cgi-bin/admin/remote_management_view.cgi" class="fly">'$KAROSHIMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/remote_management_view.cgi">'$VIEWREMOTEADMINS'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_change_password_fm.cgi">'$CHANGEREMOTEPASSWORDS'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_restrict_fm.cgi">'$RESTRICREMOTEACCES'</a></li>
						<li><a href="/cgi-bin/admin/staff_restrictions.cgi">'$RESTRICTSTAFFACCESS'</a></li>
						<li><a href="/cgi-bin/admin/set_default_page_fm.cgi">'$SETDEFAULTPAGE'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_change_language.cgi">'$CHANGELANG'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_change_theme.cgi">'$CHANGETHEME'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_change_global_language.cgi">'$CHANGEGLOBALLANG'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_change_global_theme.cgi">'$CHANGEGLOBALTHEME'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_change_timeout_fm.cgi">'$CHANGETIMEOUT'</a></li>
						<li><a href="/cgi-bin/admin/remote_management_name_fm.cgi">'$WEB_MANAGEMENT_NAME'</a></li>
						<li><a href="/cgi-bin/admin/view_karoshi_web_management_logs.cgi">'$WMANLOGMSG'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/update_karoshi_fm.cgi" class="fly">'$UPDATEMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/update_servers_fm.cgi">'$UPDATESERVERSMSG'</a></li>
						<li><a href="/cgi-bin/admin/update_servers_view_logs_fm.cgi">'$UPDATESERVERLOGSMSG'</a></li>
						<li><a href="/cgi-bin/admin/update_karoshi_fm.cgi">'$UPDATEKAROSHIMSG'</a></li>
						<li><a href="/cgi-bin/admin/update_karoshi_upload_fm.cgi">'$UPDATEKAROSHIMSG2'</a></li>
						<li><a href="/cgi-bin/admin/update_server_proxy_settings_choose_server_fm.cgi">'$UPSTREAMPROXY'</a></li>'
#Moodle
if [ $MOODLECTRL = yes ]
then
echo '						<li><a href="/cgi-bin/admin/update_moodle_fm.cgi">'$UPDATEMOODLEMSG'</a></li>
						<li><a href="/cgi-bin/admin/update_moodle_theme_fm.cgi">'$UPDATEMOODLETHEMEMSG'</a></li>'
fi

echo '					</ul>
			</li>'

echo '			<li class="mid"><a href="/cgi-bin/admin/ntp.cgi" class="fly">'$SERVERTIMEMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/ntp.cgi">'$CONFIGURENTPMSG'</a></li>
						<li><a href="/cgi-bin/admin/time_fm.cgi">'$TIMEMSG'</a></li>
						<li><a href="/cgi-bin/admin/uptime_fm.cgi">'$UPTIMEMSG'</a>
						<li><a href="/cgi-bin/admin/cron_view_fm.cgi">'$VIEWCRON'</a></li>
					</ul>
			</li>'
if [ $BACKUPCTRL = yes ]
then
echo '			<li class="mid"><a href="/cgi-bin/admin/backup_enable_disable_fm.cgi" class="fly">'$BACKUPMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/backup_enable_disable_fm.cgi">'$ENABLEBACKUP'</a></li>
						<li><a href="/cgi-bin/admin/backup_view_logs_fm.cgi">'$VIEWBACKUPLOGS'</a></li>
						<li><a href="/cgi-bin/admin/backup_now_fm.cgi">'$RUNBACKUP'</a></li>
						<li><a href="/cgi-bin/admin/restore_files_fm.cgi">'$RESTOREFILES'</a></li>
					</ul>
			</li>'
fi

if [ $RADIUSCTRL = yes ]
then
echo '			<li class="mid"><a href="/cgi-bin/admin/radius_view_access_pt_fm.cgi" class="fly">'$RADIUSNETWORK'</a>
					<ul>
						<li><a href="/cgi-bin/admin/radius_add_access_pt_fm.cgi">'$ADDRADIUSWIRELESS'</a></li>
						<li><a href="/cgi-bin/admin/radius_view_access_pt_fm.cgi">'$VIEWRADIUSWIRELESS'</a></li>
					</ul>
			</li>'
fi
echo '			<li><a href="/cgi-bin/admin/apply_ssl_certificate_fm.cgi">'$SSLCERTMSG'</a></li>
			<li><a href="/cgi-bin/admin/ssl_certs_commercial_fm.cgi">'$SSLCERTMSG2'</a></li>
			<li><a href="/admin/phpldapadmin/" target="_blank">'$LDAPMSG'</a></li>
			<li><a href="/cgi-bin/admin/clear_warnings_fm.cgi">'$CLEARWARNINGSMSG'</a></li>
		</ul>
	</li>
	<li class="top"><a href="/cgi-bin/admin/asset_register_view.cgi" id="infrastucture" class="top_link"><span class="down">'$INFRASTRUCTURESMSG'</span></a>
		<ul class="sub">
			<li><a href="/cgi-bin/admin/asset_register_view.cgi">'$ASSETREGISTER'</a></li>'
if [ $DHCPCTRL = yes ]
then
echo '			<li class="mid"><a href="/cgi-bin/admin/dhcp_fm.cgi" class="fly">'$DHCPMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/dhcp_fm.cgi">'$CONFIGUREDHCPMSG'</a></li>
						<li><a href="/cgi-bin/admin/dhcp_view_leases.cgi">'$DHCPLEASESMSG'</a></li>
					</ul>
			</li>'
fi

echo '<li><a href="/cgi-bin/admin/dnsview_fm.cgi">'$DNSVIEWMSG'</a></li>'

#Monitoring
if [ $MONITORINGCTRL = yes ]
then
echo '			<li class="mid"><a href="/cgi-bin/admin/mon_status.cgi" class="fly">'$MONNSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/monitors_add_fm.cgi">'$ADDCUSTMSG'</a></li>
						<li><a href="/cgi-bin/admin/monitors_view.cgi">'$VIEWMONSERVERSMSG'</a></li>
						<li><a href="/cgi-bin/admin/mon_status.cgi">'$SERVERSTATUSMSG'</a></li>
						<li><a href="/cgi-bin/admin/monitors_add_email_alert_fm.cgi">'$MONEMAILALERTMSG'</a></li>
						<li><a href="/cgi-bin/admin/monitors_view_email_alerts_fm.cgi">'$MONVIEWEMAILALERTMSG'</a></li>
					</ul>
			</li>'
fi
echo '		
			<li class="mid"><a href="/cgi-bin/admin/ups_status.cgi" class="fly">'$UPSMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/ups_add_fm.cgi">'$UPSADDMSG'</a></li>
						<li><a href="/cgi-bin/admin/ups_slave_add_fm.cgi">'$UPSSLAVEADDMSG'</a></li>
						<li><a href="/cgi-bin/admin/ups_status.cgi">'$UPSSTATUSMSG'</a></li>
					</ul>
			</li>

		</ul>
	</li>
	<li class="top"><a href="/cgi-bin/admin/domain_information.cgi" id="Client" class="top_link"><span class="down">'$CLIENTMSG'</span></a>
		<ul class="sub">
			<li><a href="/cgi-bin/admin/domain_information.cgi">'$DOMAININFO'</a></li>'
#OCS Inventory
if [ $OCSCTRL = yes ]
then
echo '			<li><a href="/cgi-bin/admin/ocs.cgi" target="_blank">'$OCS'</a></li>'
fi
echo '			<li><a href="/cgi-bin/admin/locations.cgi">'$CLIENTLOCATIONS'</a></li>
			<li class="mid"><a href="/cgi-bin/admin/wake_on_lan_add.cgi" class="fly">'$WAKEONLAN'</a>
					<ul>
						<li><a href="/cgi-bin/admin/wake_on_lan_add.cgi">'$WAKEONLANADD'</a></li>
						<li><a href="/cgi-bin/admin/wake_on_lan_now.cgi">'$WAKEONLANNOW'</a></li>
						<li><a href="/cgi-bin/admin/wake_on_lan_view.cgi">'$VIEWWAKELONLAN'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/linux_client_choose_background_fm.cgi" class="fly">'$LINUXCLIENT'</a>
					<ul>
						<li><a href="/cgi-bin/admin/linux_client_choose_background_fm.cgi">'$CHOOSEBACKGROUND'</a></li>
						<li><a href="/cgi-bin/admin/linux_client_install_software.cgi">'$LINSTALLSOFTWARE'</a></li>
						<li><a href="/cgi-bin/admin/linux_client_view_install_list.cgi">'$LVIEWINSTALLSOFTWARE'</a></li>
						<li><a href="/cgi-bin/admin/linux_client_remove_software.cgi">'$LREMOVESOFTWARE'</a></li>
						<li><a href="/cgi-bin/admin/linux_client_view_remove_list.cgi">'$LVIEWREMOVESOFTWARE'</a></li>
						<li><a href="/cgi-bin/admin/linux_client_software_controls.cgi">'$LSOFTWARECONTROLS'</a></li>
						<li><a href="/cgi-bin/admin/linux_client_upload_skel_fm.cgi">'$UPLOADSKELARC'</a></li>
						<li><a href="/cgi-bin/admin/linux_client_download_skel.cgi">'$DOWNLOADSKELARC'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/windows_client_profile_upload_fm.cgi" class="fly">'$WINDOWSCLIENT'</a>
					<ul>
						<li><a href="/cgi-bin/admin/windows_client_profile_upload_fm.cgi">'$WUPLOADPROFILE'</a></li>
						<li><a href="/cgi-bin/admin/windows_client_icon_upload_fm.cgi">'$WUPLOADDESKTOPICONS'</a></li>
						<li><a href="/cgi-bin/admin/windows_client_startmenu_upload_fm.cgi">'$WUPLOADSTARTMENU'</a></li>
						<li><a href="/cgi-bin/admin/windows_client_background_upload_fm.cgi">'$WUPLOADBACKGROUND'</a></li>'

if [ $ADDUSERCTRL = yes ]
then
echo '						<li><a href="/cgi-bin/admin/windows_client_allow_roaming_profile_fm.cgi">'$WALLOWROAMINGPROFILE'</a></li>'
fi
echo '					</ul>
			</li>'
#echo '			<li class="mid"><a href="/cgi-bin/admin/generate_classroom_lists_csv_upload_fm.cgi" class="fly">'$CLASSROOMMANAGEMENT'</a>
#					<ul>
#						<li><a href="/cgi-bin/admin/generate_classroom_lists_csv_upload_fm.cgi">'$GENERATECSVMSG'</a></li>
#						<li><a href="/cgi-bin/admin/generate_classroom_lists_asset_register_fm.cgi">'$GENERATEASSETRESGMSG'</a></li>
#						<li><a href="/cgi-bin/admin/generate_classroom_lists_asset_register_fm.cgi">'$GENERATEKEYSMSG'</a></li>
#					</ul>
#			</li>
#			
#'
#Distribution server
if [ $DISTROCTRL = yes ]
then
echo '			<li class="mid"><a href="/cgi-bin/admin/linux_client_choose_distro_fm.cgi" class="fly">'$CHOOSECLIENTDISTRO'</a>
					<ul>
						<li><a href="/cgi-bin/admin/linux_client_choose_distro_fm.cgi">'$CHOOSECLIENTDISTRO'</a></li>
						<li><a href="/cgi-bin/admin/client_boot_controls_fm.cgi">'$CLIENTBOOTCONTROLS'</a></li>
					</ul>
			</li>'
fi
echo '			<li><a href="/cgi-bin/admin/client_shutdown_time.cgi">'$CSHUTDOWNTIME'</a></li>
			</ul>		
		</li>
'

#Printers
if [ $PRINTERCTRL = yes ]
then
echo '	<li class="top"><a href="/cgi-bin/admin/printers.cgi" id="Printer" class="top_link"><span class="down">'$PRINTERMSG'</span></a>
		<ul class="sub">
			<li><a href="/cgi-bin/admin/printers.cgi">'$VIEWQUEUES'</a></li>
			<li><a href="/cgi-bin/admin/printers_add_fm.cgi">'$ADDPRINTER'</a></li>
			<li><a href="/cgi-bin/admin/printers_delete.cgi">'$DELETEPRINTER'</a></li>
			<li><a href="/cgi-bin/admin/printers_view_assigned_fm.cgi">'$VIEWASSIGNEDPRINTERS'</a></li>


			<li class="mid"><a href="/cgi-bin/admin/printer_accounting_status_fm.cgi" class="fly">'$PRINTERACCOUNTING'</a>
					<ul>
					<li><a href="/cgi-bin/admin/printer_accounting_view_user_usage_fm.cgi">'$USERPRINTERUSAGE'</a></li>
					<li><a href="/cgi-bin/admin/printer_accounting_view_group_usage_fm.cgi">'$GROUPPRINTERUSAGE'</a></li>
					<li><a href="/cgi-bin/admin/printer_accounting_status_fm.cgi">'$ENABLEDPRINTERS'</a></li>
					<li><a href="/cgi-bin/admin/printer_accounting_add_user_limit_fm.cgi">'$ADDUSERPRINTERLIMIT'</a></li>
					<li><a href="/cgi-bin/admin/printer_accounting_user_limits_fm.cgi">'$USERPRINTERLIMITS'</a></li>
					<li><a href="/cgi-bin/admin/printer_accounting_group_limits_fm.cgi">'$ACCOUNTINGGROUPLIMITS'</a></li>
<li><a href="/cgi-bin/admin/printer_accounting_view_logs_fm.cgi">'$PRINTERLOGS'</a></li>
					<li><a href="/cgi-bin/admin/printer_accounting_clear_page_counts_fm.cgi">'$CLEARPAGECOUNTS'</a></li>
					</ul>
			</li>
			<li><a href="/cgi-bin/admin/printers_restart_samba_fm.cgi">'$RESTARTSAMBA'</a></li>
		</ul>
	</li>'
fi

#E-Mail
if [ $EMAILCTRL = yes ]
then
echo '	<li class="top"><a href="/cgi-bin/admin/email_add_alias_fm.cgi" id="E-Mail" class="top_link"><span class="down">'$EMAILMSG'</span></a>
		<ul class="sub">
			<li><a href="/cgi-bin/admin/email_add_alias_fm.cgi">'$ADDALIAS'</a></li>
			<li><a href="/cgi-bin/admin/email_view_aliases_fm.cgi">'$VIEWALIASES'</a></li>
			<li><a href="/cgi-bin/admin/email_relay.cgi">'$USERELAY'</a></li>
			<li><a href="/cgi-bin/admin/email_ban_domain_fm.cgi">'$BANEMAILDOMAIN'</a></li>
			<li><a href="/cgi-bin/admin/email_view_banned_domains_fm.cgi">'$VIEWBANNEDEMAILDOMAINS'</a></li>
			<li><a href="/cgi-bin/admin/email_access_fm.cgi">'$EMAILACCESS'</a></li>
			<li><a href="/cgi-bin/admin/email_limits.cgi">'$EMAILLIMITS'</a></li>
			<li><a href="/cgi-bin/admin/email_search_logs_fm.cgi">'$SEARCHLOGS'</a></li>
			<li><a href="/cgi-bin/admin/email_over_quota_report.cgi">'$OVERQUOTA'</a></li>
			<li><a href="/cgi-bin/admin/email_quota_settings.cgi">'$QWARNINGSETTINGS'</a></li>
			<li><a href="/cgi-bin/admin/email_quota_messages.cgi">'$QWARNINGMESSAGES'</a></li>
			<li><a href="/cgi-bin/admin/email_change_domain_ldap_fm.cgi">'$CHANGEDOMAIN'</a></li>
			<li><a href="/cgi-bin/admin/email_show_queue_fm.cgi">'$EMAILSHOWQUEUE'</a></li>
			<li><a href="/cgi-bin/admin/bulk_email_users_upload_fm.cgi">'$BULKEMAILUSERS'</a></li>
			<li><a href="/cgi-bin/admin/email_statistics_fm.cgi">'$EMAILSTATS'</a></li>
		</ul>
	</li>'
fi
#Internet

if [ $INTERNETCTRL = yes ] || [ $KSSOCTRL = yes ]
then
echo '	<li class="top"><a href="/cgi-bin/admin/activate_internet_changes_fm.cgi" id="Internet" class="top_link"><span class="down">Internet</span></a>
		<ul class="sub">'
fi

if [ $INTERNETCTRL = yes ]
then
echo '			<li class="mid"><a href="/cgi-bin/admin/dg_view_banned_users_fm.cgi" class="fly">'$VIEWMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/dg_view_banned_users_fm.cgi">'$VIEWBANNEDUSERS'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_allowed_sites_fm.cgi">'$VIEWALLOWEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_ssl_allowed_sites_fm.cgi">'$VIEWSSLALLOWEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_part_allowed_sites_fm.cgi">'$VIEWPALLOWEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_banned_sites_fm.cgi">'$VIEWBANNEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_part_banned_sites_fm.cgi">'$VIEWPBANNEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_wildcard_bans_fm.cgi">'$VIEWWCARDBANS'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_user_logs_fm.cgi">'$VIEWUSERLOGS'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_user_usage_fm.cgi">'$VIEWUSERUSAGE'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_global_usage_fm.cgi">'$VIEWINTERNETUSAGE'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_site_logs_fm.cgi">'$VIEWSITELOGS'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_computer_logs_fm.cgi">'$VIEWCOMPUTERLOGS'</a></li>
						<li><a href="/cgi-bin/admin/dg_view_top_sites_fm.cgi">'$VIEWTOPSITES'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/dg_banned_sites_fm.cgi" class="fly">'$BANMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/dg_ban_user.cgi">'$BANUSER'</a></li>
						<li><a href="/cgi-bin/admin/dg_banned_sites_fm.cgi">'$ADDBANNESITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_part_banned_sites_fm.cgi">'$ADDPBANNEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_wildcard_ban_fm.cgi">'$WCARDBAN'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/dg_allowed_sites_fm.cgi" class="fly">'$ALLOWMSG'</a>
					<ul>
						<li><a href="/cgi-bin/admin/dg_allowed_sites_fm.cgi">'$ADDALLOWEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_ssl_allowed_sites_fm.cgi">'$ADDSSLALLOWEDSITES'</a></li>
						<li><a href="/cgi-bin/admin/dg_part_allowed_sites_fm.cgi">'$ADDPALLOWEDSITES'</a></li>
					</ul>
			</li>
			<li class="mid"><a href="/cgi-bin/admin/dg_upload_pbl_fm.cgi" class="fly">'$PROXYBYPASSLIST'</a>
					<ul>
						<li><a href="/cgi-bin/admin/dg_add_pbl_fm.cgi">'$ADDPROXYBYPASS'</a></li>
						<li><a href="/cgi-bin/admin/dg_upload_pbl_fm.cgi">'$UPLOADPROXYBYPASSLIST'</a></li>
						<li><a href="/cgi-bin/admin/dg_download_pbl_fm.cgi">'$DOWNLOADPROXYBYPASSLIST'</a></li>
						<li><a href="/cgi-bin/admin/dg_clear_pbl_fm.cgi">'$CLEARPROXYBYPASSLIST'</a></li>
					</ul>
			</li>
			<li><a href="/cgi-bin/admin/dg_extensions_fm.cgi">'$ALLOWEDFILEEXTENSIONS'</a></li>
			<li><a href="/cgi-bin/admin/dg_media_controls_fm.cgi">'$MEDIACONTROLS'</a></li>
			<li><a href="/cgi-bin/admin/dg_staff_filters_fm.cgi">'$STAFFFILTERS'</a></li>
			<li><a href="/cgi-bin/admin/dg_room_controls_fm.cgi">'$ROOMCONTROLS'</a></li>
			<li><a href="/cgi-bin/admin/dg_reset_room_controls_fm.cgi">'$RESETROOMCONTROLS'</a></li>
			<li><a href="/cgi-bin/admin/activate_internet_changes_fm.cgi">'$ACTIVATECHANGES'</a></li>'
fi

if [ $KSSOCTRL = yes ]
then
echo '			<li class="mid"><a href="/cgi-bin/admin/ksso_add1_fm.cgi" class="fly">'$KSSO'</a>
					<ul>
						<li><a href="/cgi-bin/admin/ksso_add1_fm.cgi">'$KSSOADD'</a></li>
						<li><a href="/cgi-bin/admin/ksso_view_fm.cgi">'$KSSOVIEW'</a></li>
						<li><a href="/cgi-bin/admin/ksso_icon_upload_fm.cgi">'$KSSOUPLOAD'</a></li>
						<li><a href="/cgi-bin/admin/ksso_view_icons_fm.cgi">'$KSSOVIEWICONS'</a></li>
					</ul>
			</li>
'
fi

if [ $INTERNETCTRL = yes ] || [ $KSSOCTRL = yes ]
then
echo '	</ul>'
fi

#Web
if [ $WEBCTRL = yes ]
then
echo '	<li class="top"><a href="#nogo53" id="Web" class="top_link"><span class="down">Web</span></a>
		<ul class="sub">
			<li><a href="/cgi-bin/admin/web_management_upload_files_fm.cgi">'$UPLOADFILES'</a></li>
			<li><a href="/cgi-bin/admin/web_management_view_files_choose_server_fm.cgi">'$VIEWDELETEFILES'</a></li>
			<li><a href="/cgi-bin/admin/web_management_create_folder_fm.cgi">'$CREATEFOLDER'</a></li>
			<li><a href="/cgi-bin/admin/web_management_delete_folder_choose_server_fm.cgi">'$DELETEFOLDER'</a></li>
			<li><a href="/cgi-bin/admin/set_domains_fm.cgi">'$SETDOMAIN'</a></li>'

if [ $REVERSEPROXYCTRL = yes ]
then
echo '			<li><a href="/cgi-bin/admin/reverse_proxy_add_fm.cgi">'$RPROXYADD'</a></li>
			<li><a href="/cgi-bin/admin/reverse_proxy_view_fm.cgi">'$RPROXYVIEW'</a></li>'
fi
echo '		</ul>
	</li>'
fi
echo '</ul></div>'
exit
