#!/bin/bash
#Generate md5 sums for karoshi cgi scripts
[ -d /opt/karoshi/web_controls/checksums ] && rm -f -R /opt/karoshi/web_controls/checksums
mkdir /opt/karoshi/web_controls/checksums
mkdir /opt/karoshi/web_controls/checksums/admin_checksums /opt/karoshi/web_controls/checksums/tech_checksums /opt/karoshi/web_controls/checksums/staff_checksums /opt/karoshi/web_controls/checksums/all_checksums
chmod 0600 -R /opt/karoshi/web_controls/checksums
chmod u+X -R /opt/karoshi/web_controls/checksums
chown root.root -R /opt/karoshi/web_controls/checksums

function CreateRandomString {
RandomString=$(openssl rand -base64 32)
}

function AppendRandomString
{
	CreateRandomString
	echo -e "\n########################\n#Random Key\n#$RandomString\n########################" >> "$CGIScript"
}

function WriteChecksums {
for CGIScript in /var/www/cgi-bin_karoshi/"$ScriptFolder"/*;
do
	AppendRandomString
	Scriptname=$(basename "$CGIScript" | sed 's/\./_/g' | sed 's/ /_/g')
	Checksum=$(sha256sum "$CGIScript" | cut -d' ' -f1)
	echo "$Scriptname=$Checksum" > /opt/karoshi/web_controls/checksums/"$ScriptFolder""_checksums/$Scriptname"
	chmod 0400 /opt/karoshi/web_controls/checksums/"$ScriptFolder""_checksums/$Scriptname"
done
}

ScriptFolder=admin
WriteChecksums

ScriptFolder=tech
WriteChecksums

ScriptFolder=staff
WriteChecksums

ScriptFolder=all
WriteChecksums

