#!/bin/bash
if [ -d /opt/karoshi/server_network/zones/internal/additional_domain_controllers ]
then
if [ `ls -1 /opt/karoshi/server_network/zones/internal/additional_domain_controllers | wc -l` -gt 0 ]
then
for ADSERVERS in /opt/karoshi/server_network/zones/internal/additional_domain_controllers/*
do
ADSERVER=`basename $ADSERVERS`
echo Syncing $ADSERVER
#Sync netlogon
rsync --timeout=30 --verbose --dirs --recursive --links --compress /var/lib/samba/netlogon $ADSERVER:/var/lib/samba/
#Sync applications share
rsync --timeout=30 --verbose --dirs --recursive --links --compress /home/applications $ADSERVER:/home/
#Sync subjects
rsync --timeout=30 --verbose --dirs --recursive --links --compress /home/subjects $ADSERVER:/home/
#Sync staffshare
rsync --timeout=30 --verbose --dirs --recursive --links --compress /home/staffshare $ADSERVER:/home/
#Sync users home areas
rsync --timeout=30 --verbose --dirs --recursive --links --compress /home/users/ $ADSERVER:/home/
done
fi
fi

#Make sure this script is scheduled to run
echo '*''/'30 '*' '*' '*' 1-5 /opt/karoshi/'"'useful scripts'"'/adc_sync > /opt/karoshi/cronjobs/jobs/adcsync.cron
/opt/karoshi/serversetup/all/"useful scripts"/refreshcronjobs
