#!/bin/bash
#Force youtube to use safesearch - this will create bing dns zones and redirect to strict.bing.com

#User action - add / delete
Action=$(tr -cd "[:lower:]" <<< "$1")

#Get the ip address for forcesafesearch
BingSafesearchIP=$(tr -cd "0-9." <<< "$2")
[[ -z "$BingSafesearchIP" ]] && BingSafesearchIP=204.79.197.220

if [[ ! "$Action" == "add" ]] && [[ ! "$Action" == "delete" ]]
then
	echo -e "\nUsage: bingsafesearch add,delete safeip(optional)\n\nadd - add dns zones to force bingsafesearch.\ndelete - delete any google dns zones that have been added by this script.\n\nsafeip - this is the tcpip address for strict.bing.com.\n"
fi

#List of google zones to add to samba4 dns
BingZones="bing.com"

LdapPass=$(sed -n 1,1p /etc/ldap.secret)
RestartSamba=no
BingDnsZones=$(samba-tool dns zonelist 127.0.0.1 --username=Administrator --password="$LdapPass" | grep bing)


for BingZone in $BingZones
do
	if [[ "$Action" == add ]]
	then
		#Create dns zones
		if [[ $(grep -c -w "$BingZone" <<< $BingDnsZones) = 0 ]]
		then
			RestartSamba=yes
			echo Creating "$BingZone"
			samba-tool dns zonecreate 127.0.0.1 "$BingZone" --username=Administrator --password="$LdapPass"
			#Add in cname entry
			samba-tool dns add 127.0.0.1 www."$BingZone" www."$BingZone" CNAME strict.bing.com --username=Administrator --password="$LdapPass" 1>/dev/null
			#Add in dns record for restrict.youtube.com
			samba-tool dns add 127.0.0.1 "$BingZone" www."$BingZone" A "$BingSafesearchIP" --username=Administrator --password="$LdapPass" 1>/dev/null
		fi
	fi

	if [[ "$Action" == delete ]]
	then
		#Remove dns zone if it exists
		if [[ $(grep -c -w "$BingZone" <<< $BingDnsZones) -gt 0 ]]
		then
			RestartSamba=yes
			echo Deleting "$BingZone"
			samba-tool dns zonedelete 127.0.0.1 "$BingZone" --username=Administrator --password="$LdapPass"
		fi
	fi
done

#Restart samba4 to activate any zones that have been added or deleted.
if [[ "$RestartSamba" == yes ]] && [[ $(grep -c "server services = -dns" /etc/samba/smb.conf) == 0 ]]
then
	service samba4 stop
	service samba4 start
fi
exit
