#!/bin/bash

REALM=internal
[  -f /opt/karoshi/server_network/domain_information/domain_name ] && source /opt/karoshi/server_network/domain_information/domain_name


#Check for dfs support
DFS=no
[ `grep -c "host msdfs = yes" /etc/samba/smb.conf` -gt 0 ] && DFS=yes


#Add in drive mount options
function get_pri_group_number {
PRIGROUPNUM=`getent group $PRI_GROUP | cut -d: -f3`
}

###########################
#Create /var/lib/samba/netlogon/linuxclient/$FILENAME
###########################

function create_file {
#Create header
[ ! -d /var/lib/samba/netlogon/linuxclient ] && mkdir -p /var/lib/samba/netlogon/linuxclient
cat /opt/karoshi/serversetup/pdc/linuxclient/pam_mount/pam_mount_header_xml > /var/lib/samba/netlogon/linuxclient/$FILENAME
if [ "$DFS" = yes ]
then
	#Subjects
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/subjects" path="dfs/subjects" server="'$REALM'" uid="1000-5000000" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

	#Itadmin share
	PRI_GROUP=itadmin
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/itadmin" path="dfs/itadmin" server="'$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

	#Staffshare
	PRI_GROUP=staff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="dfs/staffshare" server="'$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
	PRI_GROUP=officestaff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="dfs/staffshare" server="'$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
	PRI_GROUP=itadmin
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="dfs/staffshare" server="'$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
	PRI_GROUP=studentstaff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="dfs/staffshare" server="'$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

	#Officeshare
	PRI_GROUP=officestaff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/officeshare" path="dfs/officeshare" server="'$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

	#Home share
	echo '<volume options="sec=krb5,cruid=%(USERUID),dir_mode=0700" mountpoint="~/network/home" path="dfs/homes/%(USER)" server="'$REALM'" gid="1103" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

else
	#Subjects
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/subjects" path="subjects" server="'$HOSTNAME.$REALM'" uid="1000-5000000" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

	#Itadmin share
	PRI_GROUP=itadmin
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/itadmin" path="itadmin" server="'$HOSTNAME.$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

	#Staffshare
	PRI_GROUP=staff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="staffshare" server="'$HOSTNAME.$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
	PRI_GROUP=officestaff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="staffshare" server="'$HOSTNAME.$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
	PRI_GROUP=itadmin
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="staffshare" server="'$HOSTNAME.$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
	PRI_GROUP=studentstaff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/staffshare" path="staffshare" server="'$HOSTNAME.$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME

	#Officeshare
	PRI_GROUP=officestaff
	get_pri_group_number
	echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/officeshare" path="officeshare" server="'$HOSTNAME.$REALM'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
	#Home shares
	for PRI_GROUPS in /opt/karoshi/server_network/group_information/*
	do
		PRI_GROUP=`basename $PRI_GROUPS`
		if [ $PRI_GROUP != optional_groups ]
		then
			source /opt/karoshi/server_network/group_information/$PRI_GROUP
			get_pri_group_number
			echo '<volume options="'$OPTIONS',dir_mode=0700" mountpoint="~/network/home" path="%(USER)" server="'$SERVER'" gid="'$PRIGROUPNUM'" fstype="cifs" />' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
		fi
	done
fi
echo -e '\n</pam_mount>' >> /var/lib/samba/netlogon/linuxclient/$FILENAME
}

SAMBAVER=samba
OPTIONS="sec=ntlmv2"
FILENAME=pam_mount.conf.xml

#Create standard file
create_file
#Create extra file for kerberos enabled clients and samba4 server
OPTIONS="sec=krb5,cruid=%(USERUID)"
FILENAME=pam_mount.conf.xml.krb5
create_file

#Create mount information for owncloud

if [ -f /opt/karoshi/server_network/owncloudserver ]
then
OWNCLOUDSERVER=`sed -n 1,1p /opt/karoshi/server_network/owncloudserver`
[ ! -d /home/owncloud/data ] && mkdir -p /home/owncloud/data

MAINSERVER=`hostname-fqdn`
#Groups
MAPEXTRASHARES=no
echo '{
"group":{' > /home/owncloud/data/mount.json

#Staff info
source /opt/karoshi/server_network/group_information/staff
echo '
	"staff":{
		"\/$user\/files\/home":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$SERVER'","username_as_share":"true","share":"","root":""
			}
		} ' >> /home/owncloud/data/mount.json

if [ $MAPEXTRASHARES = yes ]
then
echo '		,"\/$user\/files\/staffshare":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$MAINSERVER'","username_as_share":"false","share":"staffshare","root":""
			}
		}' >> /home/owncloud/data/mount.json
fi
echo '	},' >> /home/owncloud/data/mount.json


#Itadmin info
source /opt/karoshi/server_network/group_information/itadmin
echo '	"itadmin":{
		"\/$user\/files\/home":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$SERVER'","username_as_share":"true","share":"","root":""
			}
		}' >> /home/owncloud/data/mount.json
if [ $MAPEXTRASHARES = yes ]
then
echo '		,"\/$user\/files\/itadmin":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$MAINSERVER'","username_as_share":"false","share":"itadmin","root":""
			}
		}' >> /home/owncloud/data/mount.json
fi
echo '	},' >> /home/owncloud/data/mount.json


#Officestaff
source /opt/karoshi/server_network/group_information/officestaff
echo '	"officestaff":{
		"\/$user\/files\/home":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$SERVER'","username_as_share":"true","share":"","root":""
			}
		}' >> /home/owncloud/data/mount.json
if [ $MAPEXTRASHARES = yes ]
then
echo '		,"\/$user\/files\/officeshare":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$MAINSERVER'","username_as_share":"false","share":"officeshare","root":""
			}
		}' >> /home/owncloud/data/mount.json
fi
echo '	},' >> /home/owncloud/data/mount.json

#Home shares
COMMA=""
for PRI_GROUPS in /opt/karoshi/server_network/group_information/*
do
PRI_GROUP=`basename $PRI_GROUPS`
if [ $PRI_GROUP != itadmin ] && [ $PRI_GROUP != staff ] && [ $PRI_GROUP != officestaff ]
then
source /opt/karoshi/server_network/group_information/$PRI_GROUP
echo '	'$COMMA'"'$PRI_GROUP'":{
		"\/$user\/files\/home":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$SERVER'","username_as_share":"true","share":"","root":""
			}
		}
	}' >> /home/owncloud/data/mount.json
COMMA=","
fi
done
echo '
}
'  >> /home/owncloud/data/mount.json

#Subjects
if [ $MAPEXTRASHARES = yes ]
then
echo ',"user":{
	"all":{
		"\/$user\/files\/subjects":{
			"class":"\\OC\\Files\\Storage\\SMB_OC","options":{
				"host":"'$MAINSERVER'","username_as_share":"false","share":"subjects","root":""
			}
		}
	}
}' >> /home/owncloud/data/mount.json
fi
echo '}' >> /home/owncloud/data/mount.json

chown www-data:www-data /home/owncloud/data/mount.json
chmod 0640 /home/owncloud/data/mount.json

if [ $OWNCLOUDSERVER != `hostname-fqdn` ]
then
scp -p -o PasswordAuthentication=no /home/owncloud/data/mount.json $OWNCLOUDSERVER:/home/owncloud/data/
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $OWNCLOUDSERVER '
chown www-data /home/owncloud/data/mount.json
'
fi
fi

