#!/bin/bash
[ ! -d /opt/karoshi/server_network/mac_addresses ] && mkdir -p /opt/karoshi/server_network/mac_addresses

source /opt/karoshi/serversetup/variables/network_card_info

TCPIPNUMBER=`ifconfig $NETWORK_INT | grep "inet addr" | sed "s/ * / /g" | cut -d" " -f3 | cut -d: -f2`
MAC_ADDRESS=`ip addr | grep -B1 $TCPIPNUMBER | sed -n 1p | sed "s/ * / /g" | cut -d" " -f3`

if [ ! -z $MAC_ADDRESS ] && [ ! -z $TCPIPNUMBER ]
then
echo $MAC_ADDRESS $TCPIPNUMBER > /opt/karoshi/server_network/mac_addresses/$HOSTNAME
cat /opt/karoshi/server_network/mac_addresses/* > /var/lib/samba/netlogon/domain_information/static_arps
fi
