#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
#####################
#Get location to wake up
#####################
LOCATION=`echo $* | cut -s -d: -f1 | tr -cd 'A-Za-z0-9\._:\-'`
if [ -z "$LOCATION" ]
then
	echo `date`: wol - Called with no location. >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit
fi
#####################
#Check that location exists in asset register
#####################
if [ ! -d /opt/karoshi/asset_register/locations/$LOCATION ]
then
	echo `date`: wol - $LOCATION does not exist in the asset register. >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 102
fi
#####################
#Log folder
#####################
if [ ! -d /opt/karoshi/logs/wake_on_lan/$LOCATION ]
then
	mkdir -p /opt/karoshi/logs/wake_on_lan/$LOCATION
	chmod 0700 /opt/karoshi/logs/wake_on_lan
	chmod 0700 /opt/karoshi/logs/wake_on_lan/$LOCATION
fi
touch /opt/karoshi/logs/wake_on_lan/$LOCATION/$LOG_DATE
chmod 0600 /opt/karoshi/logs/wake_on_lan/$LOCATION/$LOG_DATE
#####################
#Check that location is enabled
#####################
if [ -f /opt/karoshi/server_network/cronjobs/`hostname-fqdn`/wake_on_lan_status/$LOCATION ]
then
	echo `date`: wol - $LOCATION is disabled "for" wake on lan.  >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit
fi
#####################
#Wake up any assets with mac addresses
#####################
echo `date`: wol - Waking up $LOCATION.  >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

if [ -d /opt/karoshi/asset_register/locations/"$LOCATION" ]
then
	if [ `ls -1 /opt/karoshi/asset_register/locations/"$LOCATION" | wc -l` -gt 0 ]
	then
		for ASSETS in /opt/karoshi/asset_register/locations/"$LOCATION"/*
		do
			ASSET=`basename $ASSETS`
			MAC1=""
			MAC2=""
			MAC3=""
			source /opt/karoshi/asset_register/locations/"$LOCATION"/$ASSET
			if [ ! -z "$MAC1" ] && [ $MAC1 != N.A. ]
			then
				echo $"Waking" "$MAC1"
				wakeonlan "$MAC1" 1>/dev/null
				sleep 1.5
			fi
			if [ ! -z "$MAC2" ] && [ $MAC2 != N.A. ]
			then
				echo $"Waking" "$MAC2"
				wakeonlan "$MAC2" 1>/dev/null
				sleep 1.5
			fi
			if [ ! -z "$MAC3" ] && [ $MAC3 != N.A. ]
			then
				echo $"Waking" "$MAC3"
				wakeonlan "$MAC3" 1>/dev/null
				sleep 1.5
			fi
		done
	fi
fi

exit
