#!/bin/bash
#Force youtube to use safesearch - this will create google dns zones and redirect to restrict.youtube.com

#User action - add / delete
ACTION=$(tr -cd "a-z" <<< "$1")

#Get the ip address for forcesafesearch.google.com
YOUTUBESAFEIP=$(tr -cd "0-9." <<< "$2")
[[ -z "$YOUTUBESAFEIP" ]] && YOUTUBESAFEIP=216.239.38.120

if [[ ! "$ACTION" == "add" ]] && [[ ! "$ACTION" == "delete" ]]
then
	echo -e "\nUsage: youtubesafesearch add,delete safeip(optional)\n\nadd - add dns zones to force youtubesafesearch.\ndelete - delete any google dns zones that have been added by this script.\n\nsafeip - this is the tcpip address for forcesafesearch.youtube.com.\n"
fi

#List of google zones to add to samba4 dns
YOUTUBEZONES="youtube.com youtube.be m.youtube.com youtubei.googleapis.com youtube.googleapis.com www.youtube-nocookie.com"

LDAPPASS=$(sed -n 1,1p /etc/ldap.secret)
RESTARTSAMBA=no
GOOGLEINFO=$(samba-tool dns zonelist 127.0.0.1 --username=Administrator --password="$LDAPPASS" | grep youtube)



for YOUTUBEZONE in $YOUTUBEZONES
do
	if [[ "$ACTION" == add ]]
	then
		#Create dns zones
		if [[ $(grep -c -w "$YOUTUBEZONE" <<< "$GOOGLEINFO") = 0 ]]
		then
			RESTARTSAMBA=yes
			echo Creating "$YOUTUBEZONE"
			samba-tool dns zonecreate 127.0.0.1 "$YOUTUBEZONE" --username=Administrator --password="$LDAPPASS"
			#Add in cname entry
			samba-tool dns add 127.0.0.1 www."$YOUTUBEZONE" restrict.youtube.com.www."$YOUTUBEZONE" CNAME restrict.youtube.com --username=Administrator --password="$LDAPPASS" 1>/dev/null
			#Add in dns record for restrict.youtube.com
			samba-tool dns add 127.0.0.1 www."$YOUTUBEZONE" www."$YOUTUBEZONE" A "$YOUTUBESAFEIP" --username=Administrator --password="$LDAPPASS" 1>/dev/null
		fi
	fi

	if [[ "$ACTION" == delete ]]
	then
		#Remove dns zone if it exists
		if [[ $(grep -c -w www."$YOUTUBEZONE" <<< "$GOOGLEINFO") -gt 0 ]]
		then
			RESTARTSAMBA=yes
			echo Deleting www."$YOUTUBEZONE"
			samba-tool dns zonedelete 127.0.0.1 www."$YOUTUBEZONE" --username=Administrator --password="$LDAPPASS"
		fi
	fi
done

#Restart samba4 to activate any zones that have been added or deleted.
if [[ "$RESTARTSAMBA" == yes ]] && [[ $(grep -c "server services = -dns" /etc/samba/smb.conf) == 0 ]]
then
	service samba4 stop
	service samba4 start
fi
exit
