#!/bin/bash
#Stop avahi on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
	/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status avahi-daemon off 1>/dev/null 2>/dev/null
else
	chkconfig -f avahi-daemon off 1>/dev/null 2>/dev/null
fi

