#!/bin/bash
#Stop karoshi-uptime on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status karoshi-uptime off 1>/dev/null 2>/dev/null
else
chkconfig -f karoshi-uptime off 1>/dev/null 2>/dev/null
fi

