#!/bin/bash
#Stop mon on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status mon off 1>/dev/null 2>/dev/null
else
chkconfig -f mon off 1>/dev/null 2>/dev/null
fi

