#!/bin/bash
#Stop postfix on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status postfix off 1>/dev/null 2>/dev/null
else
chkconfig -f postfix off 1>/dev/null 2>/dev/null
fi

