#!/bin/bash
#Stop cups on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status freeradius off 1>/dev/null 2>/dev/null
else
chkconfig -f freeradius off 1>/dev/null 2>/dev/null
fi

