#!/bin/bash
#Stop squid on boot

#Check which init.d script to use
if [ -f /etc/init.d/squid3 ]
then
	SQUIDVER=squid3
else
	SQUIDVER=squid
fi

if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
	/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status $SQUIDVER off 1>/dev/null 2>/dev/null
else
	chkconfig -f $SQUIDVER off 1>/dev/null 2>/dev/null
fi

