#!/bin/bash
#Copyright (C) 2007  The karoshi Team
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit
########################
#Check md5checksum
########################
EDITTITLE="Edit Remote Administration Access"
NO_TCPIP_RESTRICTIONS="There are no tcpip restrictions in place."
LOCKCOMMENT="Added to prevent this computer from being locked out."
VIEWMSG="Viewing the allowed TCPIP list for levels 1 and 2."
VIEWMSG2="Viewing the allowed TCPIP list for level 3."
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_restrict_cgi
then
echo `date`: remote_management_restrict - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_restrict2_cgi
then
echo `date`: remote_management_restrict - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_restrict3_cgi
then
echo `date`: remote_management_restrict - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_restrict_cgi
source /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_restrict2_cgi
source /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_restrict3_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/remote_management_restrict.cgi | cut -d' ' -f1`
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/admin/remote_management_restrict2.cgi | cut -d' ' -f1`
MD5SUM3=`md5sum /var/www/cgi-bin_karoshi/admin/remote_management_restrict3.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
[ $MD5SUM3'null' = null ] && MD5SUM3=not_set
if [ $MD5SUM'check' != $remote_management_restrict_cgi'check' ] || [ $MD5SUM2'check' != $remote_management_restrict2_cgi'check' ] || [ $MD5SUM3'check' != $remote_management_restrict3_cgi'check' ]
then
echo `date`: remote_management_restrict - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: remote_management_restrict - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
ACTION=`echo $* | cut -s -d: -f4`
TCPADDRESS=`echo $* | cut -s -d: -f5`
TCPCOMMENT=`echo $* | cut -s -d: -f6 | sed 's/+/ /g'`
ADMINLEVEL=`echo $* | cut -s -d: -f7`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ] && [ $REMOTE_MD5'check' != $MD5SUM3'check' ]
then
echo `date`: remote_management_restrict - Not called by remote_management_restrict.cgi or remote_management_restrict2.cgi or remote_management_restrict3.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: remote_management_restrict - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: remote_management_restrict - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi
if [ $ACTION'null' = null ]
then
echo `date`: remote_management_restrict - Blank action by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi

if [ $ACTION != add ] && [ $ACTION != remove ] && [ $ACTION != view ] && [ $ACTION != edit ]
then
echo `date`: remote_management_restrict - Incorrect action by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi
if [ $ACTION = add ] || [ $ACTION = remove ] || [ $ACTION = edit ]
then
if [ $TCPADDRESS'null' = null ]
then
echo `date`: remote_management_restrict - Blank tcpip address by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi
if [ $ADMINLEVEL'null' = null ] && [ $ACTION != remove ]
then
echo `date`: remote_management_restrict - Blank admin level by $REMOTE_USER with action $ACTION from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/remote_management_users` != 1 ]
then
echo `date`: remote_management_restrict - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
fi
echo `date`: remote_management_restrict - disabled in demo mode for $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 100
