#!/bin/bash
#Start squid on boot
if [ -f /opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status ]
then
/opt/karoshi/serversetup/distro/ubuntu/scripts/set_boot_status uptimed on 1>/dev/null 2>/dev/null
else
chkconfig -f uptimed on 1>/dev/null 2>/dev/null
fi

