#!/bin/bash
#serverselection
#Copyright (C) 2005 The karoshi Team
#
#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk
#aloughlin@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
source /opt/karoshi/serversetup/variables/version
[ -d /opt/karoshi/.tempdata ] || mkdir /opt/karoshi/.tempdata
source /opt/karoshi/serversetup/variables/distro

TEXTDOMAIN=karoshi-server
locale 1>/dev/null

#############################
#check to see if root user
#############################
USERSTATUS=`id -u`
if [ $USERSTATUS != 0 ]
then
	konsole -e sh /opt/karoshi/serversetup/essentials/rootwarningserversetup
	exit
fi

#############################
#Check to see if the distro has been installed
#############################
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/install_distro
#Exit if this was running live
[ `echo $?` = 101 ] && exit

############################
#View the full agreement
############################
yad --title ''$"Linux Schools Server Setup"' '$VERSION'' --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --text '\n'$"The Linux Schools Server Project comes with ABSOLUTELY NO WARRANTY. This is free software, and you are welcome to redistribute it under certain conditions."'\n\n\n' --text-info --show-uri --geometry=650x700 --name="notes" --filename="/opt/karoshi/serversetup/AGPLv3" --title=$"Confirm Licence" --generic --button=''$"Disagree"':1' --button=''$"Agree"':0' 2>/dev/null
STATUS=`echo $?`
[ $STATUS = 0 ] && LICENCE=yes
[ $STATUS = 1 ] && LICENCE=no

if [ $LICENCE = yes ]
then
	ACCEPTDATE=`date`
	echo GPL_Karoshi_Licence_Accepted > /opt/karoshi/serversetup/variables/acceptlicence
	echo $ACCEPTDATE >> /opt/karoshi/serversetup/variables/acceptlicence
else
	yad --title ''$"Linux Schools Server Setup"' '$VERSION'' --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --text=$"The Linux Schools Server Setup has been cancelled." --timeout=3 --no-buttons 2>/dev/null
	exit
fi

while [ -z "$CHOICE" ]
do

yad --title $"Linux Schools Server Setup" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --width 400 --height 180 \
   --button=''$"Setup the main server"':2'  --button=''$"Setup an extra server"':1' --text $"Choose the type of server you want to install."
CHOICE="$?"
done

#Setup cronjobs common to all servers
[ ! -d /opt/karoshi/server_network/cronjobs/`hostname-fqdn`/jobs ] && mkdir -p /opt/karoshi/server_network/cronjobs/`hostname-fqdn`/jobs

if [ "$CHOICE" = 2 ]
then
	#Ask if this is server installation is for education or business use.
	yad --title $"Linux Schools Server Setup" --image="/opt/karoshi/serversetup/essentials/smalllogo.png" --window-icon="/opt/karoshi/serversetup/essentials/smalllogo.png" --width 400 --height 180 \
   	--button=''$"Education"':1'  --button=''$"Business"':2' --button=''$"Restore"':3' --text $"Choose the server install version.""\n\n<span font_weight='bold' foreground='blue'>"$"Education""</span>: "$"Installs with student year groups.""\n\n<span font_weight='bold' foreground='blue'>"$"Business""</span>: "$"Installs without student year groups.""\n\n<span font_weight='bold' foreground='purple'>"$"Restore""</span>: "$"Join this server to an existing additional Karoshi Server that is a domain controller."
	SCHOICE="$?"

	[ $SCHOICE = 1 ] && INSTALL_TYPE=education
	[ $SCHOICE = 2 ] && INSTALL_TYPE=business
	[ $SCHOICE = 3 ] && INSTALL_TYPE=restore
	
	[ ! -d /opt/karoshi/server_network ] && mkdir /opt/karoshi/server_network

	echo $INSTALL_TYPE > /opt/karoshi/server_network/install_type
	
	#Run pdc standard setup
	/opt/karoshi/serversetup/pdc/scripts/standardsetup 
fi

[ "$CHOICE" = 1 ] && /opt/karoshi/serversetup/extra_server/scripts/standardsetup

exit
