#!/bin/bash
LogDate=$(date +%F)

User="root"
MysqlRootPass=$(cat /etc/mysql.secret)
BackupPath=/var/lib/mysql_backup

#Make log folder
[ ! -d "/opt/karoshi/logs/backup_servers/$LogDate" ] && mkdir -p "/opt/karoshi/logs/backup_servers/$LogDate"

#Check if mysql is running
/opt/karoshi/serversetup/distro/ubuntu/scripts/control_services/mysql_status
if [ "$?" != 0 ]
then
	#mysql / mariadb is not running
	echo "$(date): mysql_backup - mysql / mariadb is not running - the databases will not be backed up." | tee -a "/opt/karoshi/logs/backup_servers/$LogDate/backup_log_summary"
	exit
fi

#Check that we can connect to mysql / mariadb with the supplied Username and MysqlRootPass
#mysqladmin --password="$MysqlRootPass" version 1>/dev/null
sshpass -p "$MysqlRootPass" mysqladmin -p version 1>/dev/null

if [ "$?" != 0 ]
then
	#Cannot connect to mysql / mariadb
	echo "$(date): mysql_backup - cannot connect to mysql / mariadb - the databases will not be backed up."  | tee -a "/opt/karoshi/logs/backup_servers/$LogDate/backup_log_summary"
	exit
fi

#Create a backup folder for the mysql databases
if [ ! -d "$BackupPath" ]
then
	echo "$(date): mysql_backup - creating $BackupPath as a backup folder."  | tee -a "/opt/karoshi/logs/backup_servers/$LogDate/backup_log_summary"
	mkdir -p "$BackupPath"
	chmod 0700 "$BackupPath"
fi

databases=$(sshpass -p "$MysqlRootPass" mysql -u "$User" -p -e "SHOW DATABASES;" | tr -d "| " | grep -v Database)
for db in $databases; do
    if [[ "$db" != "information_schema" ]] && [[ "$db" != "performance_schema" ]] && [[ "$db" != "mysql" ]] && [[ "$db" != _* ]] ; then
	echo "$(date): mysql_backup - dumping $db to $BackupPath" | tee -a "/opt/karoshi/logs/backup_servers/$LogDate/backup_log_summary"
        sshpass -p "$MysqlRootPass" mysqldump -u "$User" -p --databases "$db" > "$BackupPath/$db.sql"
    fi
done
exit
