#!/bin/bash
#Copyright (C) 2007  The karoshi Team

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/client_shutdown_time2_cgi
then
echo `date`: client_shutdown_time - No Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/client_shutdown_time2_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/admin/client_shutdown_time2.cgi | cut -d' ' -f1`
[ $Checksum'null' = null ] && Checksum=not_set
if [ $Checksum'check' != $client_shutdown_time2_cgi'check' ]
then
echo `date`: client_shutdown_time - Incorrect Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

#########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: client_shutdown_time - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1 | tr -cd 'A-Za-z0-9\._:\-'`
REMOTE_ADDR=`echo $* | cut -s -d: -f2 | tr -cd 'A-Za-z0-9\._:\-'`
RemoteCheckSum=`echo $* | cut -s -d: -f3 | tr -cd 'A-Za-z0-9\._:\-'`
HOUR=`echo $* | cut -s -d: -f4 | tr -cd 'A-Za-z0-9\._:\-'`
MINUTES=`echo $* | cut -s -d: -f5 | tr -cd 'A-Za-z0-9\._:\-'`
IDLETIME=`echo $* | cut -s -d: -f6 | tr -cd 'A-Za-z0-9\._:\-'`
########################
#Check data
########################
if [ $RemoteCheckSum'check' != $Checksum'check' ]
then
echo `date`: client_shutdown_time - Not called by client_shutdown_time.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: client_shutdown_time - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: client_shutdown_time - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $HOUR'null' = null ]
then
echo `date`: client_shutdown_time - Blank hour by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $MINUTES'null' = null ]
then
echo `date`: client_shutdown_time - Blank minutes by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ $IDLETIME'null' = null ]
then
echo `date`: client_shutdown_time - Blank idle time by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: client_shutdown_time - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
echo `date`: client_shutdown_time - changing shutdown time to $HOUR:$MINUTES by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
[ ! -d /var/lib/samba/netlogon/domain_information ] && mkdir -p /var/lib/samba/netlogon/domain_information
echo $HOUR:$MINUTES:00 > /var/lib/samba/netlogon/domain_information/clientshutdowntime
echo $IDLETIME > /var/lib/samba/netlogon/domain_information/idletime
chmod 0644 /var/lib/samba/netlogon/domain_information/clientshutdowntime
chmod 0644 /var/lib/samba/netlogon/domain_information/idletime
exit


