#!/bin/bash
#Copyright (C) 2012 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`

echo `date`: dg_reset_rooms - flushing iptables dynamic ruleset on $PROXYSERVER >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE


#Clear all of the room control flags
[ -d /opt/karoshi/server_network/internet_room_controls/ ] && rm -f -R /opt/karoshi/server_network/internet_room_controls/ 

function clear_rules {
#Clear iptables rules
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	iptables --flush dynamic
else
	ssh -o PasswordAuthentication=no -o ConnectTimeout=3  $PROXYSERVER '
	iptables --flush dynamic
	'
fi
}

PROXYSERVER=`sed -n 1,1p /opt/karoshi/server_network/proxyserver`
if [ -d /opt/karoshi/server_network/proxyservers/ ]
then
	for PROXYSERVER in `ls -1 /opt/karoshi/server_network/proxyservers`
	do
		clear_rules
	done
else 
	clear_rules
fi

exit

