#!/bin/bash
#Copyright (C) 2011 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit

########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/dg_ssl_allowed_sites_cgi
then
echo `date`: dg_ssl_allowed_sites - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/dg_ssl_allowed_sites_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/dg_ssl_allowed_sites.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $dg_ssl_allowed_sites_cgi'check' ]
then
echo `date`: dg_ssl_allowed_sites - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/dg_ssl_allowed_sites_cgi
then
echo `date`: dg_ssl_allowed_sites - No tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/dg_ssl_allowed_sites_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/dg_ssl_allowed_sites.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $dg_ssl_allowed_sites_cgi'check' ]
then
echo `date`: dg_ssl_allowed_sites - Incorrect tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: dg_ssl_allowed_sites - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
WEBADDRESS=`echo $* | cut -s -d: -f4`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: dg_ssl_allowed_sites - Not called by dg_ssl_allowed_sites.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: dg_ssl_allowed_sites - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: dg_ssl_allowed_sites - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: dg_ssl_allowed_sites - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ $WEBADDRESS'null' = null ]
then
echo `date`: dg_ssl_allowed_sites - Blank webaddress by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

echo `date`: dg_ssl_allowed_sites - adding $WEBADDRESS by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

#Get squid server name
[ ! -f /opt/karoshi/server_network/proxyserver ] && exit 101
PROXYSERVER=`sed -n 1,1p /opt/karoshi/server_network/proxyserver`

if [ $PROXYSERVER != `hostname-fqdn` ]
then
ssh -x -o PasswordAuthentication=no $PROXYSERVER '
touch /etc/dansguardian/allowed_ssl_sites

if [ `grep -c ^'$WEBADDRESS' /etc/dansguardian/allowed_ssl_sites` = 0 ]
then
echo '$WEBADDRESS' >> /etc/dansguardian/allowed_ssl_sites
sort --unique /etc/dansguardian/allowed_ssl_sites > /etc/dansguardian/allowed_ssl_sites.$$
rm -f /etc/dansguardian/allowed_ssl_sites
mv /etc/dansguardian/allowed_ssl_sites.$$ /etc/dansguardian/allowed_ssl_sites
sed -i "/^$/d" /etc/dansguardian/allowed_ssl_sites
#Restart squid
source /opt/karoshi/serversetup/variables/distro
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/squid_reload
fi
'
else

touch /etc/dansguardian/allowed_ssl_sites

if [ `grep -c ^$WEBADDRESS /etc/dansguardian/allowed_ssl_sites` = 0 ]
then
echo $WEBADDRESS >> /etc/dansguardian/allowed_ssl_sites
sort --unique /etc/dansguardian/allowed_ssl_sites > /etc/dansguardian/allowed_ssl_sites.$$
rm -f /etc/dansguardian/allowed_ssl_sites
mv /etc/dansguardian/allowed_ssl_sites.$$ /etc/dansguardian/allowed_ssl_sites
sed -i "/^$/d" /etc/dansguardian/allowed_ssl_sites
#Reload squid
source /opt/karoshi/serversetup/variables/distro
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/squid_reload 1>/dev/null
fi
fi
exit

