#!/bin/bash
#Copyright (C) 2007 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit

########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/dg_view_banned_users2_cgi
then
echo `date`: dg_view_banned_users2 - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/dg_view_banned_users2_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/dg_view_banned_users2.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $dg_view_banned_users2_cgi'check' ]
then
echo `date`: dg_view_banned_users2 - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/dg_view_banned_users2_cgi
then
echo `date`: dg_view_banned_users2 - No tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/dg_view_banned_users2_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/dg_view_banned_users2.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $dg_view_banned_users2_cgi'check' ]
then
echo `date`: dg_view_banned_users2 - Incorrect tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: dg_view_banned_users2 - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
USERARRAY=( `echo $* | cut -s -d: -f4- | sed 's/:/ /g'` )
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: dg_view_banned_users2 - Not called by dg_view_banned_users2.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: dg_view_banned_users2 - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: dg_view_banned_users2 - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: dg_view_banned_users2 - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ $USERARRAY'null' = null ]
then
echo `date`: dg_view_banned_users2 - No sites chosen by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

USERCOUNT=`echo ${#USERARRAY[@]}`
COUNTER=0
#Log event
while [ $COUNTER -lt $USERCOUNT ]
do
BANNEDUSER=`echo ${USERARRAY[$COUNTER]}`
echo `date`: dg_view_banned_users2 - removing $BANNEDUSER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
let COUNTER=$COUNTER+1
done

#Get squid server name
[ ! -f /opt/karoshi/server_network/proxyserver ] && exit 101
PROXYSERVER=`sed -n 1,1p /opt/karoshi/server_network/proxyserver`

if [ $PROXYSERVER != `hostname-fqdn` ]
then
ssh -x -o PasswordAuthentication=no $PROXYSERVER '
USERARRAY=( `echo '${USERARRAY[@]:0}'` )
COUNTER=0
while [ $COUNTER -lt '$USERCOUNT' ]
do
#Delete user

BANNEDUSER=`echo ${USERARRAY[$COUNTER]}`
#Get line number of site
USERLINENUMBER=`grep -n -w ^$BANNEDUSER /etc/squid/badusers.list | cut -d: -f1`
if [ $USERLINENUMBER"null" != null ]
then
sed -i $USERLINENUMBER"d" /etc/squid/badusers.list
fi
let COUNTER=$COUNTER+1
done
#Remove blank lines
sed -i "/^$/d" /etc/squid/badusers.list
#Make sure that list is not empty
SITECOUNT=`cat /etc/squid/badusers.list | wc -l`
if [ $SITECOUNT = 0 ]
then
echo sampleuser > /etc/squid/badusers.list
fi
'
#Copy in badusers.list from proxy server to the pdc
scp  root@$PROXYSERVER:"/etc/squid/badusers.list" /etc/squid/
else
COUNTER=0
while [ $COUNTER -lt $USERCOUNT ]
do
#Delete user
BANNEDUSER=`echo ${USERARRAY[$COUNTER]}`
#Get line number of site
USERLINENUMBER=`grep -n -w ^$BANNEDUSER /etc/squid/badusers.list | cut -d: -f1`
if [ $USERLINENUMBER"null" != null ]
then
sed -i $USERLINENUMBER"d" /etc/squid/badusers.list
fi
let COUNTER=$COUNTER+1
done
#Remove blank lines
sed -i '/^$/d' /etc/squid/badusers.list
#Make sure that list is not empty
USERCOUNT=`cat /etc/squid/badusers.list | wc -l`
if [ $USERCOUNT = 0 ]
then
echo sampleuser > /etc/squid/badusers.list
fi
fi
exit
