#!/bin/bash
#Copyright (C) 2014 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
FAILED_SERVER=no
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/dhcp_reservations_cgi
then
	echo `date`: dhcp_reservations - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/dhcp_reservations_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/dhcp_reservations.cgi | cut -d' ' -f1`
[ -z "$MD5SUM" ] && MD5SUM=not_set
if [ $MD5SUM'check' != $dhcp_reservations_cgi'check' ]
	then
	echo `date`: dhcp_reservations - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
	echo `date`: dhcp_reservations - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

read DATA
DATA=`echo "$DATA" | tr -cd 'A-Za-z0-9\._:\-%'`
if [ -z "$DATA" ]
then
	echo `date`: dhcp_reservations - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
ACTION=`echo "$DATA" | cut -s -d: -f4`
CLIENTHOSTNAME=`echo "$DATA" | cut -s -d: -f5`
MACADDRESS=`echo "$DATA" | cut -s -d: -f6 | sed 's/%3A/:/g'`
TCPIPADDRESS=`echo "$DATA" | cut -s -d: -f7`

########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] 
then
	echo `date`: dhcp_reservations - Not called by dhcp_reservations.cgi or bulk_user_creation_create.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$REMOTE_USER" ]
then
	echo `date`: dhcp_reservations - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$REMOTE_ADDR" ]
then
	echo `date`: dhcp_reservations - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$ACTION" ]
then
	echo `date`: dhcp_reservations - Blank action by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$CLIENTHOSTNAME" ]
then
	echo `date`: dhcp_reservations - Blank "client hostname" by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ "$ACTION" = reallyadd ]
then
	if [ -z "$MACADDRESS" ]
	then
		echo `date`: dhcp_reservations - Blank mac address by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi
	if [ -z "$TCPIPADDRESS" ]
	then
		echo `date`: dhcp_reservations - Blank tcpip  address by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi
fi

function updatedhcpconf {

#Create config file

[ -f /opt/karoshi/server_network/dhcp/reservation_list ] && rm -f /opt/karoshi/server_network/dhcp/reservation_list
touch /opt/karoshi/server_network/dhcp/reservation_list
if [ `ls -1 /opt/karoshi/server_network/dhcp/reservations | wc -l` -gt 0 ]
then
	for RESERVATIONS in /opt/karoshi/server_network/dhcp/reservations/*
	do
		source $RESERVATIONS
		RESERVATION=`basename $RESERVATIONS`
		echo -e '\nhost '$RESERVATION' {\n\thardware ethernet '$MACADDRESS';\n\tfixed-address '$TCPIPADDRESS';\n}' >> /opt/karoshi/server_network/dhcp/reservation_list
	done
	echo >> /opt/karoshi/server_network/dhcp/reservation_list
fi


#Cat reservation list  into dhcpd.conf
cat /opt/karoshi/server_network/dhcp/reservation_list > /etc/dhcp/dhcpd_reservations.conf

#Restart DHCP
echo '<li>'$HOSTNAME' - '$"Restarting dhcp"'>/li>'
echo `date`: cdhcp_reservations - $HOSTNAME - restarting dhcp by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
source /opt/karoshi/serversetup/variables/distro
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/dhcp_stop 1>/dev/null 2>>/opt/karoshi/logs/karoshi_web_management/$LOG_DATE
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/dhcp_start 1>/dev/null 2>>/opt/karoshi/logs/karoshi_web_management/$LOG_DATE

#Sync config file to failover server
if [ -d /opt/karoshi/server_network/dhcp_servers ]
then
	for DHCPSERVER in `ls -1 /opt/karoshi/server_network/dhcp_servers`
	do
		if [ "$DHCPSERVER" != `hostname-fqdn` ]
		then
			echo '<li>'$DHCPSERVER' - '$"Restarting dhcp"'>/li>'
			echo `date`: client_boot_controls2 - $DHCPSERVER - restarting dhcp by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
			scp /etc/dhcp/dhcpd_reservations.conf root@$DHCPSERVER:/etc/dhcp/
			ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $DHCPSERVER '
			source /opt/karoshi/serversetup/variables/distro
			/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/dhcp_stop 1>/dev/null
			/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/dhcp_start 1>/dev/null
			'
		fi
	done
sleep 2
fi

}

if [ $ACTION = reallyadd ]
then
	#Add dhcp reservation and restart dhcp
	echo `date`: dhcp_reservations - adding $CLIENTHOSTNAME - mac address: $MACADDRESS tpcip: $TCPIPADDRESS by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	[ ! -d /opt/karoshi/server_network/dhcp/reservations ] && mkdir -p /opt/karoshi/server_network/dhcp/reservations
	echo -e "MACADDRESS=$MACADDRESS
	TCPIPADDRESS=$TCPIPADDRESS" > /opt/karoshi/server_network/dhcp/reservations/$CLIENTHOSTNAME
	updatedhcpconf
fi

if [ $ACTION = delete ]
then
	if [ -f /opt/karoshi/server_network/dhcp/reservations/$CLIENTHOSTNAME ]
	then
		rm -f /opt/karoshi/server_network/dhcp/reservations/$CLIENTHOSTNAME
		updatedhcpconf
	fi
fi
exit





