#!/bin/bash
#Copyright (C) 2017 Paul Sharrad

#
#Karoshi is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/domain_trusts_cgi
then
	echo `date`: domain_trusts - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/domain_trusts_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/admin/domain_trusts.cgi | cut -d' ' -f1`
[ -z "$Checksum" ] && Checksum=not_set
if [ $Checksum'check' != $domain_trusts_cgi'check' ]
then
	echo `date`: domain_trusts - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
	echo `date`: domain_trusts - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

read DATA
DATA=`echo "$DATA" | tr -cd 'A-Za-z0-9\._,:\-+/%'`
if [ -z "$DATA" ]
then
	echo `date`: domain_trusts - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
RemoteCheckSum=`echo "$DATA" | cut -s -d: -f3`
ACTION=`echo "$DATA" | cut -s -d: -f4`
TRUSTED_DOMAIN=`echo "$DATA" | cut -s -d: -f5`
USERNAME=`echo "$DATA" | cut -s -d: -f6`
PASSWORD=`echo "$DATA" | cut -s -d: -f7`
IPADDRESS1=`echo "$DATA" | cut -s -d: -f8`
IPADDRESS2=`echo "$DATA" | cut -s -d: -f9`

WIDTH1=250
WIDTH2=250
WIDTH3=100
WIDTH4=100

[ -z "$ACTION" ] && ACTION=view

if [ "$ACTION" = edit ]
then
	echo asking to edit $TRUSTED_DOMAIN
fi

if [ "$ACTION" = reallyremove ]
then
	samba-tool domain trust delete planets.com --username Administrator
fi

if [ "$ACTION" = remove ]
then
	echo asking to remove $TRUSTED_DOMAIN
fi

if [ "$ACTION" = reallyadd ]
then
	#Add domain information
	[ ! -d "/opt/karoshi/server_network/domain_information/trusted_domains/$TRUSTED_DOMAIN" ] && mkdir -p "/opt/karoshi/server_network/domain_information/trusted_domains/$TRUSTED_DOMAIN"

	if [ ! -z "$IPADDRESS2"
	then
		echo 'DNS_SERVERS="'$IPADDRESS1'; '$IPADDRESS2';"' > "/opt/karoshi/server_network/domain_information/trusted_domains/$TRUSTED_DOMAIN/dns"
	else
		echo 'DNS_SERVERS="'$IPADDRESS1';"' > "/opt/karoshi/server_network/domain_information/trusted_domains/$TRUSTED_DOMAIN/dns"
	fi
	#Make sure that bind can see the domain trust zones
	if [ $(grep -c /etc/bind/named.conf.trust-zones.conf /etc/bind/named.conf) = 0 ]
	then
		echo 'include "/etc/bind/named.conf.trust-zones.conf";' >> /etc/bind/named.conf
	fi

	#Rebuild /etc/bind/named.conf.trust-zones.con
	[ -f /etc/bind/named.conf.trust-zones.conf ] && rm -f /etc/bind/named.conf.trust-zones.conf
	touch /etc/bind/named.conf.trust-zones.conf
	for DOMAIN_TRUST in $(ls -1 /opt/karoshi/server_network/domain_information/trusted_domains)
	do
		source "/opt/karoshi/server_network/domain_information/trusted_domains/$DOMAIN_TRUST/dns"
		echo 'zone "'$DOMAIN_TRUST'" {
type forward;
forwarders { '$DNS_SERVERS' };
};

' >> /etc/bind/named.conf.trust-zones.conf
	done

	#Restart bind
	service bind9 stop 1>/dev/null
	sleep 1
	service bind9 start 1>/dev/null

	#Configure bind on all other domain controllers

	#Create the domain trust
	LDAPPASS=`sed -n 1,1p /etc/ldap.secret`
	samba-tool domain trust create "$DOMAIN_TRUST" --username Administrator --password $LDAPPASS 1>/dev/null 2>>/opt/karoshi/logs/karoshi_web_management/$LOG_DATE

	# Check that we were successful
	if [ $? != 0 ]
	then
		rm -f -R "/opt/karoshi/server_network/domain_information/trusted_domains/$TRUSTED_DOMAIN"
		echo $"There was a problem creating the domain trust."
		sleep 5
		exit
	fi
	ACTION=view
fi

if [ "$ACTION" = add ]
then
	#Get details to add a domain trust
	echo '<input type="hidden" name="____ACTION____" value="reallyadd">
	<table class="standard" style="text-align: left;" ><tbody>
	<tr><td style="width: 180px;">'$"Domain"'</td>
        <td><input tabindex= "1" name="____DOMAIN____" style="width: 200px;" size="20" type="text"></td>
	<td><a class="info" target="_blank" href="http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=Add_User"><img class="images" alt="" src="/images/help/info.png"><span>'$"Enter the domain name for the domain trust that you want to create."'</span></a></td></tr>
	<tr><td style="width: 180px;">'$"Username"'</td>
	<td><input tabindex= "2" name="____USERNAME____" style="width: 200px;" size="20" type="text"></td>
	<td><a class="info" target="_blank" href="http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=Add_User"><img class="images" alt="" src="/images/help/info.png"><span>'$"Enter a username for the domain that has the authority of to create the domain trust."'</span></a></td></tr>
	<tr><td>'$"Password"'</td><td><input tabindex= "3" name="____PASSWORD____" style="width: 200px;" size="20" type="password"></td>
	<td><a class="info" target="_blank" href="http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=Add_User#Detailed_Explanation"><img class="images" alt="" src="/images/help/info.png"><span>'$"Enter a password for the username."'<br><br>'$"The following special characters are allowed"'<br><br> space !	&quot;	# 	$	%	&amp; 	(	) 	*	+	, 	-	.	/ 	:
;	&lt;	=	&gt;	?	@ 	[	\	]	^	_	` 	{	|	}	~	~</span></a></td></tr>
	<tr><td style="width: 180px;">'$"DNS Server"' 1</td>
        <td><input tabindex= "4" name="____IPADDRESS1____" style="width: 200px;" size="20" type="text"></td>
	<td><a class="info" target="_blank" href="http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=Add_User"><img class="images" alt="" src="/images/help/info.png"><span>'$"Enter a TCPIP number for a DNS server in the domain that you want to create the trust for."'</span></a></td></tr>
	<tr><td style="width: 180px;">'$"DNS Server"' 2</td>
        <td><input tabindex= "5" name="____IPADDRESS2____" style="width: 200px;" size="20" type="text"></td>
	<td><a class="info" target="_blank" href="http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=Add_User"><img class="images" alt="" src="/images/help/info.png"><span>'$"Enter an additional TCPIP number for another DNS server in the domain that you want to create the trust for."'</span></a></td></tr></tbody></table><br><br><input value="'$"Submit"'" class="button" type="submit"> <input value="'$"Reset"'" class="button" type="reset">
'
	
fi

if [ "$ACTION" = view ]
then
	if [ -d /opt/karoshi/server_network/domain_information/trusted_domains/ ]
	then
		ICON1=/images/submenus/system/edit.png
		ICON2=/images/submenus/system/delete.png

		echo '<table id="myTable" class="tablesorter" style="text-align: left;" >
		<thead><tr><th style="width: '$WIDTH1'px;">'$"Domain"'</th><th style="width: '$WIDTH2'px;">'$"DNS Servers"'</th><th style="width: '$WIDTH3'px;">'$"Edit"'</th><th style="width: '$WIDTH4'px;">'$"Remove"'</th></tr></thead><tbody>'

		for TRUSTED_DOMAIN in $(ls -1 /opt/karoshi/server_network/domain_information/trusted_domains/)
		do
			echo '<tr><td>'$TRUSTED_DOMAIN'</td><td>'
			source "/opt/karoshi/server_network/domain_information/trusted_domains/$TRUSTED_DOMAIN/dns"
			DNS_SERVERS=$(echo $DNS_SERVERS | sed 's/;/<br>/g')
			echo ''$DNS_SERVERS'</td>
		<td><button class="info" name="____Control____" value="____ACTION____edit____DOMAIN____'$TRUSTED_DOMAIN'____">
			<img src="'$ICON1'" alt="Remove<br>'$TRUSTED_DOMAIN'">
			<span>'$"Edit"'<br>'$TRUSTED_DOMAIN'</span>
			</button></td>
			<td><button class="info" name="____Control____" value="____ACTION____remove____DOMAIN____'$TRUSTED_DOMAIN'____">
			<img src="'$ICON2'" alt="Remove<br>'$TRUSTED_DOMAIN'">
			<span>'$"Remove"'<br>'$TRUSTED_DOMAIN'</span>
			</button></td></tr>'
		done

		echo '</tbody></table>'
	else
		echo $"No domain trusts have been added."
	fi
fi
