#!/bin/bash
#Copyright (C) 2014 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
ICON1=/images/submenus/internet/remove_group.png
ICON2=/images/submenus/internet/allowed_sites.png
ICON3=/images/submenus/internet/banned_sites.png
ICON4=/images/submenus/system/edit.png
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/e2g_filtergroups_cgi
then
echo `date`: e2g_filtergroups - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/e2g_filtergroups_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/e2g_filtergroups.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $e2g_filtergroups_cgi'check' ]
then
echo `date`: e2g_filtergroups - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: e2g_filtergroups - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-+%'`
if [ $DATA'null' = null ]
then
echo `date`: e2g_filtergroups - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
ACTION=`echo "$DATA" | cut -s -d: -f4`
FILTERNAME=`echo "$DATA" | cut -s -d: -f5`
FILTERDATA=`echo "$DATA" | cut -s -d: -f6`
FILTERDATA2=`echo "$DATA" | cut -s -d: -f7`
FILTERDATA3=`echo "$DATA" | cut -s -d: -f8`
PROXYSERVER=`sed -n 1,1p /opt/karoshi/server_network/proxyserver`

########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
	echo `date`: e2g_filtergroups - Not called by e2g_filtergroups.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$REMOTE_USER" ]
then
	echo `date`: e2g_filtergroups - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$REMOTE_ADDR" ]
then
	echo `date`: e2g_filtergroups - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$ACTION" ]
then
	echo `date`: e2g_filtergroups - Blank action by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ "$ACTION" = reallyadd ]
then
	if [ -z "$FILTERDATA" ]
	then
		echo `date`: e2g_filtergroups - Blank filter label by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi
	if [ -z "$FILTERDATA2" ]
	then
		echo `date`: e2g_filtergroups - Blank fiter description by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi
	if [ -z "$FILTERDATA3" ]
	then
		echo `date`: e2g_filtergroups - Blank filter clone by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi
fi

if [ "$ACTION" = editlabel ]
then
	if [ -z "$FILTERNAME" ]
	then
		echo `date`: e2g_filtergroups - Blank filtername by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi
fi

if [ $ACTION = reallyeditlabel ]
then
	if [ -z "$FILTERDATA" ]
	then
		echo `date`: e2g_filtergroups - Blank filter description by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi
	if [ -z "$FILTERDATA2" ]
	then
		echo `date`: e2g_filtergroups - Blank filter label by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
		exit 101
	fi	

fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: e2g_filtergroups - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

##########################
#Language
##########################
LANGCHOICE=englishuk
STYLESHEET=defaultstyle.css
[ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/internet/e2g_filtergroups ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/internet/e2g_filtergroups
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/all ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/all

source /opt/karoshi/server_network/domain_information/domain_name

function showtitle {
echo '<form name="myform" action="/cgi-bin/admin/e2g_filtergroups.cgi" method="post"><table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2">
<tr><td style="width: 180px; vertical-align: top;"><div class="sectiontitle">'$TITLE'</div></td>'

if [ $ACTION = editfilterlists ] || [ $ACTION = bannedextensionlists ] || [ $ACTION = bannedmimetypelists ]
then
echo '<td style="vertical-align: top;"><input name="_ACTION_editfiltergroup_FILTERNAME_'$FILTERNAME'_" type="submit" class="button" value="'$EDITFILTERGROUPMSG'"></td>'
fi

echo '<td style="vertical-align: top;"><input name="_ACTION_view_" type="submit" class="button" value="'$VIEWFGROUPS'"></td>
<td style="vertical-align: top;"><a class="info" target="_blank" href="http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=Filter_Management'$SUBTITLE'"><img class="images" alt="" src="/images/help/info.png"><span>'$HELPMSG'</span></a></td>
</tr></tbody></table><br></form></div><div id="infobox">'
}


function viewfilters {
#Show add filtergroup button
echo '<form name="myform" action="/cgi-bin/admin/e2g_filtergroups.cgi" method="post">
<table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2">
<tr><td style="width: 180px; vertical-align: top;"><div class="sectiontitle">'$TITLE1'</div></td>
<td style="vertical-align: top;">
<input name="_ACTION_add_" type="submit" class="button" value="'$ADDFGROUP'">
</td>'

#Button disabled unless really needed.
#echo '<td style="vertical-align: top;">
#<input name="_ACTION_activatechanges_" type="submit" class="button" value="'$ACTIVATECHANGESMSG'">
#</td>'

echo '<td style="vertical-align: top;"><a class="info" target="_blank" href="http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=Filter_Management"><img class="images" alt="" src="/images/help/info.png"><span>'$HELPMSG1'</span></a></td></tr></tbody></table><br>'

#Show existing filtergroups

echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
<tr><td style=\"width: 40px;\"><b>$FILTERNAMEMSG</b></td><td style=\"width: 120px;\"><b>$FILTERLABELMSG</b></td><td style=\"width: 140px;\"><b>$FILTERDESCMSG</b></td><td style=\"width: 120px;\"><b>$ASSIGNEDGROUPSMSG</b></td></tr>
"

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
	do
		FILTERGROUP=`basename $FILTERGROUPS`
		source /etc/e2guardian/lists/filtergroups/$FILTERGROUP/details
		echo "<tr><td style=\"height: 40px;\" valign=\"top\">$FILTERGROUP</td><td valign=\"top\">$FILTERLABEL</td><td valign=\"top\">$FILTERDESC</td><td valign=\"top\">"

		#Get list of assigned groups

		if [ $FILTERGROUP = f1 ]
		then
			echo $DEFAULTGROUPMSG
		else
			if [ -d /etc/e2guardian/lists/filtergroups/$FILTERGROUP/assigned_groups ]
			then
				for ASSIGNEDGROUPS in /etc/e2guardian/lists/filtergroups/$FILTERGROUP/assigned_groups/*
				do
					ASSIGNEDGROUP=`basename $ASSIGNEDGROUPS`
					echo $ASSIGNEDGROUP"<br>"
				done
			fi
		fi
		#Show actions for the filter groups
		echo "<td style=\"vertical-align: top;\"><input name=\"_ACTION_editfiltergroup_FILTERNAME_"$FILTERGROUP"_\" type=\"submit\" class=\"button\" value=\"$EDITFILTERGROUPMSG\"></td><td style=\"vertical-align: top;\">"
		if [ $FILTERGROUP != f1 ]
		then
			echo "<input name=\"_ACTION_deletefiltergroup_FILTERNAME_"$FILTERGROUP"_\" type=\"submit\" class=\"button\" value=\"$DELETEFILTERGROUPMSG\">"
		fi
		echo "</td></tr>"
	done
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
	do
		FILTERGROUP=`basename $FILTERGROUPS`
		source /etc/e2guardian/lists/filtergroups/$FILTERGROUP/details
		echo "<tr><td style=\"height: 40px;\" valign=\"top\">$FILTERGROUP</td><td valign=\"top\">$FILTERLABEL</td><td valign=\"top\">$FILTERDESC</td><td valign=\"top\">"

		#Get list of assigned groups

		if [ $FILTERGROUP = f1 ]
		then
			echo '$DEFAULTGROUPMSG'
		else
			if [ -d /etc/e2guardian/lists/filtergroups/$FILTERGROUP/assigned_groups ]
			then
				for ASSIGNEDGROUPS in /etc/e2guardian/lists/filtergroups/$FILTERGROUP/assigned_groups/*
				do
					ASSIGNEDGROUP=`basename $ASSIGNEDGROUPS`
					echo $ASSIGNEDGROUP"<br>"
				done
			fi
		fi
		#Show actions for the filter groups
		echo "<td style=\"vertical-align: top;\"><input name=\"_ACTION_editfiltergroup_FILTERNAME_"$FILTERGROUP"_\" type=\"submit\" class=\"button\" value=\"'$EDITFILTERGROUPMSG'\"></td><td style=\"vertical-align: top;\">"
		if [ $FILTERGROUP != f1 ]
		then
			echo "<input name=\"_ACTION_deletefiltergroup_FILTERNAME_"$FILTERGROUP"_\" type=\"submit\" class=\"button\" value=\"'$DELETEFILTERGROUPMSG'\">"
		fi
		echo "</td></tr>"
	done
'
fi
echo "</tbody></table></form>"
}

function reallyeditlabels {
FILTERLABEL=`echo $FILTERDATA | sed "s/+/ /g"`
FILTERDESC=`echo $FILTERDATA2 | sed "s/+/ /g"`

if [ ! -z "$FILTERLABEL" ] && [ ! -z "$FILTERDESC" ] 
then
	if [ $PROXYSERVER = `hostname-fqdn` ]
	then
		echo "FILTERLABEL=\"$FILTERLABEL\"" > /etc/e2guardian/lists/filtergroups/$FILTERNAME/details
		echo "FILTERDESC=\"$FILTERDESC\"" >> /etc/e2guardian/lists/filtergroups/$FILTERNAME/details
	else
		ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
		echo "FILTERLABEL=\"'$FILTERLABEL'\"" > /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/details
		echo "FILTERDESC=\"'$FILTERDESC'\"" >> /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/details
	'
	fi
fi
}

function addfiltergroup {
#Show view filtergroup button
TITLE="$TITLE2"
HELPMSG="$HELPMSG2"
SUBTITLE="#Adding_extra_filter_groups"
showtitle

echo '<form name="myform" action="/cgi-bin/admin/e2g_filtergroups.cgi" method="post">'$FILTERWARNINGMSG'<br><br><input type="hidden" name="_ACTION_" value="reallyadd"><table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2"><tbody>
<tr><td style="width: 180px;">'$FILTERLABELMSG'</td><td><input tabindex= "1" name="_FILTERDATA_" style="width: 200px;" size="20" type="text"></td></tr>
<tr><td style="width: 180px;">'$FILTERDESCMSG'</td><td><input tabindex= "1" name="_FILTERDATA2_" style="width: 200px;" size="20" type="text"></td></tr>
<tr><td style="width: 180px;">'$FILTERCLONEMSG'</td><td><select name="_FILTERDATA3_" style="width: 200px;">'

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
	do
		FILTERGROUP=`basename $FILTERGROUPS`
		echo "<option value=\"$FILTERGROUP\" $FILTERGROUP>$FILTERGROUP</option>"
	done
else
	ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
	do
		FILTERGROUP=`basename $FILTERGROUPS`
		echo "<option value=\"$FILTERGROUP\" $FILTERGROUP>$FILTERGROUP</option>"
	done
	'
fi
echo '</select></tbody></table><br><br><input value="'$SUBMITMSG'" class="button" type="submit"> <input value="'$RESETMSG'" class="button" type="reset"></form>
'

}

function reallyaddfiltergroup {

FILTERCLONE=$FILTERDATA3
#Get name of new filter group
if [ $PROXYSERVER = `hostname-fqdn` ]
then
FILTERCOUNT=`ls -1 /etc/e2guardian/lists/filtergroups/ | wc -l`
else
FILTERCOUNT=`ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER 'ls -1 /etc/e2guardian/lists/filtergroups/ | wc -l'`
fi
let FILTERCOUNT=$FILTERCOUNT+1

echo `date`: e2g_filtergroups - adding new filter group f$FILTERCOUNT by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Get name of new filter group
	FILTERCOUNT=`ls -1 /etc/e2guardian/lists/filtergroups/ | wc -l`
	let FILTERCOUNT=$FILTERCOUNT+1

	#Copy filter group config folder
	cp -f -R /etc/e2guardian/lists/filtergroups/$FILTERCLONE /etc/e2guardian/lists/filtergroups/f$FILTERCOUNT

	#Delete any assigned groups
	[ -d /etc/e2guardian/lists/filtergroups/f$FILTERCOUNT/assigned_groups ] && rm -f -R /etc/e2guardian/lists/filtergroups/f$FILTERCOUNT/assigned_groups

	#Copy e2guardian config file
	cp -f /etc/e2guardian/e2guardian$FILTERCLONE.conf /etc/e2guardian/e2guardianf$FILTERCOUNT.conf
	#Edit e2guardian config file to look at the correct filter folder
	sed -i "s/$FILTERCLONE/f$FILTERCOUNT/g" /etc/e2guardian/e2guardianf$FILTERCOUNT.conf

	#Modifiy e2guardian.conf for correct number of filters
	FILTERLINENO=`grep -n ^"filtergroups =" /etc/e2guardian/e2guardian.conf | cut -d: -f1`
	sed -i $FILTERLINENO"c""filtergroups = $FILTERCOUNT" /etc/e2guardian/e2guardian.conf

	#Restart e2guardian
	source /opt/karoshi/serversetup/variables/distro
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_stop 1>/dev/null
	sleep 1
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_start 1>/dev/null
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '

	#Copy filter group config folder
	cp -f -R /etc/e2guardian/lists/filtergroups/'$FILTERCLONE' /etc/e2guardian/lists/filtergroups/f'$FILTERCOUNT'

	#Delete any assigned groups
	[ -d /etc/e2guardian/lists/filtergroups/f'$FILTERCOUNT'/assigned_groups ] && rm -f -R /etc/e2guardian/lists/filtergroups/f'$FILTERCOUNT'/assigned_groups

	#Copy e2guardian config file
	cp -f /etc/e2guardian/e2guardian'$FILTERCLONE'.conf /etc/e2guardian/e2guardianf'$FILTERCOUNT'.conf
	#Edit e2guardian config file to look at the correct filter folder
	sed -i "s/'$FILTERCLONE'/f'$FILTERCOUNT'/g" /etc/e2guardian/e2guardianf'$FILTERCOUNT'.conf

	#Modifiy e2guardian.conf for correct number of filters
	FILTERLINENO=`grep -n ^"filtergroups =" /etc/e2guardian/e2guardian.conf | cut -d: -f1`
	sed -i $FILTERLINENO"c""filtergroups = '$FILTERCOUNT'" /etc/e2guardian/e2guardian.conf

	#Restart e2guardian
	source /opt/karoshi/serversetup/variables/distro
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_stop 1>/dev/null
	sleep 1
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_start 1>/dev/null
'
fi
restarte2guardian
#Modify details file
FILTERNAME=f$FILTERCOUNT
reallyeditlabels
}

function deletefiltergroup {
#Show view filtergroup button
TITLE="$TITLE4"
HELPMSG="$HELPMSG4"
showtitle

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	source /etc/e2guardian/lists/filtergroups/$FILTERNAME/details
else
	source <(ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER cat /etc/e2guardian/lists/filtergroups/$FILTERNAME/details)
fi
echo '<form name="myform" action="/cgi-bin/admin/e2g_filtergroups.cgi" method="post">
<table class="standard" style="text-align: left;" border="0" cellpadding="2" cellspacing="2">
<tr><td style="width: 180px;">'$FILTERNAMEMSG'</td><td>'$FILTERNAME'</td></tr>
<tr><td>'$FILTERLABELMSG'</td><td>'$FILTERLABEL'</td></tr>
<tr><td>'$FILTERDESCMSG'</td><td>'$FILTERDESC'</td></tr></tbody></table><br>
'$CONFIRMDELETEMSG'<br><br><input type="hidden" name="_ACTION_" value="reallydelete"><br><input type="hidden" name="_FILTERNAME_" value="'$FILTERNAME'"><input value="'$SUBMITMSG'" class="button" type="submit"></form>'
}

function reallydelete {
echo `date`: e2g_filtergroups - deleting filter group $FILTERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Delete filter folder
	rm -f -R /etc/e2guardian/lists/filtergroups/$FILTERNAME
	#Delete e2guardian config file
	rm -f /etc/e2guardian/e2guardian$FILTERNAME.conf
	#Modify e2guardian.conf with correct filter count.
	FILTERCOUNT=`ls -1 /etc/e2guardian/lists/filtergroups/ | wc -l`
	FILTERLINENO=`grep -n ^"filtergroups =" /etc/e2guardian/e2guardian.conf | cut -d: -f1`
	sed -i $FILTERLINENO"c""filtergroups = $FILTERCOUNT" /etc/e2guardian/e2guardian.conf

	#Rename all filter groups so that they are in sequence
	COUNTER=1
	for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
	do
		FILTERGROUP=`basename $FILTERGROUPS`
		#Check that the filtergroup name is correct
		if [ $FILTERGROUP != f$COUNTER ]
		then
			mv /etc/e2guardian/lists/filtergroups/$FILTERGROUP /etc/e2guardian/lists/filtergroups/f$COUNTER
			sed -i "s/$FILTERGROUP/f$COUNTER/g" /etc/e2guardian/e2guardian$FILTERGROUP.conf
			mv /etc/e2guardian/e2guardian$FILTERGROUP.conf /etc/e2guardian/e2guardianf$COUNTER.conf
		fi
		let COUNTER=$COUNTER+1
	done 
	#Regenerate filter lists
	/opt/karoshi/"useful scripts"/e2gupdatefilterlist
	#Restart e2guardian
	source /opt/karoshi/serversetup/variables/distro
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_stop 1>/dev/null
	sleep 1
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_start 1>/dev/null
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	#Delete filter folder
	rm -f -R /etc/e2guardian/lists/filtergroups/'$FILTERNAME'
	#Delete e2guardian config file
	rm -f /etc/e2guardian/e2guardian'$FILTERNAME'.conf
	#Modify e2guardian.conf with correct filter count.
	FILTERCOUNT=`ls -1 /etc/e2guardian/lists/filtergroups/ | wc -l`
	FILTERLINENO=`grep -n ^"filtergroups =" /etc/e2guardian/e2guardian.conf | cut -d: -f1`
	sed -i $FILTERLINENO"c""filtergroups = $FILTERCOUNT" /etc/e2guardian/e2guardian.conf

	#Rename all filter groups so that they are in sequence
	COUNTER=1
	for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
	do
		FILTERGROUP=`basename $FILTERGROUPS`
		#Check that the filtergroup name is correct
		if [ $FILTERGROUP != f$COUNTER ]
		then
			mv /etc/e2guardian/lists/filtergroups/$FILTERGROUP /etc/e2guardian/lists/filtergroups/f$COUNTER
			sed -i "s/$FILTERGROUP/f$COUNTER/g" /etc/e2guardian/e2guardian$FILTERGROUP.conf
			mv /etc/e2guardian/e2guardian$FILTERGROUP.conf /etc/e2guardian/e2guardianf$COUNTER.conf
		fi
		let COUNTER=$COUNTER+1
	done 
	#Regenerate filter lists
	/opt/karoshi/"useful scripts"/e2gupdatefilterlist
	#Restart e2guardian
	source /opt/karoshi/serversetup/variables/distro
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_stop 1>/dev/null
	sleep 1
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_start 1>/dev/null
'
fi
restarte2guardian
}

function editfiltergroup {

TITLE="$TITLE5"
HELPMSG="$HELPMSG5"
SUBTITLE="#Edit_Filter_Group"
showtitle

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	source /etc/e2guardian/lists/filtergroups/$FILTERNAME/details
else
	source <(ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER cat /etc/e2guardian/lists/filtergroups/$FILTERNAME/details)
fi

#Show details for the group
echo "<form name=\"myform\" action=\"/cgi-bin/admin/e2g_filtergroups.cgi\" method=\"post\"><input type=\"hidden\" name=\"_FILTERNAME_\" value=\"$FILTERNAME\"><input type=\"hidden\" name=\"_ACTION_\" value=\"reallyeditlable\"><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"width: 180px;\">$FILTERNAMEMSG</td><td>$FILTERNAME</td></tr><tr><td style=\"width: 180px;\">$FILTERLABELMSG</td><td><input tabindex= \"1\" value=\"$FILTERLABEL\" name=\"_FILTERDATA_\" style=\"width: 200px;\" size=\"20\" type=\"text\"></td><td><input value=\"$SUBMITMSG\" class=\"button\" type=\"submit\"></td></tr>
<tr><td>$FILTERDESCMSG</td><td><input tabindex= \"2\" value=\"$FILTERDESC\" name=\"_FILTERDATA2_\" style=\"width: 200px;\" size=\"20\" type=\"text\"></td></tr></tbody></table><br><br>"

#Show option to edit banned site lists and part banned site lists
echo "</form><form name=\"myform\" action=\"/cgi-bin/admin/e2g_filtergroups.cgi\" method=\"post\">
<input type=\"hidden\" name=\"_FILTERNAME_\" value=\"$FILTERNAME\">
<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"width: 180px;\"><b>$FILTEROPTIONSMSG</b></td><td><b>$EDITMSG</b></td></tr>
<tr><td>$BANNEDLISTSMSG</td><td style=\"vertical-align: top;\">
<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_editfilterlists_FILTERDATA_domains_\" type=\"image\" class=\"images\" src=\"$ICON4\" value=\"\"><span>$EDITMSG<br>$BANNEDLISTSMSG</span></a>
</td></tr>
<tr><td>$PARTBANNEDLISTSMSG</td><td style=\"vertical-align: top;\">
<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_editfilterlists_FILTERDATA_urls_\" type=\"image\" class=\"images\" src=\"$ICON4\" value=\"\"><span>$EDITMSG<br>$PARTBANNEDLISTSMSG</span></a>
</td></tr>
<tr><td>$BANNEDPHRASELISTSMSG</td><td style=\"vertical-align: top;\">
<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_editfilterlists_FILTERDATA_phraselists_\" type=\"image\" class=\"images\" src=\"$ICON4\" value=\"\"><span>$EDITMSG<br>$BANNEDPHRASELISTSMSG</span></a>
</td></tr>
<tr><td>$BANNEDEXTENSIONLISTSMSG</td><td style=\"vertical-align: top;\">
<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_bannedextensionlists_\" type=\"image\" class=\"images\" src=\"$ICON4\" value=\"\"><span>$EDITMSG<br>$BANNEDEXTENSIONLISTSMSG</span></a>
</td></tr>
<tr><td>$BANNEDMIMETYPELISTSMSG</td><td style=\"vertical-align: top;\">
<a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_bannedmimetypelists_\" type=\"image\" class=\"images\" src=\"$ICON4\" value=\"\"><span>$EDITMSG<br>$BANNEDMIMETYPELISTSMSG</span></a>
</td></tr>
</tbody></table><br>
"

echo '</form><form name="myform" action="/cgi-bin/admin/e2g_filtergroups.cgi" method="post">'

if [ $FILTERNAME != f1 ]
then
	#Show option to add in a group
	echo "<input type=\"hidden\" name=\"_FILTERNAME_\" value=\"$FILTERNAME\"><input type=\"hidden\" name=\"_ACTION_\" value=\"reallyaddgroup\">"
	echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
	<tr><td style=\"width: 180px;\"><b>$ADDUSERGROUPMSG</b></td></tr><tr><td>$GROUPMSG</td><td>"

	/opt/karoshi/web_controls/group_dropdown_list | sed 's/_GROUP_/_FILTERDATA_/g'

	echo "</td><td><input value="$ADDGROUPMSG" class=\"button\" type=\"submit\"></td></tr></tbody></table><br>"

	echo '</form><form name="myform" action="/cgi-bin/admin/e2g_filtergroups.cgi" method="post">'


	#Show any existing groups that have been assigned.
	if [ $PROXYSERVER = `hostname-fqdn` ]
	then
		if [ -d /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups ]
		then
			echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tr><td style=\"width: 180px;\"><b>$ASSIGNEDUSERGROUPSMSG</b></td><td><b>$REMOVEMSG</b></td></tr>
			"
			for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups/*
			do
				FILTERGROUP=`basename $FILTERGROUPS`
				echo "<tr><td style=\"width: 180px;\">$FILTERGROUP</td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_removegroup_FILTERNAME_$FILTERNAME"_"FILTERDATA"_"$FILTERGROUP"_"\" type=\"image\" class=\"images\" src=\"$ICON1\" value=\"\"><span>$FILTERGROUP<br>$REMOVEMSG</span></a></td></tr>"
				done
			echo "</tbody></table>"
		fi
	else
	ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
		if [ -d /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups ]
		then
			echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tr><td style=\"width: 180px;\"><b>'$ASSIGNEDUSERGROUPSMSG'</b></td><td><b>'$REMOVEMSG'</b></td></tr>
			"
			for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups/*
			do
				FILTERGROUP=`basename $FILTERGROUPS`
				echo "<tr><td style=\"width: 180px;\">$FILTERGROUP</td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_removegroup_FILTERNAME_'$FILTERNAME'"_"FILTERDATA"_"$FILTERGROUP"_"\" type=\"image\" class=\"images\" src=\"'$ICON1'\" value=\"\"><span>$FILTERGROUP<br>'$REMOVEMSG'</span></a></td></tr>"
				done
			echo "</tbody></table>"
		fi
	'
	fi
fi
echo '</form>'
}

function removegroup {
FILTERGROUP=$FILTERDATA
echo `date`: e2g_filtergroups - removing $FILTERGROUP from filtergroup $FILTERNAME by  $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Remove filtergroup flag file
	[ -f /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups/$FILTERGROUP ] && rm -f /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups/$FILTERGROUP

	#Remove assigned_groups folder if it is empty
	[ `ls -1 /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups | wc -l` = 0 ] && rm -f -R /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups

	#Regenerate filter lists
	/opt/karoshi/"useful scripts"/e2gupdatefilterlist
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	#Remove filtergroup flag file
	[ -f /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups/'$FILTERGROUP' ] && rm -f /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups/'$FILTERGROUP'

	#Remove assigned_groups folder if it is empty
	[ `ls -1 /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups | wc -l` = 0 ] && rm -f -R /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups

	#Regenerate filter lists
	/opt/karoshi/"useful scripts"/e2gupdatefilterlist
'
fi
}

function reallyaddgroup {
FILTERGROUP=$FILTERDATA
echo `date`: e2g_filtergroups - adding $FILTERGROUP to filter $FILTERNAME by  $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

if [ $PROXYSERVER = `hostname-fqdn` ]
then
#Create flag file
[ ! -d /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups ] && mkdir -p /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups
touch /etc/e2guardian/lists/filtergroups/$FILTERNAME/assigned_groups/$FILTERGROUP

#Remove flag file from any other filtergroup.
for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
do
	GROUP=`basename $FILTERGROUPS`
	if [ $GROUP != $FILTERNAME ]
	then
		if [ -d /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups ]
		then
			[ -f /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups/$FILTERGROUP ] && rm -f /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups/$FILTERGROUP

			#Remove assigned_groups folder if it is empty
			[ `ls -1 /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups | wc -l` = 0 ] && rm -f -R /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups
		fi
	fi
done

#Regenerate filter lists
/opt/karoshi/"useful scripts"/e2gupdatefilterlist
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
#Create flag file
[ ! -d /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups ] && mkdir -p /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups
touch /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/assigned_groups/'$FILTERGROUP'

#Remove flag file from any other filtergroup.
for FILTERGROUPS in /etc/e2guardian/lists/filtergroups/*
do
	GROUP=`basename $FILTERGROUPS`
	if [ $GROUP != '$FILTERNAME' ]
	then
		if [ -d /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups ]
		then
			[ -f /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups/'$FILTERGROUP' ] && rm -f /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups/'$FILTERGROUP'

			#Remove assigned_groups folder if it is empty
			[ `ls -1 /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups | wc -l` = 0 ] && rm -f -R /etc/e2guardian/lists/filtergroups/$GROUP/assigned_groups
		fi
	fi
done

#Regenerate filter lists
/opt/karoshi/"useful scripts"/e2gupdatefilterlist
'
fi
}

function editfilterlists {

FILENAME=bannedsitelist
FILTERTYPE=domains
SEARCHTERM=blacklists
COL1=6
COL2=7
TITLE="$TITLE6"
HELPMSG="$HELPMSG6"

if [ $FILTERDATA = urls ]
then
	FILENAME=bannedurllist
	FILTERTYPE=urls
	TITLE="$TITLE7"
	HELPMSG="$HELPMSG7"
fi

if [ $FILTERDATA = phraselists ]
then
	FILENAME=bannedphraselist
	FILTERTYPE=banned
	SEARCHTERM=phraselists
	TITLE="$TITLE8"
	HELPMSG="$HELPMSG8"
fi

SUBTITLE="#Filter_Group_Options"
showtitle

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	source /etc/e2guardian/lists/filtergroups/$FILTERNAME/details
else
	source <(ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER cat /etc/e2guardian/lists/filtergroups/$FILTERNAME/details)
fi

#Show details for the group

echo "<form name=\"myform\" action=\"/cgi-bin/admin/e2g_filtergroups.cgi\" method=\"post\"><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"width: 180px;\">$FILTERNAMEMSG</td><td>$FILTERNAME</td></tr><tr><td style=\"width: 180px;\">$FILTERLABELMSG</td><td>$FILTERLABEL</td></tr>
<tr><td>$FILTERDESCMSG</td><td>$FILTERDESC</td></tr></tbody></table><br><br>"

echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\">
<tr><td style=\"width: 180px;\"><b>$CATEGORYMSG</b></td><td style=\"width: 120px;\"><b>$STATUSMSG</b></td></tr>"


#Show categories that are currently active
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	for CATEGORIES in `grep ^".Include</etc/e2guardian/lists/$SEARCHTERM/" /etc/e2guardian/lists/filtergroups/$FILTERNAME/$FILENAME | sed "s/>//g" | sed "s/<//g"`
	do
		CATEGORY=`echo "$CATEGORIES" | cut -d"/" -f$COL1`
		SUBCATEGORY=`echo "$CATEGORIES" | cut -d"/" -f$COL2`
		CATEGORYNAME="$CATEGORY"
		[ $SUBCATEGORY != $FILTERTYPE ] && CATEGORYNAME="$CATEGORY/$SUBCATEGORY"

		echo "<tr><td>$CATEGORYNAME</td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_reallyeditfilterlists_FILTERNAME_$FILTERNAME"_"FILTERDATA_$FILTERDATA"_"FILTERDATA2"_"$CATEGORYNAME"_"FILTERDATA3_deactivate_\" type=\"image\" class=\"images\" src=\"$ICON2\" value=\"\"><span>$CATEGORYNAME<br><br>$REMOVEMSGLISTMSG</span></a></td></tr>"
	done

	#Show inactive categories
	for CATEGORIES in `grep ^"#.Include</etc/e2guardian/lists/$SEARCHTERM/" /etc/e2guardian/lists/filtergroups/$FILTERNAME/$FILENAME | sed "s/>//g" | sed "s/<//g"`
	do
		CATEGORY=`echo "$CATEGORIES" | cut -d"/" -f$COL1`
		SUBCATEGORY=`echo "$CATEGORIES" | cut -d"/" -f$COL2`
		CATEGORYNAME="$CATEGORY"
		[ $SUBCATEGORY != $FILTERTYPE ] && CATEGORYNAME="$CATEGORY/$SUBCATEGORY"

		echo "<tr><td>$CATEGORYNAME</td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_reallyeditfilterlists_FILTERNAME_$FILTERNAME"_"FILTERDATA_$FILTERDATA"_"FILTERDATA2"_"$CATEGORYNAME"_"FILTERDATA3_activate_\" type=\"image\" class=\"images\" src=\"$ICON3\" value=\"\"><span>$CATEGORYNAME<br><br>$ADDSGLISTMSG</span></a></td></tr>"
	done
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	for CATEGORIES in `grep ^".Include</etc/e2guardian/lists/'$SEARCHTERM'/" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/'$FILENAME' | sed "s/>//g" | sed "s/<//g"`
	do
		CATEGORY=`echo "$CATEGORIES" | cut -d"/" -f'$COL1'`
		SUBCATEGORY=`echo "$CATEGORIES" | cut -d"/" -f'$COL2'`
		CATEGORYNAME="$CATEGORY"
		[ $SUBCATEGORY != '$FILTERTYPE' ] && CATEGORYNAME="$CATEGORY/$SUBCATEGORY"

		echo "<tr><td>$CATEGORYNAME</td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_reallyeditfilterlists_FILTERNAME_'$FILTERNAME'"_"FILTERDATA_'$FILTERDATA'"_"FILTERDATA2"_"$CATEGORYNAME"_"FILTERDATA3_deactivate_\" type=\"image\" class=\"images\" src=\"'$ICON2'\" value=\"\"><span>$CATEGORYNAME<br><br>'$REMOVEMSGLISTMSG'</span></a></td></tr>"
	done

	#Show inactive categories
	for CATEGORIES in `grep ^"#.Include</etc/e2guardian/lists/'$SEARCHTERM'/" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/'$FILENAME' | sed "s/>//g" | sed "s/<//g"`
	do
		CATEGORY=`echo "$CATEGORIES" | cut -d"/" -f'$COL1'`
		SUBCATEGORY=`echo "$CATEGORIES" | cut -d"/" -f'$COL2'`
		CATEGORYNAME="$CATEGORY"
		[ $SUBCATEGORY != '$FILTERTYPE' ] && CATEGORYNAME="$CATEGORY/$SUBCATEGORY"

		echo "<tr><td>$CATEGORYNAME</td><td><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_reallyeditfilterlists_FILTERNAME_'$FILTERNAME'"_"FILTERDATA_'$FILTERDATA'"_"FILTERDATA2"_"$CATEGORYNAME"_"FILTERDATA3_activate_\" type=\"image\" class=\"images\" src=\"'$ICON3'\" value=\"\"><span>$CATEGORYNAME<br><br>'$ADDSGLISTMSG'</span></a></td></tr>"
	done
'
fi
echo "</tbody></table></form>"
}

function reallyeditfilterlists {
echo `date`: e2g_filtergroups - $FILTERNAME $FILTERDATA3 $FILTERDATA2 by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

FILTERDATA2=`echo $FILTERDATA2 | sed 's/%2F/\//g'`
FILENAME=bannedsitelist
[ $FILTERDATA = urls ] && FILENAME=bannedurllist
[ $FILTERDATA = phraselists ] && FILENAME=bannedphraselist

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Get the line number of list
	LINENUM=`grep -n "/$FILTERDATA2" /etc/e2guardian/lists/filtergroups/$FILTERNAME/$FILENAME | cut -d: -f1 | sed -n 1,1p`

	#Modify config file
	if [ ! -z "$LINENUM" ]
	then
		[ $FILTERDATA3 = deactivate ] && sed -i "$LINENUM"s"/^.Include/#.Include/" /etc/e2guardian/lists/filtergroups/$FILTERNAME/$FILENAME 
		[ $FILTERDATA3 = activate ] && sed -i "$LINENUM"s"/^#.Include/.Include/" /etc/e2guardian/lists/filtergroups/$FILTERNAME/$FILENAME
	fi
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	#Get the line number of list
	LINENUM=`grep -n "/'$FILTERDATA2'" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/'$FILENAME' | cut -d: -f1 | sed -n 1,1p`
	#Modify config file
	if [ ! -z "$LINENUM" ]
	then
		[ '$FILTERDATA3' = deactivate ] && sed -i "$LINENUM"s"/^.Include/#.Include/" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/'$FILENAME'
		[ '$FILTERDATA3' = activate ] && sed -i "$LINENUM"s"/^#.Include/.Include/" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/'$FILENAME'
	fi
'
fi
activatechanges
ACTION=editfilterlists
}

function bannedextensionlists {
TITLE="$TITLE9"
HELPMSG="$HELPMSG9"
SUBTITLE="#Filter_Group_Options"
showtitle

#Show details for the group
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	source /etc/e2guardian/lists/filtergroups/$FILTERNAME/details
else
	source <(ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER cat /etc/e2guardian/lists/filtergroups/$FILTERNAME/details)
fi

echo "<form name=\"myform\" action=\"/cgi-bin/admin/e2g_filtergroups.cgi\" method=\"post\"><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"width: 180px;\">$FILTERNAMEMSG</td><td>$FILTERNAME</td></tr><tr><td style=\"width: 180px;\">$FILTERLABELMSG</td><td>$FILTERLABEL</td></tr>
<tr><td>$FILTERDESCMSG</td><td>$FILTERDESC</td></tr></tbody></table><br>"

#Show allowed extensions
echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"width: 90px;\"><b>$EXTENSIONMSG</b></td><td style=\"width: 300px;\"><b>$FILTERDESCMSG</b></td><td><b>$STATUSMSG</b></td></tr>"

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	for EXTENSIONS in `grep ^"#\." /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedextensionlist | sed "s/ /_/g"`
	do
		LINEDATA=`echo "$EXTENSIONS" | sed "s/_/ /g"`
		FILEEXTENSION=`echo $LINEDATA | sed "s/ //g" | cut -d"#" -f2 | sed "s/\.//g"`
		DESCRIPTION=`echo $LINEDATA | cut -d"#" -f3`
		[ ! -z $FILEEXTENSION ] && echo "<tr><td style=\"vertical-align:top\">$FILEEXTENSION</td><td>$DESCRIPTION</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedextensionlists_FILTERNAME_$FILTERNAME"_"FILTERDATA_$FILEEXTENSION"_"FILTERDATA2_activate_\" type=\"image\" class=\"images\" src=\"$ICON2\" value=\"\"><span>$FILEEXTENSION<br><br>$DENYFILEEXTMSG</span></a></td></tr>"
	done
	#Show denied extensions
	for EXTENSIONS in `grep ^"\." /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedextensionlist | sed "s/ /_/g"`
	do
		LINEDATA=`echo "$EXTENSIONS" | sed "s/_/ /g"`
		FILEEXTENSION=`echo $LINEDATA | sed "s/ //g" | cut -d"#" -f1 | sed "s/\.//g"`
		DESCRIPTION=`echo $LINEDATA | cut -d"#" -f2`
		[ ! -z $FILEEXTENSION ] && echo "<tr><td style=\"vertical-align:top\">$FILEEXTENSION</td><td>$DESCRIPTION</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedextensionlists_FILTERNAME_$FILTERNAME"_"FILTERDATA_$FILEEXTENSION"_"FILTERDATA2_deactivate_\" type=\"image\" class=\"images\" src=\"$ICON3\" value=\"\"><span>$FILEEXTENSION<br><br>$ALLOWFILEEXTMSG</span></a></td></tr>"
	done
else
	ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	for EXTENSIONS in `grep ^"#\." /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedextensionlist | sed "s/ /_/g"`
	do
		LINEDATA=`echo "$EXTENSIONS" | sed "s/_/ /g"`
		FILEEXTENSION=`echo $LINEDATA | sed "s/ //g" | cut -d"#" -f2 | sed "s/\.//g"`
		DESCRIPTION=`echo $LINEDATA | cut -d"#" -f3`
		[ ! -z $FILEEXTENSION ] && echo "<tr><td style=\"vertical-align:top\">$FILEEXTENSION</td><td>$DESCRIPTION</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedextensionlists_FILTERNAME_'$FILTERNAME'"_"FILTERDATA_$FILEEXTENSION"_"FILTERDATA2_activate_\" type=\"image\" class=\"images\" src=\"'$ICON2'\" value=\"\"><span>$FILEEXTENSION<br><br>'$DENYFILEEXTMSG'</span></a></td></tr>"
	done
	#Show denied extensions
	for EXTENSIONS in `grep ^"\." /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedextensionlist | sed "s/ /_/g"`
	do
		LINEDATA=`echo "$EXTENSIONS" | sed "s/_/ /g"`
		FILEEXTENSION=`echo $LINEDATA | sed "s/ //g" | cut -d"#" -f1 | sed "s/\.//g"`
		DESCRIPTION=`echo $LINEDATA | cut -d"#" -f2`
		[ ! -z $FILEEXTENSION ] && echo "<tr><td style=\"vertical-align:top\">$FILEEXTENSION</td><td>$DESCRIPTION</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedextensionlists_FILTERNAME_'$FILTERNAME'"_"FILTERDATA_$FILEEXTENSION"_"FILTERDATA2_deactivate_\" type=\"image\" class=\"images\" src=\"'$ICON3'\" value=\"\"><span>$FILEEXTENSION<br><br>'$ALLOWFILEEXTMSG'</span></a></td></tr>"
	done
'
fi
echo "</tbody></table></form>"
}

function modifybannedextensionlists {
echo `date`: e2g_filtergroups - $FILTERNAME $FILTERDATA $FILTERDATA2 by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Get the line number of list
	LINENUM=`grep -n -w "\.$FILTERDATA" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedextensionlist | cut -d: -f1 | sed -n 1,1p`

	if [ ! -z $LINENUM ]
	then
		[ $FILTERDATA2 = deactivate ] && sed -i "$LINENUM"s"/^.$FILTERDATA/#\.$FILTERDATA/" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedextensionlist
		[ $FILTERDATA2 = activate ] && sed -i "$LINENUM"s"/^#.$FILTERDATA/.$FILTERDATA/" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedextensionlist
	fi
else
	ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	#Get the line number of list
	LINENUM=`grep -n -w "\.'$FILTERDATA'" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedextensionlist | cut -d: -f1 | sed -n 1,1p`

	if [ ! -z $LINENUM ]
	then
		[ '$FILTERDATA2' = deactivate ] && sed -i "$LINENUM"s"/^.'$FILTERDATA'/#.'$FILTERDATA'/" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedextensionlist
		[ '$FILTERDATA2' = activate ] && sed -i "$LINENUM"s"/^#.'$FILTERDATA'/.'$FILTERDATA'/" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedextensionlist
	fi
'
fi
activatechanges
ACTION=bannedextensionlists
}

function bannedmimetypelists {
TITLE="$TITLE10"
HELPMSG="$HELPMSG10"
SUBTITLE="#Filter_Group_Options"
showtitle

#Show details for the group
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	source /etc/e2guardian/lists/filtergroups/$FILTERNAME/details
else
	source <(ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER cat /etc/e2guardian/lists/filtergroups/$FILTERNAME/details)
fi

echo "<form name=\"myform\" action=\"/cgi-bin/admin/e2g_filtergroups.cgi\" method=\"post\"><table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"width: 180px;\">$FILTERNAMEMSG</td><td>$FILTERNAME</td></tr><tr><td style=\"width: 180px;\">$FILTERLABELMSG</td><td>$FILTERLABEL</td></tr>
<tr><td>$FILTERDESCMSG</td><td>$FILTERDESC</td></tr></tbody></table><br>"

echo "<table class=\"standard\" style=\"text-align: left;\" border=\"0\" cellpadding=\"2\" cellspacing=\"2\"><tbody>
<tr><td style=\"width: 180px;\"><b>$MIMETYPEMSG</b></td><td><b>$STATUSMSG</b></td></tr>"


if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Show allowed mimetypes
	for MIMETYPE in `grep ^"#" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedmimetypelist | sed "s/#//g" | sed 1d | sort`
	do
		[ ! -z "$MIMETYPE" ] && echo "<tr><td style=\"vertical-align:top\">$MIMETYPE</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedmimetypes_FILTERNAME_$FILTERNAME"_"FILTERDATA_$MIMETYPE"_"FILTERDATA2_activate_\" type=\"image\" class=\"images\" src=\"$ICON2\" value=\"\"><span>$MIMETYPE<br><br>$DENYMIMETYPEMSG</span></a></td></tr>"
	done

	#Show denied mimetypes
	for MIMETYPE in `grep -v ^"#" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedmimetypelist | sed "s/#//g" | sed 1d | sort`
	do
		[ ! -z "$MIMETYPE" ] && echo "<tr><td style=\"vertical-align:top\">$MIMETYPE</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedmimetypes_FILTERNAME_$FILTERNAME"_"FILTERDATA_$MIMETYPE"_"FILTERDATA2_deactivate_\" type=\"image\" class=\"images\" src=\"$ICON3\" value=\"\"><span>$MIMETYPE<br><br>$ALLOWMIMETYPEMSG</span></a></td></tr>"
	done
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	#Show allowed mimetypes
	for MIMETYPE in `grep ^"#" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedmimetypelist | sed "s/#//g" | sed 1d | sort`
	do
		[ ! -z "$MIMETYPE" ] && echo "<tr><td style=\"vertical-align:top\">$MIMETYPE</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedmimetypes_FILTERNAME_'$FILTERNAME'"_"FILTERDATA_$MIMETYPE"_"FILTERDATA2_activate_\" type=\"image\" class=\"images\" src=\"'$ICON2'\" value=\"\"><span>$MIMETYPE<br><br>'$DENYMIMETYPEMSG'</span></a></td></tr>"
	done

	#Show denied mimetypes
	for MIMETYPE in `grep -v ^"#" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedmimetypelist | sed "s/#//g" | sed 1d | sort`
	do
		[ ! -z "$MIMETYPE" ] && echo "<tr><td style=\"vertical-align:top\">$MIMETYPE</td><td style=\"vertical-align:top\"><a class=\"info\" href=\"javascript:void(0)\"><input name=\"_ACTION_modifybannedmimetypes_FILTERNAME_'$FILTERNAME'"_"FILTERDATA_$MIMETYPE"_"FILTERDATA2_deactivate_\" type=\"image\" class=\"images\" src=\"'$ICON3'\" value=\"\"><span>$MIMETYPE<br><br>'$ALLOWMIMETYPEMSG'</span></a></td></tr>"
	done
'
fi
echo "</tbody></table></form>"
}

function modifybannedmimetypes {
FILTERDATA=`echo $FILTERDATA | sed 's/%2F/\//g'`

echo `date`: e2g_filtergroups - $FILTERNAME $FILTERDATA $FILTERDATA2 by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Get the line number of list
	LINENUM=`grep -n "$FILTERDATA" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedmimetypelist | cut -d: -f1 | sed -n 1,1p`

	if [ ! -z "$LINENUM" ]
	then
		[ "$FILTERDATA2" = deactivate ] && sed -i "$LINENUM"s"%^$FILTERDATA%#$FILTERDATA%" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedmimetypelist
		[ "$FILTERDATA2" = activate ] && sed -i "$LINENUM"s"%^#$FILTERDATA%$FILTERDATA%" /etc/e2guardian/lists/filtergroups/$FILTERNAME/bannedmimetypelist
	fi
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	#Get the line number of list
	LINENUM=`grep -n "'$FILTERDATA'" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedmimetypelist | cut -d: -f1 | sed -n 1,1p`

	if [ ! -z "$LINENUM" ]
	then
		[ "'$FILTERDATA2'" = deactivate ] && sed -i "$LINENUM"s"%^'$FILTERDATA'%#'$FILTERDATA'%" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedmimetypelist
		[ "'$FILTERDATA2'" = activate ] && sed -i "$LINENUM"s"%^#'$FILTERDATA'%'$FILTERDATA'%" /etc/e2guardian/lists/filtergroups/'$FILTERNAME'/bannedmimetypelist
	fi
'
fi
activatechanges
ACTION=bannedmimetypelists
}

function activatechanges {
if [ $PROXYSERVER = `hostname-fqdn` ]
then
e2guardian -g
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
e2guardian -g
'
fi
}

activatechanges restarte2guardian
function restarte2guardian {
#Restart e2guardian to activate any changes made.
if [ $PROXYSERVER = `hostname-fqdn` ]
then
	#Restart e2guardian
	source /opt/karoshi/serversetup/variables/distro
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_stop 1>/dev/null
	sleep 1
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_start 1>/dev/null
else
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $PROXYSERVER '
	#Restart e2guardian
	source /opt/karoshi/serversetup/variables/distro
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_stop 1>/dev/null
	sleep 1
	/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/e2guardian_start 1>/dev/null
'
fi
}

[ "$ACTION" = reallyeditlable ] && ( reallyeditlabels ; viewfilters )
[ "$ACTION" = add ] && addfiltergroup 
[ "$ACTION" = reallyadd ] && ( reallyaddfiltergroup ; viewfilters )
[ "$ACTION" = deletefiltergroup ] && deletefiltergroup
[ "$ACTION" = reallydelete ] && ( reallydelete ; viewfilters )
[ "$ACTION" = editfiltergroup ] && editfiltergroup
[ "$ACTION" = removegroup ] && ( removegroup ; editfiltergroup )
[ "$ACTION" = reallyaddgroup ] && ( reallyaddgroup ; editfiltergroup )
[ "$ACTION" = editfilterlists ] && editfilterlists
[ "$ACTION" = reallyeditfilterlists ] && ( reallyeditfilterlists ; editfilterlists )
[ "$ACTION" = bannedextensionlists ] && bannedextensionlists
[ "$ACTION" = modifybannedextensionlists ] && ( modifybannedextensionlists ; bannedextensionlists )
[ "$ACTION" = bannedmimetypelists ] && bannedmimetypelists
[ "$ACTION" = modifybannedmimetypes ] && ( modifybannedmimetypes ; bannedmimetypelists )
[ "$ACTION" = view ] && viewfilters
[ "$ACTION" = activatechanges ] && ( activatechanges ; viewfilters )

exit


