#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/email_add_alias_cgi
then
echo `date`: email_add_alias - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/email_add_alias_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/email_add_alias.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $email_add_alias_cgi'check' ]
then
echo `date`: email_add_alias - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: email_add_alias - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
USERNAME=`echo $* | cut -s -d: -f4`
ALIAS=`echo $* | cut -s -d: -f5`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: email_add_alias - Not called by email_add_alias.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: email_add_alias - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: email_add_alias - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $USERNAME'null' = null ]
then
echo `date`: email_add_alias - Blank username by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ $ALIAS'null' = null ]
then
echo `date`: email_add_alias - Blank alias by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: email_add_alias - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
############################
#Add alias
############################
echo `date`: email_add_alias - Adding $ALIAS as an alias "for"  $USERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

EMAILSERVER=`sed -n 1,1p /opt/karoshi/server_network/emailserver`

if [ `echo $EMAILSERVER'null' | sed 's/ //g'` = null ] 
then
echo `date`: email_over_quota_report - blank email server by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ $EMAILSERVER != $HOSTNAME ]
then
ssh -x -o PasswordAuthentication=no $EMAILSERVER '
#Check that alias path is not already in use
if [ `grep -c -w ^'$ALIAS' /etc/postfix/aliases` -gt 0 ]
then
exit 102
fi
echo '$ALIAS':"	""	"'$USERNAME' >> /etc/postfix/aliases
cat /etc/postfix/aliases | sort -u > /etc/postfix/aliases.$$
rm -f /etc/postfix/aliases
mv /etc/postfix/aliases.$$ /etc/postfix/aliases
newaliases
'
else
#Check that alias path is not already in use
if [ `grep -c -w ^$ALIAS /etc/postfix/aliases` -gt 0 ]
then
exit 102
fi
echo $ALIAS:"	""	"$USERNAME >> /etc/postfix/aliases
#Sort list
cat /etc/postfix/aliases | sort -u > /etc/postfix/aliases.$$
rm -f /etc/postfix/aliases
mv /etc/postfix/aliases.$$ /etc/postfix/aliases
newaliases
fi
