#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
#language
MESSAGELIMITMSG=$"Message Size Limit"
MAILBOXLIMITMSG=$"Mailbox Size Limit"
HELP1=$"Enter in the maximum size for each e-mail in megabytes."
HELP2=$"Enter in the maximum size for the inboxes in megabytes."
HELP3=$"The number of E-Mails in the queue to trigger an E-Mail queue warning."
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/email_limits_cgi
then
	echo `date`: email_limits_view - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/email_limits_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/admin/email_limits.cgi | cut -d' ' -f1`
[ -z "$Checksum" ] && Checksum=not_set
if [ $Checksum'check' != $email_limits_cgi'check' ]
then
	echo `date`: email_limits_view - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
	echo `date`: email_limits_view - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
REMOTE_USER=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f2`
RemoteCheckSum=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f3`
MOBILE=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f4`
WIDTH1=200
HELPCLASS="info"
if [ $MOBILE = yes ]
then
	WIDTH1=160
	HELPCLASS="info infoleft"
fi 
########################
#Check data
########################
if [ $RemoteCheckSum'check' != $Checksum'check' ]
then
	echo `date`: email_limits_view - Not called by email_limits_view.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$REMOTE_USER" ]
then
	echo `date`: email_limits_view - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
if [ -z "$REMOTE_ADDR" ]
then
	echo `date`: email_limits_view - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
	echo `date`: email_limits_view - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
echo `date`: email_limits_view - by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
############################
#View limits settings
############################
EMAILSERVER=`sed -n 1,1p /opt/karoshi/server_network/emailserver`

if [ -z "$EMAILSERVER" ] 
then
	echo `date`: email_over_quota_report - blank email server by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi



if [ "$EMAILSERVER" != `hostname-fqdn` ]
then
	ssh -x -o PasswordAuthentication=no $EMAILSERVER '
MESSAGELIMIT=`grep ^"message_size_limit =" /etc/postfix/main.cf | sed -n 1,1p | cut -d"=" -f2 | sed "s/ //g"`
MBOXLIMIT=`grep ^"mailbox_size_limit =" /etc/postfix/main.cf | sed -n 1,1p | cut -d"=" -f2 | sed "s/ //g"`
MAILWARN=$(grep "^MAILWARN=" /opt/karoshi/serversetup/modules/email/scripts/check_mail_queue | cut -d"=" -f2)
#Convert to megabytes
let MESSAGELIMIT=$MESSAGELIMIT/1024/1024
let MBOXLIMIT=$MBOXLIMIT/1024/1024

echo "<tr><td style=\"width: 180px;\">'$MESSAGELIMITMSG' (MB)</td><td><input required=\"required\" tabindex= \"1\" style=\"width: '$WIDTH1'px;\" value=\"$MESSAGELIMIT\" name=\"_MESSAGESIZE_\" maxlength=\"4\" size=\"4\" type=\"text\"></td><td><a class=\"'$HELPCLASS'\" target=\"_blank\" href=\"http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=E-Mail_Limits\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>'$HELP1'</span></a></td></tr>
<tr><td style=\"width: 180px;\">'$MAILBOXLIMITMSG' (MB)</td><td><input required=\"required\" tabindex= \"2\" style=\"width: '$WIDTH1'px;\" value=\"$MBOXLIMIT\" name=\"_MAILBOXSIZE_\" maxlength=\"4\" size=\"4\" type=\"text\"></td><td><a class=\"info\" target=\"_blank\" href=\"http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=E-Mail_Limits\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>'$HELP2'</span></a></td></tr>
<tr><td style=\"width: 180px;\">Mail Queue Threshold Warning</td><td><input required=\"required\" tabindex= \"3\" style=\"width: '$WIDTH1'px;\" value=\"$MAILWARN\" name=\"_MAILWARN_\" maxlength=\"4\" size=\"4\" type=\"text\"></td><td><a class=\"info\" target=\"_blank\" href=\"http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=E-Mail_Limits\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>'$HELP3'</span></a></td></tr>
"

'
else
	MESSAGELIMIT=`grep ^"message_size_limit =" /etc/postfix/main.cf | sed -n 1,1p | cut -d"=" -f2 | sed "s/ //g"`
	MBOXLIMIT=`grep ^"mailbox_size_limit =" /etc/postfix/main.cf | sed -n 1,1p | cut -d"=" -f2 | sed "s/ //g"`
	MAILWARN=$(grep "^MAILWARN=" /opt/karoshi/serversetup/modules/email/scripts/check_mail_queue| cut -d"=" -f2)
	#Convert to megabytes
	let MESSAGELIMIT=$MESSAGELIMIT/1024/1024
	let MBOXLIMIT=$MBOXLIMIT/1024/1024

	echo "<tr><td style=\"width: 180px;\">$MESSAGELIMITMSG (MB)</td><td><input required=\"required\" tabindex= \"1\" style=\"width: '$WIDTH1'px;\" value=\"$MESSAGELIMIT\" name=\"_MESSAGESIZE_\" maxlength=\"4\" size=\"4\" type=\"text\"></td><td><a class=\"$HELPCLASS\" target=\"_blank\" href=\"http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=E-Mail_Limits\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>$HELP1</span></a></td></tr>
<tr><td style=\"width: 180px;\">$MAILBOXLIMITMSG (MB)</td><td><input required=\"required\" tabindex= \"2\" style=\"width: '$WIDTH1'px;\" value=\"$MBOXLIMIT\" name=\"_MAILBOXSIZE_\" maxlength=\"4\" size=\"4\" type=\"text\"></td><td><a class=\"info\" target=\"_blank\" href=\"http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=E-Mail_Limits\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>$HELP2</span></a></td></tr>
<tr><td style=\"width: 180px;\">Mail Queue Threshold Warning</td><td><input required=\"required\" tabindex= \"3\" style=\"width: '$WIDTH1'px;\" value=\"$MAILWARN\" name=\"_MAILWARN_\" maxlength=\"4\" size=\"4\" type=\"text\"></td><td><a class=\"info\" target=\"_blank\" href=\"http://www.linuxschools.com/karoshi/documentation/wiki/index.php?title=E-Mail_Limits\"><img class=\"images\" alt=\"\" src=\"/images/help/info.png\"><span>$HELP3</span></a></td></tr>
"

fi
