#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/incident_log_add2_cgi
then
echo `date`: incident_log_add2 - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/incident_log_add2_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/incident_log_add2.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $incident_log_add2_cgi'check' ]
then
echo `date`: incident_log_add2 - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/incident_log_add2_cgi
then
echo `date`: incident_log_add2 - No tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/incident_log_add2_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/incident_log_add2.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $incident_log_add2_cgi'check' ]
then
echo `date`: incident_log_add - Incorrect tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: incident_log_add - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
DAY=`echo $* | cut -s -d: -f4`
MONTH=`echo $* | cut -s -d: -f5`
YEAR=`echo $* | cut -s -d: -f6`
HOUR=`echo $* | cut -s -d: -f7`
MINUTES=`echo $* | cut -s -d: -f8`
INCIDENT=`echo $* | cut -s -d: -f9`
ACTIONTAKEN=`echo $* | cut -s -d: -f10`
STUDENTS=`echo $* | cut -s -d: -f11`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: incident_log_add - Not called by incident_log_add2.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: incident_log_add - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: incident_log_add - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $DAY'null' = null ]
then
echo `date`: incident_log_add - Blank day by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ $MONTH'null' = null ]
then
echo `date`: incident_log_add - Blank month by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $YEAR'null' = null ]
then
echo `date`: incident_log_add - Blank year by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $HOUR'null' = null ]
then
echo `date`: incident_log_add - Blank hour by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $MINUTES'null' = null ]
then
echo `date`: incident_log_add - Blank minutes by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $INCIDENT'null' = null ]
then
echo `date`: incident_log_add - Blank incident by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $ACTIONTAKEN'null' = null ]
then
echo `date`: incident_log_add - Blank incident by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $STUDENTS'null' = null ]
then
echo `date`: incident_log_add - Blank students by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: incident_log_add - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Create log file
########################
[ -d /opt/karoshi/logs/incident_logs ] || mkdir -p /opt/karoshi/logs/incident_logs
chmod -R 0600 /opt/karoshi/logs
chmod -R u+X /opt/karoshi/logs
chown -R root.root /opt/karoshi/logs
########################
#Add incident to log files
########################
INCIDENT=`echo $INCIDENT | sed 's/+/ /g'`
ACTIONTAKEN=`echo $ACTIONTAKEN | sed 's/+/ /g'`
STUDENTS=`echo $STUDENTS | sed 's/+/ /g'`
STUDENT_ARRAY=( `echo $STUDENTS` )
STUDENT_ARRAY_COUNT=`echo ${#STUDENT_ARRAY[@]}`
COUNTER=0
while [ $COUNTER -le $STUDENT_ARRAY_COUNT ]
do
USERNAME=`echo ${STUDENT_ARRAY[$COUNTER]}`
if [ $USERNAME'null' != null ]
then
echo `date | sed 's/:/-/g'`:$DAY:$MONTH:$YEAR:$HOUR:$MINUTES:$INCIDENT:$ACTIONTAKEN:$STUDENTS >> /opt/karoshi/logs/incident_logs/$USERNAME
fi
let COUNTER=$COUNTER+1
done
exit
