#!/bin/bash
#Copyright (C) 2011 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/ksso_add2_cgi
then
echo `date`: ksso_add - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/ksso_add2_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/ksso_add2.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $ksso_add2_cgi'check' ]
then
echo `date`: ksso_add - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: ksso_add - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:%\n-+-'`
if [ $DATA'null' = null ]
then
echo `date`: ksso_add - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
ENTRYNAME=`echo "$DATA" | cut -s -d: -f4`
ICON=`echo "$DATA" | cut -s -d: -f5`
DESTINATION=`echo "$DATA" | cut -s -d: -f6`
LOGONPAGE=`echo "$DATA" | cut -s -d: -f7 | sed 's/%2F/\//g' | sed 's/%3A/:/g'`
DATA=`echo "$DATA" | cut -s -d: -f8-`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo `date`: ksso_add - Not called by ksso_add.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: ksso_add - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: ksso_add - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $ENTRYNAME'null' = null ]
then
echo `date`: ksso_add - Blank entryname by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ $LOGONPAGE'null' = null ]
then
echo `date`: ksso_add - Blank logonpage by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi

if [ $DESTINATION'null' = null ]
then
echo `date`: ksso_add - Blank destination by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: ksso_add - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

echo `date`: ksso_add - adding $ENTRYNAME "for" $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

[ ! -d /opt/karoshi/server_network/ksso/data/ ] && mkdir -p /opt/karoshi/server_network/ksso/data
[ ! -d /opt/karoshi/server_network/ksso/buttons/ ] && mkdir -p /opt/karoshi/server_network/ksso/buttons

#Sort out special chars in destination

DESTINATION=`echo $DESTINATION | sed 's/%3A/:/g' | sed 's/%2F/\//g' | sed 's/%3F/?/g'  | sed 's/%3D/=/g'`

echo "if [ \$SERVICE = $ENTRYNAME ]
then
echo '
<form action="$DESTINATION" method=\"post\" id=\"$ENTRYNAME\">" > /opt/karoshi/server_network/ksso/data/"$ENTRYNAME"


#Assign data to array
DATAARRAY=( `echo $DATA | sed 's/_FORMDATA_/ /g'` )
ARRAYCOUNT=${#DATAARRAY[@]}
#Process array
ARRAYCOUNTER=0
while [ $ARRAYCOUNTER -lt $ARRAYCOUNT ]
do
DATA=${DATAARRAY[$ARRAYCOUNTER]}
ADDENTRY=yes
[ `echo $DATA | grep -c EXCLUDE` -gt 0 ] && ADDENTRY=no
END_POINT=9
#Assign NAME
COUNTER=2
while [ $COUNTER -le $END_POINT ]
do
DATAHEADER=`echo $DATA | cut -s -d'_' -f$COUNTER`
if [ `echo $DATAHEADER'check'` = NAMEcheck ]
then
let COUNTER=$COUNTER+1
NAME=`echo $DATA | cut -s -d'_' -f$COUNTER`
NAME=`echo $NAME | sed 's/UNDERSCORE/_/g'`
break
fi
let COUNTER=$COUNTER+1
done
#Assign ID
COUNTER=2
while [ $COUNTER -le $END_POINT ]
do
DATAHEADER=`echo $DATA | cut -s -d'_' -f$COUNTER`
if [ `echo $DATAHEADER'check'` = IDcheck ]
then
let COUNTER=$COUNTER+1
ID=`echo $DATA | cut -s -d'_' -f$COUNTER`
ID=`echo $ID | sed 's/UNDERSCORE/_/g'`
break
fi
let COUNTER=$COUNTER+1
done

#Assign VALUE
COUNTER=2
while [ $COUNTER -le $END_POINT ]
do
DATAHEADER=`echo $DATA | cut -s -d'_' -f$COUNTER`
if [ `echo $DATAHEADER'check'` = VALUEcheck ]
then
let COUNTER=$COUNTER+1
VALUE=`echo $DATA | cut -s -d'_' -f$COUNTER | sed 's/UNDERSCORE/_/g'`
VALUE=`echo $VALUE | sed 's/UNDERSCORE/_/g'`
break
fi
let COUNTER=$COUNTER+1
done

#Add data to button
if [ $VALUE'null' != null ]
then
[ $VALUE = USERNAME ] && VALUE="'\$USERNAME'"
[ $VALUE = PASSWORD ] && VALUE="'\$PASSWORD'"
[ $VALUE = BROWSERSTRING ] && VALUE="'\$HTTP_USER_AGENT'" 
fi
if [ $ADDENTRY = yes ] && [ $NAME'null' != null ]
then
echo '<input type='hidden' name="'$NAME'" id="'$ID'" value="'$VALUE'">' >> /opt/karoshi/server_network/ksso/data/"$ENTRYNAME"
fi
let ARRAYCOUNTER=$ARRAYCOUNTER+1
done

echo "</form>
<script language=\"JavaScript\" type=\"text/javascript\">
<!--
document.getElementById("'"'$ENTRYNAME'"'").submit();
//-->
</script>
'
fi
" >> /opt/karoshi/server_network/ksso/data/"$ENTRYNAME"

echo '<form action="ksso_connect.cgi" method="post" target="_blank" name="form">
<a class="info" href="javascript:void(0)"><input name="_SERVICE_'$ENTRYNAME'_" type="image" class="images" src="/ksso/images/icons/'$ICON'" value=""></a></form>' > /opt/karoshi/server_network/ksso/buttons/"$ENTRYNAME"


KSSOSERVER=`sed -n 1,1p /opt/karoshi/server_network/kssoserver`


if [ ! -d /opt/karoshi/server_network/ksso/cgi ]
then
mkdir -p  /opt/karoshi/server_network/ksso/cgi
chmod 0700 /opt/karoshi/server_network/ksso/cgi
fi

#Add available entries to menu
cp -f /opt/karoshi/serversetup/modules/ksso/cgi/ksso_menu.cgi /opt/karoshi/server_network/ksso/cgi/
echo 'echo '\''<table class="standard" style="text-align: left;" border="0" cellpadding="10" cellspacing="10"><tbody><tr>'\''' >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
COUNTER=1
for ENTRIES in /opt/karoshi/server_network/ksso/buttons/*
do
ENTRY=`basename $ENTRIES`
echo 'echo '\''<td style="vertical-align: middle; text-align: center;">'\''' >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
echo "echo" "'" >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
cat /opt/karoshi/server_network/ksso/buttons/"$ENTRY" >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
echo "'" >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
echo 'echo '\''</td>'\''' >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
if [ $COUNTER = 3 ]
then
echo 'echo '\''</tr><tr>'\''' >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
COUNTER=1
else
let COUNTER=$COUNTER+1
fi
done
echo 'echo '\''</tr></tbody></table>'\''' >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi
echo "echo '</div></div></body></html>'" >> /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi

#Add available entries to connect
cp -f /opt/karoshi/serversetup/modules/ksso/cgi/ksso_connect.cgi /opt/karoshi/server_network/ksso/cgi/ksso_connect.cgi
echo >> /opt/karoshi/server_network/ksso/cgi/ksso_connect.cgi
cat /opt/karoshi/server_network/ksso/data/* >> /opt/karoshi/server_network/ksso/cgi/ksso_connect.cgi
echo "echo" \""</body></html>"\" >> /opt/karoshi/server_network/ksso/cgi/ksso_connect.cgi


source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/software

#Copy cgi files and icon to the ksso server
if [ $KSSOSERVER = `hostname-fqdn` ]
then
cp -f /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi /var/www/cgi-bin/ksso/
cp -f /opt/karoshi/server_network/ksso/cgi/ksso_connect.cgi /var/www/cgi-bin/ksso/
cp -f /opt/karoshi/serversetup/modules/ksso/images/icons/$ICON /var/www/html/ksso/images/icons/
chmod 0550 /var/www/cgi-bin/ksso/ksso_connect.cgi
chown root.$APACHEGROUP /var/www/cgi-bin/ksso/ksso_connect.cgi
chmod 0550 /var/www/cgi-bin/ksso/ksso_menu.cgi
chown root.$APACHEGROUP /var/www/cgi-bin/ksso/ksso_menu.cgi
chmod 0440 /var/www/html/ksso/images/icons/$ICON
chown root.$APACHEGROUP /var/www/html/ksso/images/icons/$ICON
else
scp /opt/karoshi/server_network/ksso/cgi/ksso_menu.cgi root@$KSSOSERVER:"/var/www/cgi-bin/ksso/" 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
scp /opt/karoshi/server_network/ksso/cgi/ksso_connect.cgi root@$KSSOSERVER:"/var/www/cgi-bin/ksso/" 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
scp /opt/karoshi/serversetup/modules/ksso/images/icons/"$ICON" root@$KSSOSERVER:"/var/www/html/ksso/images/icons/" 2>> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
ssh -o PasswordAuthentication=no -o ConnectTimeout=3 $KSSOSERVER '
chmod 0550 /var/www/cgi-bin/ksso/ksso_connect.cgi
chown root.'$APACHEGROUP' /var/www/cgi-bin/ksso/ksso_connect.cgi
chmod 0550 /var/www/cgi-bin/ksso/ksso_menu.cgi
chown root.'$APACHEGROUP' /var/www/cgi-bin/ksso/ksso_menu.cgi
chmod 0440 /var/www/html/ksso/images/icons/'$ICON'
chown root.'$APACHEGROUP' /var/www/html/ksso/images/icons/'$ICON'
'
fi
exit

