#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/linux_client_upload_skel3_cgi
then
echo `date`: linux_client_upload_skel - No Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/linux_client_upload_skel3_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/admin/linux_client_upload_skel3.cgi | cut -d' ' -f1`
[ $Checksum'null' = null ] && Checksum=not_set
if [ $Checksum'check' != $linux_client_upload_skel3_cgi'check' ]
then
echo `date`: linux_client_upload_skel - Incorrect Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: linux_client_upload_skel - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f2`
RemoteCheckSum=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f3`
LINUXVERSION=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f4`
SKELFILENAME=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f5 | sed 's/1234567890/ /g'`
########################
#Check data
########################
if [ $RemoteCheckSum'check' != $Checksum'check' ]
then
echo `date`: linux_client_upload_skel - Not called by linux_client_upload_skel.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: linux_client_upload_skel - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: linux_client_upload_skel - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $LINUXVERSION'null' = null ]
then
echo `date`: linux_client_upload_skel - Blank linuxversion by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ `echo $SKELFILENAME'null' | sed 's/ //g'` = null ]
then
echo `date`: linux_client_upload_skel - Blank skelfilename by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
#Check to see that only one file exists
if [ `ls -1 /var/www/karoshi/skel_upload/ | wc -l` != 1 ]
then
echo `date`: linux_client_upload_skel - incorrect file upload >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
#Check to see that file names match
if [ `ls -1 /var/www/karoshi/skel_upload/ | sed 's/ //g'` != `echo "$SKELFILENAME" | sed 's/ //g'` ]
then
echo `date`: linux_client_upload_skel - uploaded file does not match skefilename >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: linux_client_upload_skel - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
echo `date`: linux_client_upload_skel - uploading $SKELFILENAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
#Copy in skel archive
cp -f /var/www/karoshi/skel_upload/"$SKELFILENAME" /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/skel.tar.gz
chmod 0644 /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/skel.tar.gz

rm -f -R /var/www/karoshi/skel_upload

exit
