#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/linux_client_set_repository2_cgi
then
echo `date`: linux_client_set_repository - No Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/linux_client_set_repository2_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/admin/linux_client_set_repository2.cgi | cut -d' ' -f1`
[ $Checksum'null' = null ] && Checksum=not_set
if [ $Checksum'check' != $linux_client_set_repository2_cgi'check' ]
then
echo `date`: linux_client_set_repository - Incorrect Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

#########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: linux_client_set_repository - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | tr -cd 'A-Za-z0-9\._:\%+-' | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | tr -cd 'A-Za-z0-9\._:\%+-' | cut -s -d: -f2`
RemoteCheckSum=`echo $* | tr -cd 'A-Za-z0-9\._:\%+-' | cut -s -d: -f3`
LINUXVERSION=`echo $* | tr -cd 'A-Za-z0-9\._:\%+-' | cut -s -d: -f4`
URI=`echo $* | tr -cd 'A-Za-z0-9\._:\%+-' | cut -s -d: -f5 | sed 's/%2F/\//g' | sed 's/%3A/:/g'`
DISTRIBUTION=`echo $* | tr -cd 'A-Za-z0-9\._:\%+-' | cut -s -d: -f6 | sed 's/%2F/\//g'`
SECTIONS=`echo $* | tr -cd 'A-Za-z0-9\._:\%+-' | cut -s -d: -f7 | sed 's/+/ /g'`

########################
#Check data
########################
if [ $RemoteCheckSum'check' != $Checksum'check' ]
then
echo `date`: linux_client_set_repository - Not called by linux_client_set_repository.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: linux_client_set_repository - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: linux_client_set_repository - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $LINUXVERSION'null' = null ]
then
echo `date`: linux_client_set_repository - Blank linuxversion by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ $URI'null' = null ]
then
echo `date`: linux_client_set_repository - Blank uri by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $DISTRIBUTION'null' = null ]
then
echo `date`: linux_client_set_repository - Blank distribution by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $SECTIONS'null' = null ]
then
echo `date`: linux_client_set_repository - Blank sections by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: linux_client_set_repository - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
#Log repository change
echo `date`: linux_client_set_repository - setting for $LINUXVERSION by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
echo `date`: URI: $URI DISTRIBUTION: $DISTRIBUTION SECTIONS: $SECTIONS >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
#Write repository data to file
echo '#'PCLINUXOS apt repository > /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/sources.list
echo rpm $URI $DISTRIBUTION $SECTIONS >> /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/sources.list
chmod 0644 /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/sources.list
exit
