#!/bin/bash
#Copyright (C) 2007  Paul Sharrad 

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit

SSHWARNMSG="SSH is not enabled for this server."

########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/linux_client_view_install_list3_cgi
then
echo `date`: linux_client_view_install_list - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/linux_client_view_install_list3_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/linux_client_view_install_list3.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $linux_client_view_install_list3_cgi'check' ]
then
echo `date`: linux_client_view_install_list - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: linux_client_view_install_list - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
LINUXVERSION=`echo $* | cut -s -d: -f4`
INSTALLARRAY=( `echo $* | cut -s -d: -f5- | sed 's/:/ /g'` )
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo `date`: linux_client_view_install_list - Not called by linux_client_view_install_list2.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: linux_client_view_install_list - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: linux_client_view_install_list - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $LINUXVERSION'null' = null ]
then
echo `date`: linux_client_view_install_list - Blank linuxversion >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: linux_client_view_install_list - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ $INSTALLARRAY'null' = null ]
then
echo `date`: linux_client_view_install_list - No sites chosen by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

INSTALLCOUNT=`echo ${#INSTALLARRAY[@]}`
COUNTER=1
#Log event
while [ $COUNTER -lt $INSTALLCOUNT ]
do
SOFTWARE=`echo ${INSTALLARRAY[$COUNTER]}`
echo `date`: linux_client_view_install_list - removing $SOFTWARE by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
let COUNTER=$COUNTER+1
done

COUNTER=1
while [ $COUNTER -lt $INSTALLCOUNT ]
do
#Delete software from list
SOFTWARE=`echo ${INSTALLARRAY[$COUNTER]}`
#Get line number of software
SOFTWARELINENUMBER=`grep -n ^$SOFTWARE /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/install_list | cut -d: -f1`
if [ $SOFTWARELINENUMBER"null" != null ]
then
sed -i $SOFTWARELINENUMBER"d" /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/install_list
fi
let COUNTER=$COUNTER+1
done
#Remove blank lines
sed -i '/^$/d' /var/lib/samba/netlogon/linuxclient/$LINUXVERSION/install_list
exit
