#!/bin/bash
#Copyright (C) 2007 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/logout_cgi
then
echo `date`: logout - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/logout_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/logout.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $logout_cgi'check' ]
then
echo `date`: logout - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/logout_cgi
then
echo `date`: logout - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/logout_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/logout.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $logout_cgi'check' ]
then
echo `date`: logout - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: logout - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: logout - Not called by logout.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: logout - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: logout - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` = 1 ]
then
KAROSHI_STATUS=admin
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` = 1 ]
then
KAROSHI_STATUS=tech
fi

if [ $KAROSHI_STATUS != tech ] && [ $KAROSHI_STATUS != admin ]
then
echo `date`: logout - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi



########################
#Create logout folder
########################
if [ ! -d /var/www/cgi-bin_karoshi/logout/$REMOTE_USER ]
then
mkdir -p /var/www/cgi-bin_karoshi/logout/$REMOTE_USER
chown root.apache_karoshi /var/www/cgi-bin_karoshi/logout/$REMOTE_USER
chmod 0750 /var/www/cgi-bin_karoshi/logout/$REMOTE_USER
fi

########################
#Copy in redirect cgi
########################
cp -f /opt/karoshi/serversetup/web_controls/cgi/pdc/admin/logout2.cgi /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/
chmod 0750 /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/logout2.cgi
chown root.apache_karoshi /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/logout2.cgi
########################
#Add in .htaccess file
########################
echo AuthType Basic > /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
echo SSLRequireSSL >> /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
echo ErrorDocument 401 /cgi-bin/blank.cgi >> /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
echo ErrorDocument 403 /cgi-bin/access_forbidden.cgi >> /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
echo AuthName \"Karoshi Web Control\" >> /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
if [ $KAROSHI_STATUS = admin ]
then
echo AuthUserFile /opt/karoshi/web_controls/web_access_admin >> /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
else
echo AuthUserFile /opt/karoshi/web_controls/web_access_tech >> /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
fi
echo require user access_denied >> /var/www/cgi-bin_karoshi/logout/$REMOTE_USER/.htaccess
echo `date`: logout - by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
