#!/bin/bash
#Copyright (C) 2011 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/module_ssh_access_cgi
then
echo `date`: module_ssh_access - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/module_ssh_access_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/module_ssh_access.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $module_ssh_access_cgi'check' ]
then
echo `date`: module_ssh_access - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: module_ssh_access - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:%\n-+-'`
if [ $DATA'null' = null ]
then
echo `date`: module_ssh_access - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
RESTRICT=`echo "$DATA" | cut -s -d: -f4`
SERVERNAME=`echo "$DATA" | cut -s -d: -f5`
RESTRICTTYPE=`echo "$DATA" | cut -s -d: -f6`


if [ $RESTRICTTYPE != null ]
then
if [ $RESTRICTTYPE = TCPIP ]
then
RESTRICT=`echo $RESTRICT | tr -cd '0-9.'`
else
RESTRICT=`echo $RESTRICT | sed 's/%3A/-/g' | tr -cd 'A-Za-z0-9\-:' | sed 's/^/~/g'`
fi
fi

########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo `date`: module_ssh_access - Not called by module_ssh_access.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: module_ssh_access - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: module_ssh_access - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $RESTRICT'null' = null ]
then
echo `date`: module_ssh_access - Setting up $SERVERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
else
echo `date`: module_ssh_access - Setting up $SERVERNAME "for" $RESTRICT by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
fi
########################
#Language
########################
LANGCHOICE=englishuk
STYLESHEET=defaultstyle.css
[ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
[ -f /opt/karoshi/serversetup/language/$LANGCHOICE/modules/ssh_access/setupssh ] || LANGCHOICE=englishuk
source /opt/karoshi/serversetup/language/$LANGCHOICE/modules/ssh_access/setupssh
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/all ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/all

source /opt/karoshi/serversetup/variables/distro
#########################
#Modify shorewall rules
#########################

MODCHECK=`grep -c pdc_ssh_rule /etc/shorewall/rules`
if [ $MODCHECK = 0 ]
then
echo "<li>"$RESTRICT $OPENPORTMSG"</li>"
LINENUM=`grep -n 'LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE' /etc/shorewall/rules | cut -d: -f1`
if [ $RESTRICT'null' != null ]
then
sed $LINENUM'c'\ACCEPT'	'net:$RESTRICT'	'fw'	'tcp'	'22'	'-'#'pdc_ssh_rule /etc/shorewall/rules > /etc/shorewall/rulestemp
else
sed $LINENUM'c'\ACCEPT'	'fw'	'tcp'	'22'	'-'#'pdc_ssh_rule /etc/shorewall/rules > /etc/shorewall/rulestemp
fi
rm -f /etc/shorewall/rules
mv /etc/shorewall/rulestemp /etc/shorewall/rules
echo '#'LAST LINE -- ADD YOUR ENTRIES BEFORE THIS ONE -- DO NOT REMOVE >> /etc/shorewall/rules
fi

if [ $MODCHECK != 0 ]
then
LINENUM=`grep -n '#pdc_ssh_rule' /etc/shorewall/rules | cut -d: -f1`
if [ $RESTRICT'null' != null ]
then
sed $LINENUM'c'\ACCEPT'	'net:$RESTRICT'	'fw'	'tcp'	'22'	'-'#'pdc_ssh_rule /etc/shorewall/rules > /etc/shorewall/rulestemp
else
sed $LINENUM'c'\ACCEPT'	'net'	'fw'	'tcp'	'22'	'-'#'pdc_ssh_rule /etc/shorewall/rules > /etc/shorewall/rulestemp
fi
rm -f /etc/shorewall/rules
mv /etc/shorewall/rulestemp /etc/shorewall/rules
fi
######################
#Restart shorewall
######################
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_stop
sleep 0.5
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/shorewall_start


######################
#Add ssh line to hosts.allow
######################
MODCHECK=`grep -c sshd':' /etc/hosts.allow`
if [ $MODCHECK = 0 ]
then
if [ $RESTRICT'null' != null ]
then
echo sshd: 127.0.0.1 , $RESTRICT >> /etc/hosts.allow
fi
fi

#############################
#copy in config file
#############################
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ssh_stop
mv /etc/ssh/sshd_config /etc/ssh/sshd_configbackup
cp -f /opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/configfiles/sshd_config /etc/ssh/
sleep .5

#Create ssh folder
[ ! -d /root/.ssh ] && mkdir /root/.ssh
chmod 0700 /root/.ssh
#Generate keys ??
/opt/karoshi/serversetup/distro/$DISTROCHOICE/extra_server/scripts/generate_ssh_keys

#Check that timeout has been set
TIMEOUTSTATUS=`grep -c '#''   'ConnectTimeout' '0 /etc/ssh/ssh_config`
if [ $TIMEOUTSTATUS != 0 ]
then
sed -i 's/#   ConnectTimeout 0/ConnectTimeout 4/g' /etc/ssh/ssh_config
fi
#Check that StrictHostkeychecking is set to no
HOSTKEYSTATUS=`grep -c '#''   'StrictHostKeyChecking' 'ask /etc/ssh/ssh_config`
if [ $HOSTKEYSTATUS != 0 ]
then
sed -i 's/#   StrictHostKeyChecking ask/StrictHostKeyChecking no/g' /etc/ssh/ssh_config
fi

#Stop ssh if it is running
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ssh_status
if [ `echo $?` = 0 ]
then
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ssh_stop
sleep 1
fi

#Start ssh
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/control_services/ssh_start

#############################
#Ensure that ssh is running on boot
#############################
/opt/karoshi/serversetup/distro/$DISTROCHOICE/scripts/startonboot/ssh

#############################
#Add role information
#############################
[ ! -d /opt/karoshi/server_network/servers/$SERVERNAME ] && mkdir -p /opt/karoshi/server_network/servers/$SERVERNAME
if [ $RESTRICT'null' = null ]
then
echo $ROLE"<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/remote_ssh
else
RESTRICT=`echo $RESTRICT | sed 's/~//g' | sed 's/-/:/g'` 
echo $ROLE $RESTRICT"<br>" > /opt/karoshi/server_network/servers/$SERVERNAME/remote_ssh
fi
exit

