#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ -z "$LOG_DATE" ] && exit

SSHWARNMSG="SSH is not enabled for this server."
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/staff_checksums/printers_cgi
then
	echo `date`: printers - No Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
source /opt/karoshi/web_controls/checksums/staff_checksums/printers_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/staff/printers.cgi | cut -d' ' -f1`
[ -z "$Checksum" ] && Checksum=not_set
if [ $Checksum'check' != $printers_cgi'check' ]
then
	echo `date`: printers_staff - Incorrect Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
	echo `date`: printers_staff - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi
REMOTE_USER=`echo $* | tr -cd 'A-Za-z0-9\._:%/+-' | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | tr -cd 'A-Za-z0-9\._:%/+-' | cut -s -d: -f2`
RemoteCheckSum=`echo $* | tr -cd 'A-Za-z0-9\._:%/+-' | cut -s -d: -f3`
MOBILE=`echo $* | tr -cd 'A-Za-z0-9\._:%/+-' | cut -s -d: -f4`
PRINTER=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f5`
########################
#Check data
########################
if [ $RemoteCheckSum'check' != $Checksum'check' ]
then
	echo `date`: printers_staff - Not called by printers_staff.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

if [ -z "$REMOTE_ADDR" ]
then
	echo `date`: printers_staff - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
	exit 101
fi

#Get Printer location data
STARTLINENO=`grep -n ^--start-- /var/lib/samba/netlogon/printers.txt | cut -d: -f1`
let STARTLINENO=$STARTLINENO+1

NOOFLINES=`cat /var/lib/samba/netlogon/printers.txt | wc -l`
LOCATIONDATA=`sed -n $STARTLINENO,$NOOFLINES'p' /var/lib/samba/netlogon/printers.txt`
LOCATIONDATA=`echo $LOCATIONDATA | sed 's/ /123SPACE123/g'`

####################
#Show printers
####################
PRINTSERVER=`sed -n 1,1p /opt/karoshi/server_network/printserver`
if [ $PRINTSERVER = `hostname-fqdn` ]
then
	/opt/karoshi/"useful scripts"/printer_info staff $LOCATIONDATA $MOBILE $PRINTER
else
	ssh -x -o PasswordAuthentication=no $PRINTSERVER '/opt/karoshi/"useful scripts"/printer_info staff '$LOCATIONDATA' '$MOBILE' '$PRINTER'' 2>&1
fi
