#!/bin/bash
#Copyright (C) 2007 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk

LOG_DATE=$(date +%F)
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/printer_driver_gen_cgi
then
	echo "$(date): printer_driver_gen - No MD5Checksum" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"
	exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/printer_driver_gen_cgi
Checksum=$(sha256sum /var/www/cgi-bin_karoshi/admin/printer_driver_gen.cgi | cut -d' ' -f1)
[ -z "$Checksum" ] && Checksum=not_set
if [ "$Checksum"'check' != "$printer_driver_gen_cgi"'check' ]
then
	echo "$(date): printer_driver_gen - Incorrect MD5Checksum" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"
	exit 101
fi
########################
#Get variables
########################
numArgs="$#"
if [ "$numArgs" != 1 ]
then
	echo "$(date): printer_driver_gen2 - incorrect number of arguments" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"
	exit 101
fi
REMOTE_USER=$(echo "$*" | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f1)
REMOTE_ADDR=$(echo "$*" | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f2)
RemoteCheckSum=$(echo "$*" | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f3)
MOBILE=$(echo "$*" | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f4)
########################
#Check data
########################
if [ "$RemoteCheckSum"'check' != "$Checksum"'check' ]
then
	echo "$(date): printer_driver_gen2 - Not called by printer_driver_gen2.cgi" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"
	exit 101
fi
if [ -z "$REMOTE_USER" ]
then
	echo "$(date): printer_driver_gen2 - Blank remote user" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"
	exit 101
fi
if [ -z "$REMOTE_ADDR" ]
then
	echo "$(date): printer_driver_gen2 - Blank remote tcpip address" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"
	exit 101
fi
if [[ $(grep -c ^"$REMOTE_USER:" /opt/karoshi/web_controls/web_access_admin) != 1 ]]
then
	echo "$(date): printer_driver_gen2 - access denied to $REMOTE_USER from $REMOTE_ADDR" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"
	exit 101
fi

echo "$(date): printer_driver_gen2 - Restarting from $REMOTE_ADDR by $REMOTE_USER from $REMOTE_ADDR" >> "/opt/karoshi/logs/karoshi_web_management/$LOG_DATE"

source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/"$DISTROCHOICE"/all/software
source /opt/karoshi/server_network/domain_information/domain_name


LDAPPASS=$(sed -n 1,1p /etc/ldap.secret)
PRINTSERVER=$(sed -n 1,1p /opt/karoshi/server_network/printserver)


if [[ "$PRINTSERVER" != $(hostname-fqdn) ]]
then
	#Make sure 64bit drivers are on print server
	scp -r /opt/karoshi/serversetup/modules/printserver/cupsdrivers64 root@"$PRINTSERVER:/opt/karoshi/serversetup/modules/printserver/"

	#Check to see if the print server is a domain member or an additional domain controller
	#For a dc we have to use cupsaddsmb -H $HOSTNAME -U Administrator%$LDAPPASS -a -v 2>&1
	#For a domain member cupsaddsmb -H $HOSTNAME -U root%$LDAPPASS -a -v 2>&1

	#set root password to be the same as the administrator password
	samba-tool user setpassword root --newpassword="$LDAPPASS" 1>/dev/null


	#Get windows dlls

	ssh "$PRINTSERVER" '
	if [ ! -d /usr/share/cups/drivers ]
	then
		mkdir /usr/share/cups/drivers
		cp /opt/karoshi/serversetup/modules/printserver/cupsdrivers/* /usr/share/cups/drivers/
	fi
	[ ! -e /usr/share/cups/drivers/pscript5.dll ] && exit 101'
	if [ "$?" = 101 ]
	then
		scp /home/applications/cups_print/pscript5.dll root@"$PRINTSERVER"/usr/share/cups/drivers/
		scp /home/applications/cups_print/ps5ui.dll root@"$PRINTSERVER"/usr/share/cups/drivers/
		scp /home/applications/cups_print/pscript.hlp root@"$PRINTSERVER"/usr/share/cups/drivers/
		scp /home/applications/cups_print/pscript.ntf root@"$PRINTSERVER"/usr/share/cups/drivers/
	fi

	ssh "$PRINTSERVER" '
	if [ ! -d /usr/share/cups/drivers/x64 ]
	then
		mkdir /usr/share/cups/drivers/x64
		cp /opt/karoshi/serversetup/modules/printserver/cupsdrivers64/cups6.inf /usr/share/cups/drivers/x64/
	fi
	[ ! -e /usr/share/cups/drivers/x64/pscript5.dll ] && exit 101
	'
	if [ "$?" = 101 ]
	then
		scp /home/applications/cups_print/x64/PSCRIPT5.DLL root@"$PRINTSERVER"/usr/share/cups/drivers/x64/pscript5.dll
		scp /home/applications/cups_print/x64/PS5UI.DLL root@"$PRINTSERVER"/usr/share/cups/drivers/x64/ps5ui.dll
		scp /home/applications/cups_print/x64/PSCRIPT.HLP root@"$PRINTSERVER"/usr/share/cups/drivers/x64/pscript.hlp
		scp /home/applications/cups_print/x64/PSCRIPT.NTF root@"$PRINTSERVER"/usr/share/cups/drivers/x64/pscript.ntf
	fi

	ssh -x -o PasswordAuthentication=no "$PRINTSERVER" '
	chmod 0644 -R /usr/share/cups/drivers
	chmod u+X,g+X,o+X /usr/share/cups/drivers
	if [ ! -f /usr/share/cups/drivers/pscript5.dll ] && [ ! -f /usr/share/cups/drivers/x64/pscript5.dll ]
	then
		exit 103
	fi
	'
	if [ "$?" = 103 ]
	then
		exit 103
	fi

	echo '<br><b>'$"Generating Windows Printer Drivers"'</b><br>'
	[ "$MOBILE" = no ] && echo '<pre style="font-size: 10pt; font-family:Arial, Times, Georgia, serif">'
	ssh -x -o PasswordAuthentication=no "$PRINTSERVER" '
	#Make sure /var/lib/samba/printers/ exists and has correct permissions
	[ ! -d /var/lib/samba/printers/x64/ ] && mkdir -p /var/lib/samba/printers/x64/
	chown root.itadmin -R /var/lib/samba/printers 
	chmod -R 0664 /var/lib/samba/printers
	chmod u+X,g+X,o+X -R /var/lib/samba/printers

	#Check to see if this server is a domain member or a dc
	REGENUSER=Administrator
	[ `grep -c "#karoshi_member_server" /etc/samba/smb.conf` -gt 0 ] && REGENUSER=root
	[ ! -d /opt/karoshi/server_network/printers/windows/stop_driver_gen ] && mkdir -p /opt/karoshi/server_network/printers/windows/stop_driver_gen

	QUEUELIST=`diff <(lpstat -a | cut -d" " -f1 | sort) <(ls -1 /opt/karoshi/server_network/printers/windows/stop_driver_gen | sort) | grep "<" | sed "s/^< //g"`
	if [ ! -z "$QUEUELIST" ]
	then
		cupsaddsmb -H $HOSTNAME -U $REGENUSER%'"$LDAPPASS"' -v $QUEUELIST 2>&1
		#Copy in cups6.inf
		cp -f /usr/share/cups/drivers/x64/cups6.inf /var/lib/samba/printers/x64/
	fi
	'
	[ "$MOBILE" = no ] && echo "</pre>"
else

	######################
	#Copy cups drivers from \\pdc\applications
	######################
	if [ ! -d /usr/share/cups/drivers ]
	then
		mkdir /usr/share/cups/drivers
		cp /opt/karoshi/serversetup/modules/printserver/cupsdrivers/* /usr/share/cups/drivers/
	fi

	[ ! -d /usr/share/cups/drivers/x64 ] && mkdir /usr/share/cups/drivers/x64
	cp /opt/karoshi/serversetup/modules/printserver/cupsdrivers64/cups6.inf /usr/share/cups/drivers/x64/

	#Get windows dlls
	if ! test -e /usr/share/cups/drivers/pscript5.dll
	then
		if [ -f /home/applications/cups_print/pscript5.dll ]
		then

			cp -f /home/applications/cups_print/pscript5.dll /usr/share/cups/drivers/
			cp -f /home/applications/cups_print/ps5ui.dll /usr/share/cups/drivers/
			cp -f /home/applications/cups_print/pscript.hlp /usr/share/cups/drivers/
			cp -f /home/applications/cups_print/pscript.ntf /usr/share/cups/drivers/
			chmod 0644 -R /usr/share/cups/drivers
			chmod u+X,g+X,o+X /usr/share/cups/drivers
		fi
	fi
	#Get windows dlls x64
	if ! test -e /usr/share/cups/drivers/x64/pscript5.dll
	then
		if [ -f /home/applications/cups_print/x64/PSCRIPT5.DLL ]
		then

			cp -f /home/applications/cups_print/x64/PSCRIPT5.DLL /usr/share/cups/drivers/x64/pscript5.dll
			cp -f /home/applications/cups_print/x64/PS5UI.DLL /usr/share/cups/drivers/x64/ps5ui.dll
			cp -f /home/applications/cups_print/x64/PSCRIPT.HLP /usr/share/cups/drivers/x64/pscript.hlp
			cp -f /home/applications/cups_print/x64/PSCRIPT.NTF /usr/share/cups/drivers/x64/pscript.ntf
			chmod 0644 -R /usr/share/cups/drivers
			chmod u+X,g+X,o+X /usr/share/cups/drivers
		fi
	fi

	#Exit if printer drivers are not there
	if [ ! -f /usr/share/cups/drivers/pscript5.dll ] && [ ! -f /usr/share/cups/drivers/x64/pscript5.dll ]
	then
		exit 103
	fi
	#Delete existing drives
	#rm -f -R /var/lib/samba/printers/COLOR
	#rm -f -R /var/lib/samba/printers/IA64
	#rm -f -R /var/lib/samba/printers/W32ALPHA
	#rm -f -R /var/lib/samba/printers/W32MIPS
	#rm -f -R /var/lib/samba/printers/W32PPC
	#rm -f -R /var/lib/samba/printers/W32X86
	#rm -f -R /var/lib/samba/printers/WIN40
	#rm -f -R /var/lib/samba/printers/x64
	#Generate drivers
	echo '<br><b>'$"Generating Windows Printer Driverssdff"'</b><br><br>'
	[ "$MOBILE" = no ] && echo '<pre style="font-size: 10pt; font-family:Arial, Times, Georgia, serif">'

	#Make sure /var/lib/samba/printers/ exists and has correct permissions
	[ ! -d /var/lib/samba/printers/x64/ ] && mkdir -p /var/lib/samba/printers/x64/
	chown root.itadmin -R /var/lib/samba/printers
	chmod -R 0664 /var/lib/samba/printers
	chmod u+X,g+X,o+X -R /var/lib/samba/printers

	#Generate printer drivers
	[ ! -d /opt/karoshi/server_network/printers/windows/stop_driver_gen ] && mkdir -p /opt/karoshi/server_network/printers/windows/stop_driver_gen
	QUEUELIST=$(diff <(lpstat -a | cut -d" " -f1 | sort) <(ls -1 /opt/karoshi/server_network/printers/windows/stop_driver_gen | sort) | grep "<" | sed "s/^< //g")
	if [ ! -z "$QUEUELIST" ]
	then
		echo about to genrate printers to "$HOSTNAME""<br>"
		cupsaddsmb -H "$HOSTNAME" -U Administrator%"$LDAPPASS" -v "$QUEUELIST" 2>&1
		#Copy in cups.inf
		cp -f /usr/share/cups/drivers/x64/cups6.inf /var/lib/samba/printers/x64/
	fi
	[ "$MOBILE" = no ] && echo "</pre>"
fi
exit 0
