#!/bin/bash
#Copyright (C) 2007 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_change_timeout_cgi
then
echo `date`: remote_management_change_timeout - No Admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_change_timeout_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/admin/remote_management_change_timeout.cgi | cut -d' ' -f1`
[ $Checksum'null' = null ] && Checksum=not_set
if [ $Checksum'check' != $remote_management_change_timeout_cgi'check' ]
then
echo `date`: remote_management_change_timeout - Incorrect Admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/remote_management_change_timeout_cgi
then
echo `date`: remote_management_change_timeout - No tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/remote_management_change_timeout_cgi
Checksum2=`sha256sum /var/www/cgi-bin_karoshi/tech/remote_management_change_timeout.cgi | cut -d' ' -f1`
[ $Checksum2'null' = null ] && Checksum=not_set
if [ $Checksum2'check' != $remote_management_change_timeout_cgi'check' ]
then
echo `date`: remote_management_change_timeout - Incorrect tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: remote_management_change_timeout - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f2`
RemoteCheckSum=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f3`
TIMEOUT=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f4`
NOTIMEOUT=`echo $* | tr -cd 'A-Za-z0-9\._:\-' | cut -s -d: -f5`
########################
#Check data
########################
if [ $RemoteCheckSum'number' != $Checksum'number' ] && [ $RemoteCheckSum'number' != $Checksum2'number' ]
then
echo `date`: remote_management_change_timeout - Not called by remote_management_change_timeout.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: remote_management_change_timeout - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: remote_management_change_timeout - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $TIMEOUT'null' = null ]
then
echo `date`: remote_management_change_timeout - Blank timeout by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: remote_management_change_timeout - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
#########################
#Change timeout
#########################
#TIMEOUT
if [ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ]
then
LINENUMBER=`grep -n ^TIMEOUT= /opt/karoshi/web_controls/user_prefs/$REMOTE_USER | cut -d: -f1`
if [ $LINENUMBER'null' != null ]
then
#Delete variable
sed -i $LINENUMBER'd' /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
fi
#Delete empty lines
 sed -i '/^$/d' /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
fi
#Convert timeout time to seconds
let TIMEOUT=$TIMEOUT*60
#NOTIMEOUT
if [ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ]
then
LINENUMBER=`grep -n ^NOTIMEOUT= /opt/karoshi/web_controls/user_prefs/$REMOTE_USER | cut -d: -f1`
if [ $LINENUMBER'null' != null ]
then
#Delete variable
sed -i $LINENUMBER'd' /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
fi
#Delete empty lines
 sed -i '/^$/d' /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
fi
#Add variable
echo TIMEOUT=$TIMEOUT >> /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
if [ $NOTIMEOUT'null' != null ]
then
echo NOTIMEOUT=$NOTIMEOUT >> /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
fi
chmod 0640 /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
chown root.apache_karoshi /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
exit
