#!/bin/bash
#Copyright (C) 2007 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_change_global_theme2_cgi
then
echo `date`: remote_management_change_global_theme - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/remote_management_change_global_theme2_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/remote_management_change_global_theme2.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $remote_management_change_global_theme2_cgi'check' ]
then
echo `date`: remote_management_change_global_theme - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: remote_management_change_global_theme - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
THEMECHOICE=`echo $* | cut -s -d: -f4`
THEMECHOICE=`echo $THEMECHOICE.css`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo `date`: remote_management_change_global_theme - Not called by remote_management_change_global_theme.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: remote_management_change_global_theme - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: remote_management_change_global_theme - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $THEMECHOICE'null' = null ]
then
echo `date`: remote_management_change_global_theme - Blank firstname by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ ! -f /var/www/html_karoshi/css/$THEMECHOICE ]
then
echo `date`: remote_management_change_global_theme - no cgi theme for $THEMECHOICE by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: remote_management_change_global_theme - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
#####################
#Change theme for the web management
#####################
if [ -f /opt/karoshi/web_controls/global_prefs ]
then
LINENUMBER=`grep -n ^STYLESHEET= /opt/karoshi/web_controls/global_prefs | cut -d: -f1`
if [ $LINENUMBER'null' != null ]
then
#Delete variable
sed -i $LINENUMBER'd' /opt/karoshi/web_controls/global_prefs
fi
#Delete empty lines
 sed -i '/^$/d' /opt/karoshi/web_controls/global_prefs
fi
#Add variable
echo STYLESHEET=$THEMECHOICE >> /opt/karoshi/web_controls/global_prefs
chmod 0640 /opt/karoshi/web_controls/global_prefs
chown root.apache_karoshi /opt/karoshi/web_controls/global_prefs
exit
