#!/bin/bash
#Copyright (C) 2007 Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
[ $LOG_DATE'null' = null ] && exit
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/staff_checksums/request_new_users_cgi
then
echo `date`: request_new_users - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/staff_checksums/request_new_users_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/staff/request_new_users.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $request_new_users_cgi'check' ]
then
echo `date`: request_new_users - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi


########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: request_new_users - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:%\n-+-'`
if [ $DATA'null' = null ]
then
echo `date`: request_new_users - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
MYUSERNAME=`echo "$DATA" | cut -s -d: -f4`

FORENAME1=`echo "$DATA" | cut -s -d: -f5`
SURNAME1=`echo "$DATA" | cut -s -d: -f6`
GROUP1=`echo "$DATA" | cut -s -d: -f7`
ADNO1=`echo "$DATA" | cut -s -d: -f8`

FORENAME2=`echo "$DATA" | cut -s -d: -f9`
SURNAME2=`echo "$DATA" | cut -s -d: -f10`
GROUP2=`echo "$DATA" | cut -s -d: -f11`
ADNO2=`echo "$DATA" | cut -s -d: -f12`

FORENAME3=`echo "$DATA" | cut -s -d: -f13`
SURNAME3=`echo "$DATA" | cut -s -d: -f14`
GROUP3=`echo "$DATA" | cut -s -d: -f15`
ADNO3=`echo "$DATA" | cut -s -d: -f16`

FORENAME4=`echo "$DATA" | cut -s -d: -f17`
SURNAME4=`echo "$DATA" | cut -s -d: -f18`
GROUP4=`echo "$DATA" | cut -s -d: -f19`
ADNO4=`echo "$DATA" | cut -s -d: -f20`

FORENAME5=`echo "$DATA" | cut -s -d: -f21`
SURNAME5=`echo "$DATA" | cut -s -d: -f22`
GROUP5=`echo "$DATA" | cut -s -d: -f23`
ADNO5=`echo "$DATA" | cut -s -d: -f24`

FORENAME6=`echo "$DATA" | cut -s -d: -f25`
SURNAME6=`echo "$DATA" | cut -s -d: -f26`
GROUP6=`echo "$DATA" | cut -s -d: -f27`
ADNO6=`echo "$DATA" | cut -s -d: -f28`

FORENAME7=`echo "$DATA" | cut -s -d: -f29`
SURNAME7=`echo "$DATA" | cut -s -d: -f30`
GROUP7=`echo "$DATA" | cut -s -d: -f31`
ADNO7=`echo "$DATA" | cut -s -d: -f32`

FORENAME8=`echo "$DATA" | cut -s -d: -f33`
SURNAME8=`echo "$DATA" | cut -s -d: -f34`
GROUP8=`echo "$DATA" | cut -s -d: -f35`
ADNO8=`echo "$DATA" | cut -s -d: -f36`

FORENAME9=`echo "$DATA" | cut -s -d: -f37`
SURNAME9=`echo "$DATA" | cut -s -d: -f38`
GROUP9=`echo "$DATA" | cut -s -d: -f39`
ADNO9=`echo "$DATA" | cut -s -d: -f40`

FORENAME10=`echo "$DATA" | cut -s -d: -f41`
SURNAME10=`echo "$DATA" | cut -s -d: -f42`
GROUP10=`echo "$DATA" | cut -s -d: -f43`
ADNO10=`echo "$DATA" | cut -s -d: -f44`

########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo the remote md5 is $REMOTE_MD5 
echo `date`: request_new_users - Not called by request_new_users.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $MYUSERNAME'null' = null ]
then
echo `date`: request_new_users - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: request_new_users - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

#Check that user adding the data is a member of staff
MYPRIGROUP=`id -g -n $MYUSERNAME`
if [ $MYPRIGROUP != staff ] && [ $MYPRIGROUP != officestaff ] && [ $MYPRIGROUP != itadmin ] && [ $MYPRIGROUP != tech ]
then
echo `date`: request_new_users - $MYUSERNAME is not a member of staff from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi


[ -f /opt/karoshi/web_controls/global_prefs ] && source /opt/karoshi/web_controls/global_prefs
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/user/request_new_users ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/user/request_new_users

#Do something with the data!

if [ ! -d /opt/karoshi/user_requests/new_users ]
then
mkdir -p /opt/karoshi/user_requests/new_users ]
chmod 0750 /opt/karoshi/user_requests/new_users
chown root.apache_karoshi /opt/karoshi/user_requests/new_users
fi
SESSIONNAME=`date +%s`.$$

[ $FORENAME1'null' != null ] && echo $FORENAME1:$SURNAME1:$GROUP1:$ADNO1:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.1
[ $FORENAME2'null' != null ] && echo $FORENAME2:$SURNAME2:$GROUP2:$ADNO2:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.2
[ $FORENAME3'null' != null ] && echo $FORENAME3:$SURNAME3:$GROUP3:$ADNO3:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.3
[ $FORENAME4'null' != null ] && echo $FORENAME4:$SURNAME4:$GROUP4:$ADNO4:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.4
[ $FORENAME5'null' != null ] && echo $FORENAME5:$SURNAME5:$GROUP5:$ADNO5:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.5
[ $FORENAME6'null' != null ] && echo $FORENAME6:$SURNAME6:$GROUP6:$ADNO6:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.6
[ $FORENAME7'null' != null ] && echo $FORENAME7:$SURNAME7:$GROUP7:$ADNO7:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.7
[ $FORENAME8'null' != null ] && echo $FORENAME8:$SURNAME8:$GROUP8:$ADNO8:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.8
[ $FORENAME9'null' != null ] && echo $FORENAME9:$SURNAME9:$GROUP9:$ADNO9:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.9
[ $FORENAME10'null' != null ] && echo $FORENAME10:$SURNAME10:$GROUP10:$ADNO10:$MYUSERNAME: > /opt/karoshi/user_requests/new_users/$SESSIONNAME.10

#Add web management alert
/opt/karoshi/serversetup/web_controls/scripts/web_management_warn add request_new_users /cgi-bin/admin/request_new_users_fm.cgi "$NEWREQUESTMSG" webwarning1.gif

exit $CHANGE_PASS_STATUS
