#!/bin/bash
#Copyright (C) 2011 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jsharrad@karoshi.org.uk

#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/set_default_page_cgi
then
echo `date`: set_default_page - No admin Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/set_default_page_cgi
Checksum=`sha256sum /var/www/cgi-bin_karoshi/admin/set_default_page.cgi | cut -d' ' -f1`
[ $Checksum'null' = null ] && Checksum=not_set
if [ $Checksum'check' != $set_default_page_cgi'check' ]
then
echo `date`: set_default_page - Incorrect admin Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/set_default_page_cgi
then
echo `date`: set_default_page - No tech Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/set_default_page_cgi
Checksum2=`sha256sum /var/www/cgi-bin_karoshi/tech/set_default_page.cgi | cut -d' ' -f1`
[ $Checksum2'null' = null ] && Checksum2=not_set
if [ $Checksum2'check' != $set_default_page_cgi'check' ]
then
echo `date`: set_default_page - Incorrect tech Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: set_default_page - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-'`
if [ $DATA'null' = null ]
then
echo `date`: set_default_page - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
RemoteCheckSum=`echo "$DATA" | cut -s -d: -f3`
DEFAULTPAGE=`echo "$DATA" | cut -s -d: -f4`

########################
#Check data
########################
if [ $RemoteCheckSum'check' != $Checksum'check' ] && [ $RemoteCheckSum'check' != $Checksum2'check' ]
then
echo `date`: set_default_page - Not called by set_default_page.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: set_default_page - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: set_default_page - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $DEFAULTPAGE'null' = null ]
then
echo `date`: set_default_page set to $DEFAULTPAGE  by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

#####################
#Change default page for user
#####################

echo `date`: set_default_page -  by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

if [ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ]
then
LINENUMBER=`grep -n ^DEFAULTPAGE= /opt/karoshi/web_controls/user_prefs/$REMOTE_USER | cut -d: -f1`
if [ $LINENUMBER'null' != null ]
then
#Delete variable
sed -i $LINENUMBER'd' /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
fi
#Delete empty lines
 sed -i '/^$/d' /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
fi
#Add variable
echo DEFAULTPAGE=$DEFAULTPAGE >> /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
chmod 0640 /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
chown root.apache_karoshi /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
exit

