#!/bin/bash
#Copyright (C) 2012 Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`

########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/update_karoshi_upload_cgi
then
echo `date`: update_karoshi_upload - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/update_karoshi_upload2_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/update_karoshi_upload2.cgi | cut -d' ' -f1`

[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $update_karoshi_upload2_cgi'check' ]
then
echo `date`: update_karoshi_upload - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: update_karoshi_upload - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-'`
if [ $DATA'null' = null ]
then
echo `date`: update_karoshi_upload - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`

########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo `date`: update_karoshi_upload - Not called by update_karoshi_upload2.cgi  >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: update_karoshi_upload - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: update_karoshi_upload - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] 
then
echo `date`: update_karoshi_upload - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ ! -d /var/www/karoshi/karoshi_patches ]
then
echo `date`: update_karoshi_upload - no upload folder by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

##########################
#Language
##########################
LANGCHOICE=englishuk
STYLESHEET=defaultstyle.css
[ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/system/update_karoshi ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/system/update_karoshi
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/all ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/all

[ ! -d /opt/karoshi/updates ] && mkdir -p /opt/karoshi/updates

#Assign patch name and sig name.

cd /var/www/karoshi/karoshi_patches


PATCHNAME=`ls *.sh | sed -n 1,1p | tr -cd 'A-Za-z0-9\._:\-'`
SIGNAME=`ls *.sig | sed -n 1,1p | tr -cd 'A-Za-z0-9\._:\-'`

if [ -z "$PATCHNAME" ]
then
echo `date`: update_karoshi_upload - the patchname has not been assigned by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 102
fi
if [ -z "$SIGNAME" ]
then
echo `date`: update_karoshi_upload - the signature name has not been assigned by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 103
fi

#Copy the files
[ -f /var/www/karoshi/karoshi_patches/"$PATCHNAME" ] && cp -f /var/www/karoshi/karoshi_patches/"$PATCHNAME" /opt/karoshi/updates/
[ -f /var/www/karoshi/karoshi_patches/"$SIGNAME" ] && cp -f /var/www/karoshi/karoshi_patches/"$SIGNAME" /opt/karoshi/updates/
rm -f -R /var/www/karoshi/karoshi_patches/

#Make sure that files are there
if [ ! -f /opt/karoshi/updates/"$PATCHNAME" ]
then
echo `date`: update_karoshi_upload - the patch file was not uploaded correctly by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 102
fi

if [ ! -f /opt/karoshi/updates/"$SIGNAME" ]
then
echo `date`: update_karoshi_upload - the signature "file" was not uploaded correctly by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 103
fi

#Verify patch
gpg /opt/karoshi/updates/"$SIGNAME"
GPGSTATUS=`echo $?`
#echo checking /opt/karoshi/updates/"$SIGNAME"
#echo status is $GPGSTATUS
if [ $GPGSTATUS = 0 ]
then
echo `date`: update_karoshi_upload - applying "$PATCHNAME" by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
chmod 0700 /opt/karoshi/updates/"$PATCHNAME"
echo '<pre style="font-size: 10pt; font-family:Arial, Times, Georgia, serif">'
/opt/karoshi/updates/"$PATCHNAME"
echo '</pre>'
#Add this patchname to the completed jobs list

[ ! -d /opt/karoshi/logs/karoshi_updates ] && mkdir -p /opt/karoshi/logs/karoshi_updates
echo '<tr><td>'$PATCHNAME'<\td><td>'$HOSTNAME'<\td><td>'`date`'</td></tr>' >> /opt/karoshi/logs/karoshi_updates/$PATCHNAME

else
echo $VERIFYERRORMSG
exit 104
fi
exit


