#!/bin/bash
#Copyright (C) 2009 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/view_acceptable_use_authorisations_cgi
then
echo `date`: view_acceptable_use_authorisations - No admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/view_acceptable_use_authorisations_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/view_acceptable_use_authorisations.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $view_acceptable_use_authorisations_cgi'check' ]
then
echo `date`: view_acceptable_use_authorisations - Incorrect admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/view_acceptable_use_authorisations_cgi
then
echo `date`: view_acceptable_use_authorisations - No tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/view_acceptable_use_authorisations_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/view_acceptable_use_authorisations.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $view_acceptable_use_authorisations_cgi'check' ]
then
echo `date`: view_acceptable_use_authorisations - Incorrect tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: view_acceptable_use_authorisations - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-'`
if [ $DATA'null' = null ]
then
echo `date`: view_acceptable_use_authorisations - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
USERNAME=`echo "$DATA" | cut -s -d: -f4`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: view_acceptable_use_authorisations - Not called by view_acceptable_use_authorisations.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: view_acceptable_use_authorisations - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: view_acceptable_use_authorisations - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $USERNAME'null' = null ]
then
echo `date`: view_acceptable_use_authorisations - Blank username by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: view_acceptable_use_authorisations - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

echo `date`: view_acceptable_use_authorisations - authorising $USERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

#Get creation data
PENDING_USER_DATA=`sed -n 1,1p /opt/karoshi/acceptable_use_authorisations/pending/$USERNAME`
USER_CREATOR=`echo $PENDING_USER_DATA | cut -d, -f2`
CREATION_DATE=`echo $PENDING_USER_DATA | cut -d, -f3`

[ -f /opt/karoshi/acceptable_use_authorisations/pending/$USERNAME ] && rm -f /opt/karoshi/acceptable_use_authorisations/pending/$USERNAME
smbpasswd -e $USERNAME 1>/dev/null

#Get the primary group of the user

PRI_GROUP=`id -g -n $USERNAME`

if [ ! -f /opt/karoshi/acceptable_use_authorisations/approved_users ]
then
touch /opt/karoshi/acceptable_use_authorisations/approved_users
chmod 0640 /opt/karoshi/acceptable_use_authorisations/approved_users
chown root.apache_karoshi /opt/karoshi/acceptable_use_authorisations/approved_users
fi

#Add to the approved list
if [ `grep -c -w $USERNAME /opt/karoshi/acceptable_use_authorisations/approved_users` = 0 ]
then
echo $USERNAME,$CREATION_DATE,$PRI_GROUP,$USER_CREATOR,$REMOTE_USER,`date +%d-%m-%Y` >> /opt/karoshi/acceptable_use_authorisations/approved_users
fi

#Check warning messages
if [ `ls -1 /opt/karoshi/acceptable_use_authorisations/pending | wc -l` -lt 1 ]
then
/opt/karoshi/serversetup/web_controls/scripts/web_management_warn delete acceptable_use_authorisations
fi
exit

