#!/bin/bash
#Copyright (C) 2007 Paul Sharrad
#This program is free software; you can redistribute it and/or
#modify it under the terms of the GNU General Public License
#as published by the Free Software Foundation; either version 2
#of the License, or (at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program; if not, write to the Free Software
#Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/web_management_upload_files_select_cgi
then
echo `date`: web_management_upload_files - No Admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/web_management_upload_files_select_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/web_management_upload_files_select.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $web_management_upload_files_select_cgi'check' ]
then
echo `date`: web_management_upload_files - Incorrect Admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/web_management_upload_files_select_cgi
then
echo `date`: web_management_upload_files - No Tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/web_management_upload_files_select_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/web_management_upload_files_select.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $web_management_upload_files_select_cgi'check' ]
then
echo `date`: web_management_upload_files - Incorrect Tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: web_management_upload_files - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
UPLOADFOLDER=`echo $* | cut -s -d: -f4`
UPLOADID=`echo $* | cut -s -d: -f5`
WEBSERVER=`echo $* | cut -s -d: -f6`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: web_management_upload_files - Not called by web_management_upload_files.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: web_management_upload_files - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: web_management_upload_files - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $UPLOADFOLDER'null' = null ]
then
echo `date`: web_management_upload_files - Blank upload folder >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $UPLOADID'null' = null ]
then
echo `date`: web_management_upload_files - Blank upload id >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ $WEBSERVER'null' = null ]
then
echo `date`: web_management_upload_files - Blank webserver by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: web_management_upload_files - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

UPLOADFOLDER=`echo $UPLOADFOLDER | sed 's/UNDERSCORE/_/g'`

########################
#Move files
########################
mv /var/www/karoshi/webfiles /var/www/karoshi/webfiles.$UPLOADID
########################
#Check that process id is correct
########################
if [ `sed -n 1,1p /var/www/karoshi/webfiles.$UPLOADID/web_management_upload_id` != $UPLOADID ]
then
echo '<b>'$ERRORMSG4'</b><br>'
echo `date`: web_management_upload_files - file overwrite "for" $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
#Remove process id file
rm -f /var/www/karoshi/webfiles.$UPLOADID/web_management_upload_id
#Log files to be copied
for UPLOADEDFILE in /var/www/karoshi/webfiles.$UPLOADID/*
do
FILENAME=`basename $UPLOADEDFILE`
#Replace spaces with underscores
FILENAME=`echo $FILENAME | sed "s/ /_/g"`
echo `date`: web_management_upload_files $FILENAME uploaded to $UPLOADFOLDER on $WEBSERVER by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
done

########################
#Copy in files
########################
if [ $WEBSERVER != $HOSTNAME ]
then
#Create tar archive
tar -z -c -f /var/www/karoshi/webfiles$UPLOADID.tar.gz icons /var/www/karoshi/webfiles.$UPLOADID/ 1>/dev/null 2>/dev/null
#Transfer archive to webserver
scp /var/www/karoshi/webfiles$UPLOADID.tar.gz root@$WEBSERVER:"/opt/karoshi/.tempdata"
#Delete tar archive on pdc
rm -f /var/www/karoshi/webfiles$UPLOADID.tar.gz
ssh -x -o PasswordAuthentication=no $WEBSERVER '
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/software
[ ! -d /var/www/html/webfiles/'$UPLOADFOLDER'/ ] && mkdir -p /var/www/html/webfiles/'$UPLOADFOLDER'/
#Extract archive
cd /
tar -xzf /opt/karoshi/.tempdata/webfiles'$UPLOADID'.tar.gz 1>/dev/null 2>/dev/null
#Delete archive
rm -f /opt/karoshi/.tempdata/webfiles'$UPLOADID'.tar.gz
#Copy files to web folder
for UPLOADEDFILE in /var/www/karoshi/webfiles.'$UPLOADID'/*
do
FILENAME=`basename $UPLOADEDFILE`
#Replace spaces with underscores
FILENAME=`echo $FILENAME | sed "s/ /_/g"`
if [ $FILENAME"null" != null ]
then
#Copy file and change permissions
cp -f $UPLOADEDFILE /var/www/html/webfiles/'$UPLOADFOLDER'/
chown root.$APACHEGROUP /var/www/html/webfiles/'$UPLOADFOLDER'/$FILENAME
chmod 0440 /var/www/html/webfiles/'$UPLOADFOLDER'/$FILENAME
fi
done
#Remove uploaded folder
rm -f -R /var/www/karoshi/webfiles.'$UPLOADID'/
'
else
source /opt/karoshi/serversetup/variables/distro
source /opt/karoshi/serversetup/distro/$DISTROCHOICE/all/software
[ ! -d /var/www/html/webfiles/$UPLOADFOLDER/ ] && mkdir -p /var/www/html/webfiles/$UPLOADFOLDER/
#Copy files to web folder
for UPLOADEDFILE in /var/www/karoshi/webfiles.$UPLOADID/*
do
FILENAME=`basename $UPLOADEDFILE`
#Replace spaces with underscores
FILENAME=`echo $FILENAME | sed "s/ /_/g"`
#Copy file and change permissions
if [ $FILENAME"null" != null ]
then
cp -f $UPLOADEDFILE /var/www/html/webfiles/$UPLOADFOLDER/
chown root.$APACHEGROUP /var/www/html/webfiles/$UPLOADFOLDER/$FILENAME
chmod 0440 /var/www/html/webfiles/$UPLOADFOLDER/$FILENAME
fi
done
fi
#######################
#Remove upload folder
#######################
rm -f -R /var/www/karoshi/webfiles.$UPLOADID/
exit
