#!/bin/bash
#Copyright (C) 2007 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/web_management_delete_files_cgi
then
echo `date`: web_management_delete_files - No Admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/web_management_delete_files_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/web_management_delete_files.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $web_management_delete_files_cgi'check' ]
then
echo `date`: web_management_delete_files - Incorrect Admin MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if ! test -f /opt/karoshi/web_controls/checksums/tech_checksums/web_management_delete_files_cgi
then
echo `date`: web_management_delete_files - No Tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/tech_checksums/web_management_delete_files_cgi
MD5SUM2=`md5sum /var/www/cgi-bin_karoshi/tech/web_management_delete_files.cgi | cut -d' ' -f1`
[ $MD5SUM2'null' = null ] && MD5SUM2=not_set
if [ $MD5SUM2'check' != $web_management_delete_files_cgi'check' ]
then
echo `date`: web_management_delete_files - Incorrect Tech MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: web_management_delete_files - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
WEBSERVER=`echo $* | cut -s -d: -f4`
UPLOADFOLDER=`echo $* | cut -s -d: -f5`
DELETEARRAY=( `echo $* | cut -s -d: -f6- | sed 's/:/ /g'` )
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ] && [ $REMOTE_MD5'check' != $MD5SUM2'check' ]
then
echo `date`: web_management_delete_files - Not called by web_management_delete_files.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: web_management_delete_files - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: web_management_delete_files - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $WEBSERVER'null' = null ]
then
echo `date`: web_management_delete_files - Blank webserver by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $UPLOADFOLDER'null' = null ]
then
echo `date`: web_management_delete_files - Blank upload folder  by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $DELETEARRAY'null' = null ]
then
echo `date`: web_management_delete_files - Blank upload id >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: web_management_delete_files - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

LANGCHOICE=englishuk
STYLESHEET=defaultstyle.css
[ -f /opt/karoshi/web_controls/user_prefs/$REMOTE_USER ] && source /opt/karoshi/web_controls/user_prefs/$REMOTE_USER
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/web/view_delete_files ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/web/view_delete_files
[ -f /opt/karoshi/web_controls/language/$LANGCHOICE/all ] || LANGCHOICE=englishuk
source /opt/karoshi/web_controls/language/$LANGCHOICE/all
echo '<b>'$TITLE' : /var/www/html/webfiles/'$UPLOADFOLDER'</b><br><br>'
UPLOADFOLDER=`echo $UPLOADFOLDER | sed 's/UNDERSCORE/_/g'`

DELETECOUNT=`echo ${#DELETEARRAY[@]}`
[ $DELETECOUNT = 1 ] && exit 102

COUNTER=1
while [ $COUNTER -lt $DELETECOUNT ]
do
DELETEFILE=`echo ${DELETEARRAY[$COUNTER]} | sed 's/UNDERSCORE/_/g'`
#Log file deletion
echo `date`: web_management_delete_files - deleting $DELETEFILE by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
echo $DELETEMSG2 $DELETEFILE'<br>'

#Delete the file
if [ $WEBSERVER != `hostname-fqdn` ]
then
ssh -x -o PasswordAuthentication=no $WEBSERVER '
rm -f /var/www/html/webfiles/'$UPLOADFOLDER'/'$DELETEFILE'
'
else
rm -f /var/www/html/webfiles/$UPLOADFOLDER/$DELETEFILE
fi
let COUNTER=$COUNTER+1
done
exit
