#!/bin/bash
#Copyright (C) 2007 Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 1 ]
then
echo `date`: web_management_create_folder_list - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo $* | cut -s -d: -f1`
REMOTE_ADDR=`echo $* | cut -s -d: -f2`
REMOTE_MD5=`echo $* | cut -s -d: -f3`
SERVERNAME=`echo $* | cut -s -d: -f4`
########################
#Check data
########################
if [ -z $REMOTE_USER ]
then
echo `date`: web_management_create_folder_list - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ -z $REMOTE_ADDR ]
then
echo `date`: web_management_create_folder_list - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ -z $SERVERNAME ]
then
echo `date`: web_management_create_folder_list - Blank web server by $REMOTE_USER from $REMOTE_ADDRESS >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ] && [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_tech` != 1 ]
then
echo `date`: web_management_create_folder_list - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi


########################
#Create folder list
########################
echo `date`: web_management_create_folder_list by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
if [ $SERVERNAME != `hostname-fqdn` ]
then
ssh -x -o PasswordAuthentication=no $SERVERNAME '
ls -l --time-style="long-iso" /var/www/html | egrep "^d" | sed "s/ * / /g" | cut -d" " -f8 | sed "s/^/<option>\/var\/www\/html\//"g | sed "s/$/<\/option>/g"
'
else
ls -l --time-style="long-iso" /var/www/html | egrep "^d" | sed "s/ * / /g" | cut -d" " -f8 | sed "s/^/<option>\/var\/www\/html\//g" | sed "s/$/<\/option>/g"
fi
exit
