#!/bin/bash
#Copyright (C) 2007  Paul Sharrad

#This file is part of Karoshi Server.
#
#Karoshi Server is free software: you can redistribute it and/or modify
#it under the terms of the GNU Affero General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#Karoshi Server is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU Affero General Public License for more details.
#
#You should have received a copy of the GNU Affero General Public License
#along with Karoshi Server.  If not, see <http://www.gnu.org/licenses/>.

#
#The Karoshi Team can be contacted at: 
#mpsharrad@karoshi.org.uk
#jharris@karoshi.org.uk
#aball@karoshi.org.uk
#
#Website: http://www.karoshi.org.uk
LOG_DATE=`date +%F`
########################
#Check md5checksum
########################
if ! test -f /opt/karoshi/web_controls/checksums/admin_checksums/windows_client_allow_roaming_profile_cgi
then
echo `date`: windows_client_allow_roaming_profile - No MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
source /opt/karoshi/web_controls/checksums/admin_checksums/windows_client_allow_roaming_profile_cgi
MD5SUM=`md5sum /var/www/cgi-bin_karoshi/admin/windows_client_allow_roaming_profile.cgi | cut -d' ' -f1`
[ $MD5SUM'null' = null ] && MD5SUM=not_set
if [ $MD5SUM'check' != $windows_client_allow_roaming_profile_cgi'check' ]
then
echo `date`: windows_client_allow_roaming_profile - Incorrect MD5Checksum >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
########################
#Get variables
########################
numArgs=$#
if [ $numArgs != 0 ]
then
echo `date`: windows_client_allow_roaming_profile - incorrect number of arguments >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:%\n-+'`
if [ $DATA'null' = null ]
then
echo `date`: windows_client_allow_roaming_profile - no data >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
USERNAME=`echo "$DATA" | cut -s -d: -f4`
########################
#Check data
########################
if [ $REMOTE_MD5'check' != $MD5SUM'check' ]
then
echo `date`: windows_client_allow_roaming_profile - Not called by windows_client_allow_roaming_profile.cgi >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_USER'null' = null ]
then
echo `date`: windows_client_allow_roaming_profile - Blank remote user >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $REMOTE_ADDR'null' = null ]
then
echo `date`: windows_client_allow_roaming_profile - Blank remote tcpip address >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi
if [ $USERNAME'null' = null ]
then
echo `date`: windows_client_allow_roaming_profile - Blank username by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit
fi

#Check to see that this user does not already have a roaming profile
if [ -d /home/applications/profiles/$USERNAME ]
then
echo `date`: windows_client_allow_roaming_profile - $USERNAME already has a roaming profile by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
fi 

if [ `grep -c ^$REMOTE_USER: /opt/karoshi/web_controls/web_access_admin` != 1 ]
then
echo `date`: windows_client_allow_roaming_profile - access denied to $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE
exit 101
fi

########################
#Allow the roaming profile
########################
echo `date`: windows_client_allow_roaming_profile - Roaming profile enabled "for" $USERNAME by $REMOTE_USER from $REMOTE_ADDR >> /opt/karoshi/logs/karoshi_web_management/$LOG_DATE

#Create new profile folder for the user
cp -R /home/applications/profiles/default_roaming_profile /home/applications/profiles/$USERNAME
chown -c -R $USERNAME:itadmin /home/applications/profiles/$USERNAME 1>/dev/null
chmod 0660 -R /home/applications/profiles/$USERNAME
chmod u+X,g+X -R /home/applications/profiles/$USERNAME

if [ ! -d /home/applications/profiles/$USERNAME.V2 ]
then
mkdir /home/applications/profiles/$USERNAME.V2
chmod 0660 -R /home/applications/profiles/$USERNAME.V2
chmod u+X,g+X -R /home/applications/profiles/$USERNAME.V2
fi

if [ ! -d /home/applications/profiles/$USERNAME.V3 ]
then
mkdir /home/applications/profiles/$USERNAME.V3
chmod 0660 -R /home/applications/profiles/$USERNAME.V3
chmod u+X,g+X -R /home/applications/profiles/$USERNAME.V3
fi

if [ ! -d /home/applications/profiles/$USERNAME.V4 ]
then
mkdir /home/applications/profiles/$USERNAME.V4
chmod 0660 -R /home/applications/profiles/$USERNAME.V4
chmod u+X,g+X -R /home/applications/profiles/$USERNAME.V4
fi

#Set new profile path for the user
echo -e "dn: CN=$USERNAME,OU=$PRIMARYGROUP,OU=$SUBUNIT,OU=People,$LDAPBASE
changetype: modify
replace: profilePath
profilePath: \\\\$HOSTNAME\\applications\\profiles\\$USERNAME
-" | ldapmodify -x -D "CN=Administrator,CN=Users,$LDAPBASE" -w $LDAPPASS 1>/dev/null 2>>/opt/karoshi/logs/karoshi_web_management/$LOG_DATE


exit

