#!/bin/bash

#Get data
read DATA
DATA=`echo $DATA | tr -cd 'A-Za-z0-9\._:\-'`
[ $DATA'null' = null ] exit 101
REMOTE_USER=`echo "$DATA" | cut -s -d: -f1`
REMOTE_ADDR=`echo "$DATA" | cut -s -d: -f2`
REMOTE_MD5=`echo "$DATA" | cut -s -d: -f3`
FIRSTNAME=`echo "$DATA" | cut -s -d: -f4`
SURNAME=`echo "$DATA" | cut -s -d: -f5`
NEWUSERNAME=`echo "$DATA" | cut -s -d: -f6`

[ -d /opt/karoshi/.tempdata/airtime.$$ ] && rm -f -R /opt/karoshi/.tempdata/airtime.$$
mkdir /opt/karoshi/.tempdata/airtime.$$

#Dowload latest version of airtime
echo "<li>Downloading the latest version of airtime./</li>"
cd /opt/karoshi/.tempdata/airtime.$$
wget  http://apt.sourcefabric.org/misc/airtime-easy-setup.deb
[ `echo $?` != 0 ] && exit 102

#Install easy setup
echo "<li>Installaling airtime easy-setup.deb</li>"
dpkg -i airtime-easy-setup.deb
[ `echo $?` != 0 ] && exit 103

#Update repos
echo "<li>Updating repositories</li>"
sudo apt-get update
[ `echo $?` != 0 ] && exit 104

#Install airtime
echo "<li>Installing airtime</li>"
sudo apt-get install airtime 
[ `echo $?` != 0 ] && exit 105

#Configure airtime
echo "<li>Reconfiguring airtime</li>"
dpkg-reconfigure airtime
[ `echo $?` != 0 ] && exit 106
